Repository yamada-ui/yamada-ui, pull requests merged in 2024-09, with the labels that each got.

#2687 Fixed a bug where the right navigation item was not clickable
  docs/components/navigation/table-of-contents.tsx
Labels: review wanted, merge request

#2698 Updated MixedArray type definition
  docs/utils/array.ts
Labels: merge request

#2696 Updated contributor list order and entries
  docs/constant/contributors.ts
  docs/constant/members.ts
Labels: merge request

#2697 Removed unnecessary closing tags
  .changeset/tender-chefs-provide.md
  packages/components/select/src/select.tsx
Labels: merge request

#2699 Updated rounding in CountUp
  docs/components/transitions/count-up.tsx
Labels: merge request

#2705 Updated comments on loading behavior
  .changeset/twenty-pans-behave.md
  packages/core/src/theme.types.ts
Labels: merge request

#2704 Provided `systemColorMode`.
  .changeset/cuddly-cycles-chew.md
  docs/components/layouts/header.tsx
  examples/create-react-app/src/components/layouts/header.tsx
  examples/hono/src/components/layouts/header.tsx
  examples/next/app/components/layouts/header.tsx
  examples/next/pages/components/layouts/header.tsx
  examples/remix/app/components/layouts/header.tsx
  examples/vite/src/components/layouts/header.tsx
  packages/core/src/css/css.types.ts
  packages/core/src/providers/color-mode-manager.ts
  packages/core/src/providers/color-mode-provider.tsx
  packages/core/src/providers/color-mode-script.tsx
  packages/core/src/providers/color-mode-utils.ts
  packages/core/src/providers/environment-provider.tsx
Labels: review wanted, merge request

#2709 Enhance Test Coverage for @yamada-ui/switch
  packages/components/switch/tests/switch.test.tsx
Labels: merge request

#2712 Update forms documentation title
  docs/contents/components/forms/index.mdx
Labels: merge request

#2715 Add `zIndex` in CopyButton
  docs/components/forms/copy-button.tsx
Labels: merge request

#2730 Updated references from `var` to `vars`
  docs/contents/styled-system/css-custom-properties.ja.mdx
  docs/contents/styled-system/css-custom-properties.mdx
  docs/contents/styled-system/interpolation.ja.mdx
  docs/contents/styled-system/interpolation.mdx
Labels: merge request

#2717 Removed unnecessary `tabIndex` attribute
  .changeset/spicy-donkeys-appear.md
  packages/components/infinite-scroll-area/src/infinite-scroll-area.tsx
Labels: merge request

#2716 Simplify motion component logic
  .changeset/dirty-eagles-poke.md
  packages/components/motion/src/factory.ts
  packages/components/motion/src/motion-forward-ref.tsx
  packages/components/motion/src/motion.tsx
  packages/core/src/components/forward-ref.ts
  packages/core/src/styled.ts
Labels: merge request

#2729 Updated forwardRef implementations
  .changeset/serious-pans-watch.md
Labels: merge request

#2733 Improved error handling in changelog reader
  scripts/changelog.ts
Labels: merge request

#2727 Added `maxWidth` handling to components
  .changeset/nervous-mails-heal.md
  packages/components/autocomplete/src/autocomplete-list.tsx
  packages/components/popover/src/popover-content.tsx
  packages/components/select/src/select-list.tsx
Labels: merge request

#2741 Updated contributors and member details
  docs/constant/contributors.ts
  docs/constant/maintainers.ts
  docs/constant/members.ts
  docs/pages/insights/insights-utils.ts
Labels: merge request

#2739 Fixed a bug where `$` could not be used within the theme
  .changeset/swift-experts-unite.md
  packages/core/src/config/animation.ts
  packages/core/src/config/at-rule.ts
  packages/core/src/config/index.ts
  packages/core/src/config/utils.ts
  packages/core/src/css/css.ts
  packages/core/src/css/var.ts
  packages/core/src/theme.ts
  packages/core/src/theme.types.ts
Labels: merge request

#2743 Reorganize type definitions in files
  packages/components/autocomplete/src/autocomplete.tsx
  packages/components/transitions/src/collapse.tsx
  packages/components/transitions/src/fade.tsx
  packages/components/transitions/src/scale-fade.tsx
  packages/components/transitions/src/slide-fade.tsx
  packages/components/transitions/src/slide.tsx
Labels: merge request

#2750 Update pseudo and attribute selectors
  .changeset/sweet-toys-type.md
  packages/core/src/components/should-forward-prop.ts
  packages/core/src/css/css.ts
  packages/core/src/pseudos.ts
  packages/core/src/styles.ts
  scripts/generate-css/styles.ts
Labels: merge request

#2763 chore(eslint/test): set `vitest/no-commented-out-tests` to `off`
  .eslintrc.json
Labels: test, merge request

#2762 The Switch component type is wrong
  .changeset/thin-singers-exercise.md
  packages/components/switch/src/switch.tsx
Labels: merge request

#2752 Updated breakpoint base logic handling
  .changeset/smooth-lizards-hang.md
  packages/core/src/css/breakpoint.ts
  packages/core/src/theme.types.ts
Labels: merge request

#2747 test: add test for AlphaSlider component with pointer events
  packages/components/color-picker/tests/alpha-slider.test.tsx
Labels: merge request

#2756 Possible to generate CSS variables even in nested CSS objects.
  .changeset/fast-flowers-heal.md
  .changeset/old-avocados-trade.md
  packages/components/link/src/link-box.tsx
  packages/core/src/css/index.ts
  packages/core/src/css/use-var.ts
  packages/core/src/css/var.ts
  packages/core/src/theme.ts
  packages/core/tests/var.test.tsx
  packages/utils/src/object.ts
  packages/utils/tests/object.test.ts
Labels: merge request

#2737 feat:create yamada app update Remix template
  packages/create-yamada-app/src/templates/remix/app/root.tsx
  packages/create-yamada-app/src/templates/remix/app/routes/_index.tsx
  packages/create-yamada-app/src/templates/remix/app/tailwind.css
  packages/create-yamada-app/src/templates/remix/package.json
  packages/create-yamada-app/src/templates/remix/postcss.config.js
  packages/create-yamada-app/src/templates/remix/public/favicon.ico
  packages/create-yamada-app/src/templates/remix/public/favicon.svg
  packages/create-yamada-app/src/templates/remix/tailwind.config.ts
Labels: review wanted

#2766 Optimized theme provider logic
  .changeset/little-planets-float.md
  packages/core/src/providers/theme-provider.tsx
Labels: merge request

#2767 Optimized re-rendering with useMemo
  .changeset/warm-penguins-roll.md
  packages/hooks/use-breakpoint/src/index.ts
  packages/hooks/use-token/src/index.ts
Labels: merge request

#2768 Optimized styling and imports handling
  .changeset/sharp-lemons-talk.md
  packages/components/calendar/src/month.tsx
  packages/theme/src/components/calendar.ts
Labels: merge request

#2771 fix: delete commentout
  packages/components/select/tests/select.test.tsx
Labels: merge request

#2784 refactor: change error handling in sortNodes to use console.warn
  .changeset/popular-singers-joke.md
  packages/hooks/use-descendant/src/index.ts
Labels: merge request

#2778 Update renderHook usage and types
  .changeset/pretty-pumas-tickle.md
  cspell.json
  packages/hooks/use-breakpoint/tests/index.test.tsx
  packages/test/src/index.ts
  packages/test/src/render.tsx
Labels: merge request

#2786 Added `@media print` to atRules
  .changeset/smart-turkeys-appear.md
  packages/core/src/pseudos.ts
Labels: merge request

#2758 Corrected color mode expansion in css module
  .changeset/lucky-pianos-sit.md
  packages/components/carousel/src/carousel.tsx
  packages/components/modal/src/drawer.tsx
  packages/components/snacks/src/snacks.tsx
  packages/core/src/components/use-component-style.tsx
  packages/core/src/css/css.ts
  packages/core/src/css/css.types.ts
  packages/core/src/theme.types.ts
  packages/core/tests/component.test.tsx
  packages/hooks/use-value/src/index.ts
  packages/utils/src/color.ts
  stories/system/styles/color-mode.stories.tsx
  stories/system/styles/responsive.stories.tsx
Labels: review wanted, merge request

#2765 fixed `MonthPicker` tests
  packages/components/calendar/tests/month-picker.test.tsx
Labels: review wanted, merge request

#2789 Update data extraction and parsing logic
  docs/scripts/content/styled-system.ts
Labels: merge request

#2769 chore(deps): use `@koralle/vitest-axe` instead of `vitest-axe`
  .changeset/khaki-teachers-look.md
  package.json
  packages/test/src/accessibility.tsx
  pnpm-lock.yaml
  scripts/setup-test.ts
Labels: test, merge request

#2792 Changed prettier export to local function
  packages/components/lucide/scripts/generate-icons.ts
Labels: review wanted, merge request

#2788 Updated theme references and types
  .changeset/light-apricots-smash.md
  packages/core/@types/emotion.d.ts
  packages/core/src/components/component.types.ts
  packages/core/src/config/calc.ts
  packages/core/src/config/color-mix.ts
  packages/core/src/config/gradient.ts
  packages/core/src/config/grid.ts
  packages/core/src/css/css.types.ts
  packages/core/src/providers/theme-provider.tsx
  packages/core/src/theme.types.ts
  packages/core/tests/css.test.tsx
  packages/core/tests/theme.test.tsx
  packages/core/tsconfig.json
  packages/hooks/use-breakpoint/tests/index.test.tsx
  packages/hooks/use-token/src/index.ts
  packages/hooks/use-value/tests/index.test.tsx
  packages/theme-tools/src/extend-theme.ts
Labels: review wanted, merge request

#2809 Standardize capitalization in documentation
  docs/contents/components/other/motion/index.ja.mdx
  docs/contents/components/other/motion/index.mdx
  docs/contents/styled-system/animation.ja.mdx
  docs/contents/styled-system/animation.mdx
  docs/contents/styled-system/at-rules.ja.mdx
  docs/contents/styled-system/at-rules.mdx
Labels: merge request

#2808 Added `base` breakpoint configuration
  docs/contents/styled-system/configure/default-config.ja.mdx
  docs/contents/styled-system/configure/default-config.mdx
Labels: merge request

#2791 Added group and peer style handlers
  .changeset/sweet-maps-rest.md
  docs/scripts/content/styled-system.ts
  docs/theme/styles/mdx-styles.ts
  packages/core/src/pseudos.ts
  packages/utils/src/index.types.ts
  stories/system/styles/pseudo.stories.tsx
Labels: merge request

#2800 feat: useSelectList to support multi-select functionality
  .changeset/twelve-trains-itch.md
  packages/components/select/src/use-select.ts
Labels: merge request

#2783 test: add SaturationSlider component with pointer events
  packages/components/color-picker/tests/saturation-slider.test.tsx
Labels: merge request

#2822 feat: add test for ColorPickerEyeDropper cloning children
  packages/components/color-picker/tests/color-picker.test.tsx
Labels: merge request

#2820 Added `Fontawesome icon` test
  packages/components/fontawesome/package.json
  packages/components/fontawesome/tests/icon.test.tsx
  pnpm-lock.yaml
Labels: merge request

#2831 dosc: change type definition of items in autocomplete grouping example
  docs/contents/components/forms/autocomplete/index.ja.mdx
  docs/contents/components/forms/autocomplete/index.mdx
Labels: merge request

#2821 Added `useValue` test
  .changeset/rich-buckets-dress.md
  packages/hooks/use-value/src/index.ts
  packages/hooks/use-value/tests/index.test.tsx
Labels: merge request

#2813 Fixed width expansion issue in Drawer
  .changeset/smooth-panthers-join.md
  docs/components/layouts/header.tsx
  packages/components/modal/src/drawer-content.tsx
Labels: review wanted, merge request

#2829 Corrected date-value in `useMonth`
  .changeset/perfect-windows-cover.md
  packages/components/calendar/src/use-month.tsx
  packages/components/calendar/tests/calendar.test.tsx
  packages/components/calendar/tests/date-picker.test.tsx
  packages/components/calendar/tests/multi-date-picker.test.tsx
  packages/components/calendar/tests/range-date-picker.test.tsx
Labels: review wanted, merge request

#2836 Add 2xl breakpoint to useBreakpointValue example
  docs/contents/getting-started/advanced.ja.mdx
  docs/contents/getting-started/advanced.mdx
  docs/contents/hooks/use-breakpoint-value.ja.mdx
  docs/contents/hooks/use-breakpoint-value.mdx
  docs/contents/styled-system/responsive-styles.ja.mdx
  docs/contents/styled-system/responsive-styles.mdx
  stories/hooks/use-breakpoint.stories.tsx
Labels: merge request

#2834 Updated `Input` component handling
  .changeset/big-bottles-jog.md
  .changeset/nervous-avocados-occur.md
  packages/components/input/src/input-addon.tsx
  packages/components/input/src/input-context.tsx
  packages/components/input/src/input-element.tsx
  packages/components/input/src/input-group.tsx
  packages/core/src/config/vars.ts
  packages/core/src/css/breakpoint.ts
  packages/core/src/css/css.ts
  packages/core/src/css/use-var.ts
  packages/core/src/theme.ts
  packages/core/tests/var.test.tsx
Labels: merge request

#2838 Fixed outline display on focus for menu elements
  .changeset/warm-socks-live.md
  packages/components/popover/src/popover-content.tsx
  packages/theme/src/components/menu.ts
Labels: merge request

#2839 Update pr condition and add checks
  .github/workflows/docs.yml
Labels: merge request

#2825 Expanded the functionality so that you can set responsive objects in the theme
  .changeset/pink-guests-crash.md
  .changeset/shiny-elephants-mate.md
  .changeset/wicked-dodos-whisper.md
  cspell.json
  packages/cli/@types/node-eval.d.ts
  packages/cli/package.json
  packages/cli/src/command/tokens/config.ts
  packages/cli/src/command/tokens/create-theme-typings.ts
  packages/cli/src/command/tokens/index.ts
  packages/cli/src/index.ts
  packages/cli/src/utils/index.ts
  packages/cli/src/utils/module.ts
  packages/cli/src/utils/object.ts
  packages/core/src/css/breakpoint.ts
  packages/core/src/css/css.ts
  packages/core/src/css/var.ts
  packages/core/src/theme.ts
  packages/core/src/theme.types.ts
  packages/core/tests/theme.test.tsx
  pnpm-lock.yaml
Labels: review wanted, merge request

#2843 Fixed insight script
  scripts/report-insights.ts
Labels: merge request

#2919 Add fieldFontSize to input context and elements
  packages/components/input/src/input-context.tsx
  packages/components/input/src/input-element.tsx
  packages/components/input/src/input-group.tsx
Labels: merge request

#2923 Set `displayName` and `__ui__` after each component definition.
  .changeset/fluffy-actors-eat.md
  packages/components/breadcrumb/src/breadcrumb.tsx
Labels: merge request

#2925 Set displayName and __ui__ for the Skeleton component
  .changeset/serious-camels-play.md
  packages/components/skeleton/src/skeleton-circle.tsx
  packages/components/skeleton/src/skeleton-text.tsx
  packages/components/skeleton/src/skeleton.tsx
Labels: merge request

#2537 fix: remove the size of the Icon compoent in v2
  .changeset/mighty-geese-cheer.md
  .changeset/spotty-peaches-shop.md
  packages/components/fontawesome/src/icon.tsx
  packages/components/icon/src/icon.tsx
  packages/components/loading/src/loading.tsx
  packages/core/src/theme.types.ts
  packages/theme/src/components/loading.ts
Labels: help wanted, review wanted

#2710 fix: remove size from image component
  .changeset/big-ducks-do.md
  packages/components/image/src/image.tsx
Labels: review wanted

#2734 Make aria-label of IconButton mandatory
  .changeset/plenty-doors-enjoy.md
  docs/components/forms/search.tsx
  docs/components/layouts/header.tsx
  docs/pages/examples/cards/bookmark-card.tsx
  docs/pages/examples/mail/detail.tsx
  docs/pages/examples/mail/sidebar.tsx
  docs/pages/examples/music/sidebar.tsx
  docs/pages/examples/playground/footer/index.tsx
  docs/pages/examples/playground/header/control-button.tsx
  docs/pages/examples/playground/header/share-button.tsx
  docs/pages/insights/total-chart.tsx
  examples/create-react-app/src/components/layouts/header.tsx
  examples/hono/src/components/layouts/header.tsx
  examples/next/app/components/layouts/header.tsx
  examples/next/pages/components/layouts/header.tsx
  examples/remix/app/components/layouts/header.tsx
  examples/vite/src/components/layouts/header.tsx
  packages/components/button/src/icon-button.tsx
  packages/components/calendar/src/calendar-header.tsx
  packages/components/calendar/src/use-calendar-header.tsx
  packages/components/carousel/src/carousel-control.tsx
  packages/components/carousel/src/use-carousel.ts
  packages/components/color-picker/src/color-selector-eye-dropper.tsx
Labels: review wanted

#2927 feat: add display name for visually hidden elements
  .changeset/honest-dragons-trade.md
  packages/components/visually-hidden/src/visually-hidden.tsx
Labels: merge request

#2922 Added `findChild`
  .changeset/flat-tools-hang.md
  .changeset/moody-ravens-travel.md
  packages/components/accordion/src/accordion-item.tsx
  packages/components/carousel/src/carousel.tsx
  packages/components/form-control/src/fieldset.tsx
  packages/components/form-control/src/form-control.tsx
  packages/components/modal/src/dialog.tsx
  packages/components/modal/src/modal.tsx
  packages/components/slider/src/range-slider.tsx
  packages/components/slider/src/slider.tsx
  packages/components/stat/src/stat.tsx
  packages/components/tabs/src/tabs.tsx
  packages/utils/src/react.tsx
Labels: merge request

#2928 Updated variable bindings for clarity
  packages/components/pagination/src/pagination.tsx
  packages/components/pagination/src/use-pagination.ts
  packages/components/skeleton/src/skeleton-text.tsx
  packages/components/skeleton/src/skeleton.tsx
Labels: merge request

#2931 fix: set display-name in `textarea` component
  .changeset/curvy-sloths-sing.md
  packages/components/textarea/src/textarea.tsx
Labels: merge request

#2932 fix: fix ModalOverlay height
  .changeset/few-squids-exercise.md
  packages/components/modal/src/modal-overlay.tsx
Labels: merge request

#2934 feat: set ui after each component definition
  .changeset/cuddly-frogs-heal.md
  packages/components/radio/src/radio-group.tsx
  packages/components/radio/src/radio.tsx
Labels: merge request

#2937 fix: add displayName and __ui__ to alert component
  .changeset/beige-lamps-serve.md
  packages/components/alert/src/alert.tsx
Labels: merge request

#2933 feat: set displayName and __ui__ for color-picker
  .changeset/thick-games-pretend.md
  packages/components/color-picker/src/alpha-slider.tsx
  packages/components/color-picker/src/color-picker.tsx
  packages/components/color-picker/src/color-selector-body.tsx
  packages/components/color-picker/src/color-selector-channels.tsx
  packages/components/color-picker/src/color-selector-eye-dropper.tsx
  packages/components/color-picker/src/color-selector-sliders.tsx
  packages/components/color-picker/src/color-selector-swatches.tsx
  packages/components/color-picker/src/color-selector.tsx
  packages/components/color-picker/src/color-swatch.tsx
  packages/components/color-picker/src/hue-slider.tsx
  packages/components/color-picker/src/saturation-slider.tsx
Labels: merge request

#2942 Added `FunctionComponent` and `FC` type
  .changeset/ninety-boats-sniff.md
  packages/core/src/components/component.types.ts
  packages/utils/src/index.types.ts
Labels: merge request

#2920 DisplayName set for the component of `accordion`
  .changeset/brown-hairs-unite.md
  packages/components/accordion/src/accordion-item.tsx
  packages/components/accordion/src/accordion-label.tsx
  packages/components/accordion/src/accordion-panel.tsx
  packages/components/accordion/src/accordion.tsx
Labels: review wanted, merge request

#2941 Add responsive theme settings and notes
  docs/contents/styled-system/configure/default-config.ja.mdx
  docs/contents/styled-system/configure/default-config.mdx
  docs/contents/styled-system/theming/customize-theme.ja.mdx
  docs/contents/styled-system/theming/customize-theme.mdx
Labels: merge request

#2943 Added new color calculations and tests
  packages/core/tests/config.test.ts
  packages/core/tests/css.test.tsx
  packages/core/tests/theme.test.tsx
Labels: merge request

#2939 fix: add displayName and __ui__ to badge component
  .changeset/neat-mayflies-remember.md
  packages/components/badge/src/badge.tsx
Labels: merge request

#2949 Add displayName and __ui__ to switch component
  .changeset/rude-emus-fail.md
  packages/components/switch/src/switch.tsx
Labels: merge request

#2947 Set displayName the component of `ColorPicker`
  .changeset/breezy-hornets-juggle.md
  packages/components/color-picker/src/color-selector-eye-dropper.tsx
Labels: merge request

#2948 Feat set display name and UI for transitions
  .changeset/nice-worms-drum.md
  packages/components/transitions/src/collapse.tsx
  packages/components/transitions/src/fade.tsx
  packages/components/transitions/src/scale-fade.tsx
  packages/components/transitions/src/slide-fade.tsx
  packages/components/transitions/src/slide.tsx
Labels: merge request

#2954 fix: add displayName and __ui__ to tooltip component
  .changeset/unlucky-balloons-cheer.md
  packages/components/tooltip/src/tooltip.tsx
Labels: merge request

#2938 Add `displayName` and `__ui__` to components
  .changeset/stale-cherries-prove.md
  packages/components/typography/src/heading.tsx
  packages/components/typography/src/text.tsx
Labels: merge request

#2944 fix: set displayName and __ui__
  .changeset/shy-tigers-joke.md
  packages/components/toggle/src/toggle-group.tsx
  packages/components/toggle/src/toggle.tsx
  packages/components/toggle/tests/toggle-group.test.tsx
  packages/components/toggle/tests/toggle.test.tsx
Labels: merge request

#2936 fix: add displayName about forwardref components
  .changeset/rare-ravens-train.md
  packages/components/calendar/src/calendar-header.tsx
  packages/components/calendar/src/calendar.tsx
  packages/components/calendar/src/date-picker.tsx
  packages/components/calendar/src/month-list.tsx
  packages/components/calendar/src/month-picker.tsx
  packages/components/calendar/src/month.tsx
  packages/components/calendar/src/multi-date-picker.tsx
  packages/components/calendar/src/range-date-picker.tsx
  packages/components/calendar/src/year-list.tsx
  packages/components/calendar/src/year-picker.tsx
Labels: merge request

#2964 Added waitFor in calendar tests
  packages/components/calendar/tests/calendar.test.tsx
Labels: merge request

#2958 feat: create-yamada-app update Hono template
  packages/create-yamada-app/src/templates/hono/favicon.svg
  packages/create-yamada-app/src/templates/hono/src/client.tsx
  packages/create-yamada-app/src/templates/hono/src/index.tsx
Labels: merge request

#2917 Updated `useSelectOption` signature
  .changeset/loud-mugs-destroy.md
  cspell.json
  packages/components/select/src/option.tsx
  packages/components/select/src/use-select.ts
Labels: review wanted, merge request

#2950 Set displayName and __ui__ after each component definition.
  .changeset/eight-pens-cheat.md
  packages/components/popover/src/popover-anchor.tsx
  packages/components/popover/src/popover-body.tsx
  packages/components/popover/src/popover-close-button.tsx
  packages/components/popover/src/popover-content.tsx
  packages/components/popover/src/popover-footer.tsx
  packages/components/popover/src/popover-header.tsx
  packages/components/popover/src/popover-trigger.tsx
  packages/components/popover/src/popover.tsx
Labels: merge request

#2713 test(slider): Refactoring of RangeSlider test code
  packages/components/slider/tests/range-slider-mark.test.tsx
  packages/components/slider/tests/slider-mark.test.tsx
Labels: test

#2966 Simplified branch condition checks in script
  docs/ignored-build-step.sh
Labels: merge request

#2967 Update scripts and improve type annotations
  cspell.json
  package.json
  plopfile.ts
  pnpm-lock.yaml
Labels: merge request

#2956 docs: getting-started hono fix type error
  docs/contents/getting-started/frameworks/hono.ja.mdx
  docs/contents/getting-started/frameworks/hono.mdx
Labels: merge request

#2971 Updated eslint options in documentation
  CONTRIBUTING.ja.md
  CONTRIBUTING.md
  docs/contents/community/contributing.ja.mdx
  docs/contents/community/contributing.mdx
Labels: merge request

#2975 Set displayName and __ui__ at @yamada-ui/tabs
  .changeset/eight-geese-help.md
  packages/components/tabs/src/tab-list.tsx
  packages/components/tabs/src/tab-panel.tsx
  packages/components/tabs/src/tab-panels.tsx
  packages/components/tabs/src/tab.tsx
  packages/components/tabs/src/tabs.tsx
Labels: merge request

#2977 Changed `isClick` to `isClickable`
  docs/contents/components/forms/file-input/index.ja.mdx
  docs/contents/components/forms/file-input/index.mdx
  docs/contents/components/forms/input/index.ja.mdx
  docs/contents/components/forms/input/index.mdx
  stories/components/forms/file-input.stories.tsx
Labels: merge request

#2960 Set the displayName in `Autocomplete`
  .changeset/famous-seals-look.md
  packages/components/autocomplete/src/autocomplete-create.tsx
  packages/components/autocomplete/src/autocomplete-empty.tsx
  packages/components/autocomplete/src/autocomplete-icon.tsx
  packages/components/autocomplete/src/autocomplete-list.tsx
  packages/components/autocomplete/src/autocomplete-option-group.tsx
  packages/components/autocomplete/src/autocomplete-option.tsx
  packages/components/autocomplete/src/autocomplete.tsx
  packages/components/autocomplete/src/multi-autocomplete.tsx
Labels: merge request

#2976 feat: set display name and UI for scroll-area
  .changeset/loud-toys-clean.md
  packages/components/scroll-area/src/scroll-area.tsx
Labels: merge request

#2973 Set `displayName` and ` __ui__ ` at `@yamada-ui/carousel`
  .changeset/honest-deers-notice.md
  packages/components/carousel/src/carousel-control.tsx
  packages/components/carousel/src/carousel-indicators.tsx
  packages/components/carousel/src/carousel-slide.tsx
  packages/components/carousel/src/carousel.tsx
Labels: merge request

#2965 Set the displayName for `Button`
  .changeset/many-lemons-scream.md
  packages/components/button/src/button-group.tsx
  packages/components/button/src/button.tsx
  packages/components/button/src/icon-button.tsx
Labels: review wanted, merge request

#2929 Standardize id generation across components
  .changeset/plenty-pugs-rhyme.md
  packages/components/accordion/src/accordion-item.tsx
  packages/components/autocomplete/src/use-autocomplete-list.ts
  packages/components/autocomplete/src/use-autocomplete-option.ts
  packages/components/calendar/src/use-calendar-picker.ts
  packages/components/checkbox/src/checkbox.tsx
  packages/components/form-control/src/fieldset.tsx
  packages/components/form-control/src/form-control.tsx
  packages/components/pin-input/src/pin-input.tsx
  packages/components/progress/src/circle-progress.tsx
  packages/components/radio/src/radio-group.tsx
  packages/components/radio/src/radio.tsx
  packages/components/rating/src/use-rating.tsx
  packages/components/resizable/src/use-resizable.ts
  packages/components/segmented-control/src/segmented-control.tsx
  packages/components/select/src/option.tsx
  packages/components/slider/src/range-slider.tsx
  packages/components/tooltip/src/tooltip.tsx
Labels: merge request

#2987 feat: set display name and UI for close-button
  .changeset/smooth-lemons-help.md
  packages/components/close-button/src/close-button.tsx
Labels: merge request

#2980 feat: set display name and UI for focus-lock
  .changeset/nasty-cobras-divide.md
  packages/components/focus-lock/src/focus-lock.tsx
Labels: merge request

#2845 Correct Loading's size to fontSize
  .changeset/thick-trees-rest.md
  docs/contents/components/data-display/infinite-scroll-area/index.ja.mdx
  docs/contents/components/data-display/infinite-scroll-area/index.mdx
  packages/components/loading/src/loading-provider.tsx
Labels: merge request

#2993 Updated dependencies
  .changeset/itchy-shrimps-grow.md
  .changeset/mighty-spies-fold.md
  docs/package.json
  examples/create-react-app/package.json
  examples/hono/package.json
  examples/next/app/package.json
  examples/next/pages/package.json
  examples/remix/package.json
  examples/vite/package.json
  package.json
  packages/cli/package.json
  packages/components/carousel/package.json
  packages/components/focus-lock/package.json
  packages/components/loading/package.json
  packages/components/lucide/package.json
  packages/components/lucide/src/icons/briefcase-conveyor-belt.tsx
  packages/components/lucide/src/icons/clock-alert.tsx
  packages/components/lucide/src/icons/file-user.tsx
  packages/components/lucide/src/icons/grid2x2-plus.tsx
  packages/components/lucide/src/icons/headphone-off.tsx
  packages/components/lucide/src/icons/index.ts
  packages/components/lucide/src/icons/index.types.tsx
  packages/components/lucide/src/icons/message-square-lock.tsx
  packages/components/lucide/src/icons/octagon-minus.tsx
  packages/components/markdown/package.json
  packages/components/modal/package.json
  packages/components/resizable/package.json
  packages/next/package.json
  pnpm-lock.yaml
Labels: merge request

#3005 Fixed a bug where component `props` documentation was not created correctly
  docs/contents/components/data-display/calendar/props.ja.mdx
  docs/contents/components/data-display/calendar/props.mdx
  docs/contents/components/data-display/table/props.ja.mdx
  docs/contents/components/data-display/table/props.mdx
  docs/contents/components/feedback/progress/props.ja.mdx
  docs/contents/components/feedback/progress/props.mdx
  docs/contents/components/forms/autocomplete/props.ja.mdx
  docs/contents/components/forms/autocomplete/props.mdx
  docs/contents/components/forms/button/props.ja.mdx
  docs/contents/components/forms/button/props.mdx
  docs/contents/components/forms/color-picker/props.ja.mdx
  docs/contents/components/forms/color-picker/props.mdx
  docs/contents/components/forms/select/props.ja.mdx
  docs/contents/components/forms/select/props.mdx
  docs/contents/components/forms/slider/props.ja.mdx
  docs/contents/components/forms/slider/props.mdx
  docs/contents/components/navigation/link/props.ja.mdx
  docs/contents/components/navigation/link/props.mdx
  docs/contents/components/overlay/modal/props.ja.mdx
  docs/contents/components/overlay/modal/props.mdx
  docs/scripts/component/props.ts
Labels: merge request

#3000 Fixed resize and slide watch settings
  .changeset/small-onions-switch.md
  packages/components/carousel/src/use-carousel.ts
Labels: merge request

#3006 fix: set display-name in image component #2871
  .changeset/dull-jobs-know.md
  packages/components/image/src/image.tsx
Labels: merge request

#2995 Updated cleaning scripts and tsbuildinfo config
  cspell.json
  docs/package.json
  package.json
Labels: merge request

#2992 Update prop from `size` to `boxSize`
  docs/contents/components/feedback/circle-progress/index.ja.mdx
  docs/contents/components/feedback/circle-progress/index.mdx
  packages/components/progress/tests/circle-progress.test.tsx
Labels: merge request

#2999 Update checkbox icon component names
  .changeset/short-paws-approve.md
  packages/components/checkbox/src/checkbox.tsx
Labels: merge request

#2984 Build only packages with dependencies
  .github/workflows/quality.yml
  package.json
  pnpm-lock.yaml
  scripts/dependency-build.ts
Labels: merge request

#3012 fix: add displayName and __ui__ to a component in "@yamada-ui/fontawesome"
  .changeset/six-cups-stare.md
  packages/components/fontawesome/src/icon.tsx
Labels: merge request

#3016 Set `displayName` and `__ui__` in `@yamada-ui/alert`.
  .changeset/nine-kings-hide.md
  packages/components/alert/src/alert.tsx
Labels: merge request

#2994 fix: set displayname and __ui__ to dropzone
  .changeset/soft-trains-judge.md
  packages/components/dropzone/src/dropzone.tsx
Labels: review wanted

#2996 fix: set displayname and __ui__ to editable
  .changeset/twenty-waves-serve.md
  packages/components/editable/src/editable.tsx
Labels: review wanted

#2998 Rename button component elements and props
  .changeset/slimy-timers-judge.md
  packages/components/button/src/button.tsx
Labels: review wanted, merge request

#3028 Update contributor and member lists
  docs/constant/contributors.ts
  docs/constant/emeriti.ts
  docs/constant/maintainers.ts
  docs/constant/members.ts
Labels: merge request
