Repository yamada-ui/yamada-ui, pull requests merged in 2024-06, with the labels that each got.

#1720 Update `FileButton` Tests
  packages/components/file-button/tests/file-button.test.tsx
Labels: test

#1702 Update tests for `Card`
  packages/components/card/tests/card.test.tsx
Labels: test

#1925 Updated `color-picker` test
  packages/components/color-picker/tests/color-picker.test.tsx
Labels: test

#1740 Update `Tabs` tests
  packages/components/tabs/tests/tabs.test.tsx
Labels: test

#1735 Fixed useResizeObserver test
  packages/hooks/use-resize-observer/tests/index.test.tsx
Labels: test

#2055 Improved accessibility and refactoring code
  .changeset/kind-crabs-teach.md
  packages/components/tooltip/src/tooltip.tsx
Labels: a11y

#2032 Add accessibility documentation
  docs/contents/components/disclosure/tabs/accessibility.ja.mdx
  docs/contents/components/disclosure/tabs/accessibility.mdx
  docs/contents/components/navigation/breadcrumb/accessibility.ja.mdx
  docs/contents/components/navigation/breadcrumb/accessibility.mdx
Labels: a11y

#1995 Make the Calendar component headless
  .changeset/real-tips-compare.md
  packages/components/calendar/src/calendar-header.tsx
  packages/components/calendar/src/calendar.tsx
  packages/components/calendar/src/date-picker.tsx
  packages/components/calendar/src/month-list.tsx
  packages/components/calendar/src/month-picker.tsx
  packages/components/calendar/src/month.tsx
  packages/components/calendar/src/multi-date-picker.tsx
  packages/components/calendar/src/range-date-picker.tsx
  packages/components/calendar/src/year-list.tsx
  packages/components/calendar/src/year-picker.tsx
  packages/theme/src/components/calendar.ts
  packages/theme/src/components/date-picker.ts
Labels: help wanted

#2080 Update @yamada-ui/breadcrumb accessibility
  .changeset/large-bats-camp.md
  packages/components/breadcrumb/src/breadcrumb.tsx
Labels: a11y

#2060 Update @yamada-ui/slider accessibility
  .changeset/smooth-trees-swim.md
  packages/components/slider/src/range-slider.tsx
  packages/components/slider/src/slider.tsx
Labels: a11y

#2018 Make Carousel component headless.
  .changeset/big-islands-leave.md
  packages/components/carousel/src/carousel-control.tsx
  packages/components/carousel/src/carousel-indicators.tsx
  packages/components/carousel/src/carousel.tsx
  packages/theme/src/components/carousel.ts
Labels: help wanted

#2121 Enhance `<Switch >` component accessibilities
  .changeset/tiny-beds-unite.md
  packages/components/switch/src/switch.tsx
  packages/components/switch/tests/switch.test.tsx
Labels: a11y

#2134 Enhance `Modal` compoennt accessibility
  .changeset/itchy-donuts-sleep.md
  packages/components/modal/src/modal.tsx
  packages/components/modal/tests/modal.test.tsx
Labels: a11y

#2046 Make the `@yamada-ui/charts` component headless
  .changeset/rotten-peas-smash.md
  packages/components/charts/src/area-chart.tsx
  packages/components/charts/src/bar-chart.tsx
  packages/components/charts/src/donut-chart.tsx
  packages/components/charts/src/line-chart.tsx
  packages/components/charts/src/pie-chart.tsx
  packages/components/charts/src/radar-chart.tsx
  packages/components/charts/src/use-area-chart.ts
  packages/components/charts/src/use-bar-chart.ts
  packages/components/charts/src/use-line-chart.ts
  packages/components/charts/src/use-pie-chart.ts
  packages/components/charts/src/use-radar-chart.ts
  packages/theme/src/components/area-chart.ts
  packages/theme/src/components/bar-chart.ts
  packages/theme/src/components/line-chart.ts
  packages/theme/src/components/pie-chart.ts
  packages/theme/src/components/radar-chart.ts
Labels: help wanted, review wanted

#2115 Replace the example pages icon with `"@yamada-ui/lucide"`
  .eslintignore
  docs/components/media-and-icons/apple.tsx
  docs/components/media-and-icons/index.ts
  docs/components/media-and-icons/paypal.tsx
  docs/pages/examples/authentication/company.tsx
  docs/pages/examples/cards/bookmark-card.tsx
  docs/pages/examples/cards/github-card.tsx
  docs/pages/examples/cards/notification-card.tsx
  docs/pages/examples/cards/payment-method-card.tsx
  docs/pages/examples/dashboard/cards.tsx
  docs/pages/examples/dashboard/index.tsx
  docs/pages/examples/mail/detail.tsx
  docs/pages/examples/mail/inbox.tsx
  docs/pages/examples/mail/sidebar.tsx
  docs/pages/examples/music/content.tsx
  docs/pages/examples/music/header.tsx
  docs/pages/examples/music/sidebar.tsx
  docs/pages/examples/playground/footer/index.tsx
  docs/pages/examples/playground/header/control-button.tsx
  docs/pages/examples/tasks/data-table.tsx
  docs/pages/examples/tasks/data.tsx
  docs/pages/examples/tasks/filter.tsx
Labels: review wanted

#2054 Enhance `Calendar` accessibilities
  .changeset/strong-onions-invent.md
  packages/components/calendar/src/month-list.tsx
  packages/components/calendar/src/month.tsx
  packages/components/calendar/src/year-list.tsx
  packages/components/calendar/tests/calendar.test.tsx
Labels: a11y, review wanted

#2159 add test for `notice`
  packages/components/notice/tests/notice.test.tsx
Labels: test

#2139 Increased test coverage for use-resize-observer
  packages/hooks/use-resize-observer/tests/index.test.tsx
Labels: review wanted

#2146 fix(storybook): typo of delay close text
  stories/components/overlay/tooltip.stories.tsx
Labels: review wanted

#2113 Docs: Add `Radio` accessibility docs
  docs/contents/components/forms/radio/accessibility.ja.mdx
  docs/contents/components/forms/radio/accessibility.mdx
Labels: a11y, review wanted

#2137 add accessibility section for `Alert`
  docs/contents/components/feedback/alert/accessibility.ja.mdx
  docs/contents/components/feedback/alert/accessibility.mdx
Labels: a11y, review wanted

#2176 Updated reviewer filtering logic
  docs/pages/api/github/webhook/pull-request/opened.ts
  docs/pages/api/github/webhook/pull-request/review-request-removed.ts
Labels: request merge

#2184 Fix a typo about `check` in `List` component
  docs/contents/components/data-display/list/index.mdx
Labels: request merge

#2194 Standardized self-closing tags by adding space
  packages/components/button/tests/button-group.test.tsx
  packages/components/button/tests/button.test.tsx
  packages/components/button/tests/icon-button.test.tsx
  packages/components/carousel/tests/carousel.test.tsx
  packages/components/file-button/tests/file-button.test.tsx
  packages/components/highlight/tests/highlight.test.tsx
  packages/components/icon/tests/icon.test.tsx
  packages/components/pagination/tests/pagination.test.tsx
  packages/components/radio/tests/radio-group.test.tsx
  packages/components/radio/tests/radio.test.tsx
  packages/components/stepper/tests/stepper.test.tsx
  packages/components/tooltip/tests/tooltip.test.tsx
Labels: request merge

#2182 Enhance the accessibility of `AvatarGroup`
  .changeset/chatty-snails-begin.md
  packages/components/avatar/src/avatar-group.tsx
Labels: merge request

#2187 test(modal): enhance test coverage for @yamada/modal
  packages/components/modal/tests/modal.test.tsx
Labels: merge request

#2188 Enhance Test Coverage for @yamada-ui/use-os
  packages/hooks/use-os/tests/use-os.test.tsx
Labels: merge request

#2135 Update `@yamada-ui/table` accessibility
  .changeset/heavy-shoes-hear.md
  packages/components/table/src/tbody.tsx
  packages/components/table/src/thead.tsx
  packages/components/table/src/use-table.tsx
Labels: a11y, review wanted

#2199 test(use-resize-observer): rewrite a mock of `ResizeObserver`
  packages/hooks/use-resize-observer/tests/index.test.tsx
Labels: test, merge request

#2202 Updated report command, added publish option
  .github/workflows/insight.yml
  package.json
  scripts/report-insight.ts
  scripts/report-insights.ts
  scripts/utils.ts
Labels: merge request

#2203 Update contributor and maintainer lists
  docs/constant/contributors.ts
  docs/constant/maintainers.ts
  docs/constant/members.ts
Labels: merge request

#2191 Fixed `Radio` accessibility page
  docs/contents/components/forms/radio/accessibility.ja.mdx
Labels: documentation, a11y

#2192 Fixed the tooltip to close via the event handler for the `pointerdown` event when `closeOnPointerDown` is `true`.
  .changeset/rotten-dragons-think.md
  packages/components/tooltip/src/tooltip.tsx
  packages/components/tooltip/tests/tooltip.test.tsx
Labels: bug, merge request

#2206 Corrected `StringLiteral` type definition
  .changeset/eleven-lemons-confess.md
  packages/utils/src/index.types.ts
Labels: merge request
