Repository yamada-ui/yamada-ui, pull requests merged in 2024-11, with the labels that each got.

#3284 test(icon): enhance test coverage for icon
  packages/components/icon/tests/icon.test.tsx
Labels: test, coverage, review wanted, merge request

#3308 Added missing button type attribute
  .changeset/forty-shrimps-tell.md
  packages/components/pagination/src/pagination-item.tsx
Labels: merge request

#3306 Fixed a bug where search items were not generated correctly
  docs/i18n/content.en.json
  docs/i18n/content.ja.json
Labels: merge request

#3298 Added `role="radiogroup"` attribute
  .changeset/empty-peas-film.md
  packages/components/segmented-control/src/segmented-control.tsx
Labels: merge request

#3166 docs: add accessibility section for Rating component
  docs/contents/components/forms/rating/accessibility.ja.mdx
  docs/contents/components/forms/rating/accessibility.mdx
Labels: review wanted

#3305 Updated styling and removed unused code
  docs/components/mdx/index.tsx
  docs/components/navigation/table-of-contents.tsx
  docs/components/navigation/tree.tsx
  docs/pages/examples/[slug].page.tsx
  docs/theme/components/alert.ts
  docs/theme/components/index.ts
  docs/theme/components/mark.ts
  docs/theme/components/segmented-control.ts
Labels: merge request

#3310 Fixed label/value mismatch handling
  .changeset/chilly-rockets-beam.md
  packages/components/autocomplete/src/use-autocomplete.tsx
Labels: merge request

#3312 Add `waitFor` to async tests
  packages/hooks/use-async-callback/tests/index.test.tsx
Labels: merge request

#3304 Updated color shading across components
  .changeset/seven-grapes-burn.md
  .changeset/spotty-seals-warn.md
  packages/theme/src/components/alert.ts
  packages/theme/src/components/badge.ts
  packages/theme/src/components/blockquote.ts
  packages/theme/src/components/button.ts
  packages/theme/src/components/calendar.ts
  packages/theme/src/components/code.ts
  packages/theme/src/components/pagination.ts
  packages/theme/src/components/tabs.ts
  packages/theme/src/components/tag.ts
  packages/theme/src/components/toggle.ts
Labels: merge request

#3326 Added `"use client"` to `Rating`
  .changeset/itchy-bottles-allow.md
  packages/components/rating/package.json
Labels: merge request

#3317 Fixed style issue on closeButton focus
  .changeset/few-pumas-smell.md
  packages/theme/src/components/close-button.ts
Labels: review wanted, merge request

#3223 Enhance Test Coverage for @yamada-ui/modal
  packages/components/modal/tests/drawer.test.tsx
  packages/components/modal/tests/modal.test.tsx
Labels: review wanted, merge request

#3335 Fix close button section for `@yamda-ui/popover`
  docs/contents/components/overlay/popover/index.ja.mdx
  docs/contents/components/overlay/popover/index.mdx
Labels: merge request

#3328 fix(docs): fix usage section for Table component
  docs/contents/components/data-display/table/index.ja.mdx
  docs/contents/components/data-display/table/index.mdx
Labels: merge request

#3323 Added a11y doc for icon-button
  docs/contents/components/forms/icon-button/accessibility.ja.mdx
  docs/contents/components/forms/icon-button/accessibility.mdx
Labels: merge request

#3318 docs: add airy, rotate and flip docs
  docs/components/mdx/editable-code-block.tsx
  docs/contents/components/transitions/airy/index.ja.mdx
  docs/contents/components/transitions/airy/index.mdx
  docs/contents/components/transitions/airy/props.ja.mdx
  docs/contents/components/transitions/airy/props.mdx
  docs/contents/components/transitions/airy/theming.ja.mdx
  docs/contents/components/transitions/airy/theming.mdx
  docs/contents/components/transitions/flip/index.ja.mdx
  docs/contents/components/transitions/flip/index.mdx
  docs/contents/components/transitions/flip/props.ja.mdx
  docs/contents/components/transitions/flip/props.mdx
  docs/contents/components/transitions/flip/theming.ja.mdx
  docs/contents/components/transitions/flip/theming.mdx
  docs/contents/components/transitions/rotate/index.ja.mdx
  docs/contents/components/transitions/rotate/index.mdx
  docs/contents/components/transitions/rotate/props.ja.mdx
  docs/contents/components/transitions/rotate/props.mdx
  docs/contents/components/transitions/rotate/theming.ja.mdx
  docs/contents/components/transitions/rotate/theming.mdx
  docs/i18n/content.en.json
  docs/i18n/content.ja.json
  docs/scripts/component/props.ts
Labels: review wanted

#3342 Added `"use client"` to theme
  .changeset/kind-geese-jam.md
  packages/theme/package.json
Labels: merge request

#3240 feat(resizable): add `displayName` to `Resizable` and `ResizableItem`
  .changeset/soft-camels-marry.md
  packages/components/resizable/src/resizable-item.tsx
  packages/components/resizable/src/resizable-trigger.tsx
  packages/components/resizable/src/resizable.tsx
  packages/components/resizable/src/use-resizable.ts
Labels: review wanted

#3376 Set `displayName` and `__ui__` for `@yamada-ui/notice`
  .changeset/few-chairs-dream.md
  packages/components/notice/src/notice-provider.tsx
  packages/components/notice/src/notice.tsx
Labels: merge request

#3019 refactor: Update HueSlider accessibility
  .changeset/famous-melons-call.md
  packages/components/color-picker/src/alpha-slider.tsx
  packages/components/color-picker/src/hue-slider.tsx
  packages/components/color-picker/src/use-color-slider.ts
Labels: review wanted

#3390 fix: change import of @yamada-ui/lucide in disclosure of Storybook to *Icon
  stories/components/disclosure/accordion.stories.tsx
Labels: merge request

#3398 Remove unnecessary code in next pages example
  examples/next/pages/pages/index.tsx
Labels: merge request

#3272 fix(colorPicker): added necessary aria attribute to ColorPicker
  .changeset/brave-years-train.md
  packages/components/color-picker/src/color-picker.tsx
  packages/components/color-picker/src/use-color-picker.ts
  packages/components/color-picker/tests/color-picker.test.tsx
Labels: review wanted

#3377 Update dependencies and clean code
  .changeset/tough-planets-fix.md
  .changeset/wise-carrots-cry.md
  docs/package.json
  examples/create-react-app/package.json
  examples/hono/package.json
  examples/next/app/package.json
  examples/next/pages/package.json
  examples/remix/package.json
  examples/vite/package.json
  package.json
  packages/components/carousel/package.json
  packages/components/charts/package.json
  packages/components/lucide/package.json
  packages/components/lucide/src/icons/calendar1.tsx
  packages/components/lucide/src/icons/index.ts
  packages/components/lucide/src/icons/index.types.ts
  packages/components/lucide/src/icons/wind-arrow-down.tsx
  packages/components/modal/tests/modal.test.tsx
  packages/components/motion/package.json
  packages/components/motion/src/factory.ts
  packages/components/motion/src/index.ts
  packages/components/motion/src/motion.types.ts
  packages/components/resizable/package.json
  packages/components/transitions/tests/slide.test.tsx
  packages/core/package.json
  packages/hooks/use-async-callback/package.json
  packages/hooks/use-processing/package.json
  packages/next/package.json
  pnpm-lock.yaml
Labels: merge request

#3413 fix: fixed import of lucide icon in Alert
  .changeset/fast-garlics-pretend.md
  packages/components/alert/src/alert.tsx
  packages/components/alert/tests/alert.test.tsx
Labels: merge request

#3415 Disabled eslint in craco config
  examples/create-react-app/craco.config.js
Labels: merge request

#3424 fix: change import of @yamada-ui/lucide in navigation of storybook to *Icon
  stories/components/navigation/breadcrumb.stories.tsx
  stories/components/navigation/pagination.stories.tsx
  stories/components/navigation/stepper.stories.tsx
Labels: merge request

#3405 Add `Autocomplete` test
  packages/components/autocomplete/tests/autocomplete.test.tsx
Labels: merge request

#3429 Update transition documentation wording
  docs/contents/components/transitions/airy/index.ja.mdx
  docs/contents/components/transitions/airy/index.mdx
  docs/contents/components/transitions/flip/index.ja.mdx
  docs/contents/components/transitions/flip/index.mdx
  docs/contents/components/transitions/rotate/index.ja.mdx
  docs/contents/components/transitions/rotate/index.mdx
Labels: merge request

#3431 Updated .gitignore and .nvmrc versions
  .gitignore
  .nvmrc
Labels: merge request

#3427 Corrected component name in descriptions
  docs/contents/components/data-display/color-swatch/props.ja.mdx
  docs/contents/components/data-display/color-swatch/theming.ja.mdx
Labels: merge request

#3440 Updated layout page title to plural
  docs/contents/components/layouts/index.mdx
Labels: merge request

#3337 feat(docs): add accessibility section for HueSlider component
  docs/contents/components/forms/hue-slider/accessibility.ja.mdx
  docs/contents/components/forms/hue-slider/accessibility.mdx
  docs/contents/components/forms/hue-slider/index.ja.mdx
  docs/contents/components/forms/hue-slider/index.mdx
  stories/components/forms/hue-slider.stories.tsx
Labels: review wanted

#3320 feat: rename left and right to start and end
  .changeset/real-penguins-itch.md
  packages/components/button/src/button.tsx
  packages/components/button/src/icon-button.tsx
  packages/components/button/tests/button.test.tsx
  packages/components/tag/src/tag.tsx
  packages/components/tag/tests/tag.test.tsx
  stories/components/data-display/tag.stories.tsx
  stories/components/forms/button.stories.tsx
  stories/components/overlay/menu.stories.tsx
Labels: review wanted

#3443 fix: icon imports
  stories/components/forms/autocomplete.stories.tsx
  stories/components/forms/button.stories.tsx
  stories/components/forms/color-picker.stories.tsx
  stories/components/forms/date-picker.stories.tsx
  stories/components/forms/dropzone.stories.tsx
  stories/components/forms/editable.stories.tsx
  stories/components/forms/file-button.stories.tsx
  stories/components/forms/file-input.stories.tsx
  stories/components/forms/input.stories.tsx
  stories/components/forms/month-picker.stories.tsx
  stories/components/forms/multi-autocomplete.stories.tsx
  stories/components/forms/multi-date-picker.stories.tsx
  stories/components/forms/multi-select.stories.tsx
  stories/components/forms/native-select.stories.tsx
  stories/components/forms/range-date-picker.stories.tsx
  stories/components/forms/range-slider.stories.tsx
  stories/components/forms/rating.stories.tsx
  stories/components/forms/select.stories.tsx
  stories/components/forms/slider.stories.tsx
  stories/components/forms/toggle.stories.tsx
  stories/components/forms/year-picker.stories.tsx
Labels: merge request

#3452 Replace FormControl with Fieldset
  docs/contents/components/forms/segmented-control/index.ja.mdx
  docs/contents/components/forms/segmented-control/index.mdx
  stories/components/forms/segmented-control.stories.tsx
Labels: merge request

#3453 Update Japanese button accessibility doc
  docs/contents/components/forms/button/accessibility.ja.mdx
Labels: merge request

#3444 Updated accessibility documentation
  docs/contents/components/forms/editable/accessibility.ja.mdx
  docs/contents/components/forms/editable/accessibility.mdx
  docs/contents/components/forms/editable/index.ja.mdx
  docs/contents/components/forms/editable/index.mdx
  stories/components/forms/editable.stories.tsx
Labels: merge request

#3449 Replace FormControl with Fieldset in docs
  docs/contents/components/forms/range-slider/index.ja.mdx
  docs/contents/components/forms/range-slider/index.mdx
  docs/contents/components/forms/saturation-slider/index.ja.mdx
  docs/contents/components/forms/saturation-slider/index.mdx
  docs/contents/components/forms/slider/index.ja.mdx
  docs/contents/components/forms/slider/index.mdx
  stories/components/forms/color-selector.stories.tsx
  stories/components/forms/range-slider.stories.tsx
  stories/components/forms/saturation-slider.stories.tsx
  stories/components/forms/slider.stories.tsx
Labels: merge request

#3447 Update checkbox accessibility handling
  docs/contents/components/forms/checkbox/accessibility.ja.mdx
  docs/contents/components/forms/checkbox/accessibility.mdx
  docs/contents/components/forms/checkbox/index.ja.mdx
  docs/contents/components/forms/checkbox/index.mdx
  stories/components/forms/checkbox.stories.tsx
Labels: merge request

#3471 Enhanced double-click functionality
  .changeset/dull-donkeys-attend.md
  packages/components/resizable/src/use-resizable.ts
Labels: merge request

#3459 Add accessibility documentation for textarea
  docs/contents/components/forms/textarea/accessibility.ja.mdx
  docs/contents/components/forms/textarea/accessibility.mdx
Labels: merge request

#3451 Replace FormControl with Fieldset
  docs/contents/components/forms/rating/index.ja.mdx
  docs/contents/components/forms/rating/index.mdx
  stories/components/forms/rating.stories.tsx
Labels: merge request

#3476 Update accessibility docs for file inputs
  docs/contents/components/forms/file-button/accessibility.ja.mdx
  docs/contents/components/forms/file-button/accessibility.mdx
  docs/contents/components/forms/file-input/accessibility.ja.mdx
  docs/contents/components/forms/file-input/accessibility.mdx
Labels: merge request

#3485 Added aria-orientation and type enhancements
  .changeset/tender-swans-cover.md
  packages/components/resizable/src/use-resizable.ts
Labels: merge request

#3470 Added aria labels and roles for accessibility
  .changeset/healthy-taxis-smash.md
  docs/contents/components/forms/number-input/accessibility.ja.mdx
  docs/contents/components/forms/number-input/accessibility.mdx
  packages/components/number-input/src/number-input.tsx
Labels: merge request

#3457 Updated accessibility documentation
  docs/contents/components/overlay/context-menu/accessibility.ja.mdx
  docs/contents/components/overlay/context-menu/accessibility.mdx
Labels: merge request

#3486 Corrected markdown link spacing and quotes
  docs/contents/components/forms/autocomplete/accessibility.ja.mdx
  docs/contents/components/forms/autocomplete/accessibility.mdx
  docs/contents/components/forms/checkbox/accessibility.mdx
  docs/contents/components/forms/multi-autocomplete/accessibility.ja.mdx
  docs/contents/components/forms/multi-autocomplete/accessibility.mdx
  docs/contents/components/forms/radio/accessibility.mdx
  docs/contents/components/overlay/menu/accessibility.ja.mdx
  docs/contents/components/overlay/menu/accessibility.mdx
  docs/contents/components/overlay/popover/accessibility.ja.mdx
  docs/contents/components/overlay/popover/accessibility.mdx
Labels: merge request

#3482 Added accessibility documentation for components
  docs/contents/components/forms/autocomplete/accessibility.ja.mdx
  docs/contents/components/forms/autocomplete/accessibility.mdx
  docs/contents/components/forms/multi-autocomplete/accessibility.ja.mdx
  docs/contents/components/forms/multi-autocomplete/accessibility.mdx
Labels: merge request

#3473 Add accessibility docs for resizable component
  docs/contents/components/data-display/resizable/accessibility.ja.mdx
  docs/contents/components/data-display/resizable/accessibility.mdx
Labels: merge request

#3483 Add Japanese accessibility docs for ColorPicker
  docs/contents/components/forms/color-picker/accessibility.ja.mdx
  docs/contents/components/forms/color-picker/accessibility.mdx
Labels: merge request

#3464 Added Japanese accessibility docs for range slider
  docs/contents/components/forms/range-slider/accessibility.ja.mdx
  docs/contents/components/forms/range-slider/accessibility.mdx
  docs/contents/components/forms/slider/accessibility.ja.mdx
  docs/contents/components/forms/slider/accessibility.mdx
Labels: merge request

#3480 Added accessibility documentation for components
  docs/contents/components/forms/multi-select/accessibility.ja.mdx
  docs/contents/components/forms/multi-select/accessibility.mdx
  docs/contents/components/forms/select/accessibility.ja.mdx
  docs/contents/components/forms/select/accessibility.mdx
Labels: merge request

#3477 Added accessibility details for Rating component
  docs/contents/components/forms/rating/accessibility.ja.mdx
  docs/contents/components/forms/rating/accessibility.mdx
Labels: merge request

#3461 Add Japanese accessibility docs for dropzone
  docs/contents/components/forms/dropzone/accessibility.ja.mdx
  docs/contents/components/forms/dropzone/accessibility.mdx
Labels: merge request

#3454 Add Japanese and English accessibility docs
  docs/contents/components/forms/fieldset/accessibility.ja.mdx
  docs/contents/components/forms/fieldset/accessibility.mdx
Labels: merge request

#3484 Updated accessibility documentation
  docs/contents/components/forms/alpha-slider/accessibility.ja.mdx
  docs/contents/components/forms/alpha-slider/accessibility.mdx
  docs/contents/components/forms/hue-slider/accessibility.ja.mdx
  docs/contents/components/forms/hue-slider/accessibility.mdx
Labels: merge request

#3502 Add enter key functionality to checkbox and switch
  .changeset/little-windows-sleep.md
  docs/contents/components/forms/switch/accessibility.ja.mdx
  docs/contents/components/forms/switch/accessibility.mdx
  packages/components/checkbox/src/checkbox.tsx
  packages/components/switch/src/switch.tsx
Labels: merge request

#3468 Add accessibility documentation for components
  docs/contents/components/feedback/circle-progress/accessibility.ja.mdx
  docs/contents/components/feedback/circle-progress/accessibility.mdx
  docs/contents/components/feedback/circle-progress/index.ja.mdx
  docs/contents/components/feedback/circle-progress/index.mdx
  docs/contents/components/feedback/progress/accessibility.ja.mdx
  docs/contents/components/feedback/progress/accessibility.mdx
  docs/contents/components/feedback/progress/index.ja.mdx
  docs/contents/components/feedback/progress/index.mdx
Labels: merge request

#3469 Add screen reader friendly value text
  .changeset/eighty-zebras-end.md
  packages/components/slider/src/range-slider.tsx
  packages/components/slider/src/slider.tsx
Labels: merge request

#3488 Adjust button styling in navigation links
  docs/components/navigation/related-links.tsx
Labels: merge request

#3490 Update accessibility roles and attributes
  .changeset/healthy-months-repair.md
  docs/contents/components/overlay/context-menu/accessibility.ja.mdx
  docs/contents/components/overlay/context-menu/accessibility.mdx
  packages/components/menu/src/context-menu-trigger.tsx
Labels: merge request

#3496 Updated accessibility documentation
  docs/contents/components/forms/alpha-slider/accessibility.ja.mdx
  docs/contents/components/forms/alpha-slider/accessibility.mdx
  docs/contents/components/forms/hue-slider/accessibility.ja.mdx
  docs/contents/components/forms/hue-slider/accessibility.mdx
  docs/contents/components/forms/range-slider/accessibility.ja.mdx
  docs/contents/components/forms/range-slider/accessibility.mdx
  docs/contents/components/forms/slider/accessibility.ja.mdx
  docs/contents/components/forms/slider/accessibility.mdx
Labels: merge request

#3448 Update form control to fieldset usage
  docs/contents/components/forms/radio/accessibility.ja.mdx
  docs/contents/components/forms/radio/accessibility.mdx
  docs/contents/components/forms/radio/index.ja.mdx
  docs/contents/components/forms/radio/index.mdx
  stories/components/forms/radio.stories.tsx
Labels: review wanted, merge request

#3467 Added accessibility attributes to progress components
  .changeset/perfect-maps-impress.md
  packages/components/progress/src/circle-progress.tsx
  packages/components/progress/src/progress.tsx
  packages/components/progress/tests/circle-progress.test.tsx
  packages/components/progress/tests/progress.test.tsx
  stories/components/feedback/circle-progress.stories.tsx
  stories/components/feedback/progress.stories.tsx
Labels: merge request

#3513 Updated variable names and conditions
  .changeset/sixty-kids-heal.md
  packages/components/calendar/src/calendar-header.tsx
  packages/components/calendar/src/use-calendar-header.tsx
  packages/components/calendar/src/use-year-list.tsx
  packages/components/calendar/tests/calendar.test.tsx
Labels: merge request

#3489 Changed `span` to `div` in ui elements
  .changeset/gold-geckos-taste.md
  packages/components/checkbox/src/checkbox.tsx
  packages/components/checkbox/tests/checkbox.test.tsx
  packages/components/radio/src/radio.tsx
  packages/components/switch/src/switch.tsx
Labels: review wanted, merge request

#3512 Updated Japanese accessibility docs
  docs/contents/components/data-display/calendar/accessibility.ja.mdx
  docs/contents/components/data-display/calendar/accessibility.mdx
  docs/contents/components/data-display/table/accessibility.ja.mdx
Labels: review wanted, merge request

#3495 Updated color-picker accessibility docs
  .changeset/sharp-keys-divide.md
  docs/contents/components/forms/color-picker/accessibility.ja.mdx
  docs/contents/components/forms/color-picker/accessibility.mdx
  docs/contents/components/forms/saturation-slider/accessibility.ja.mdx
  docs/contents/components/forms/saturation-slider/accessibility.mdx
  packages/components/color-picker/src/use-saturation-slider.ts
Labels: merge request

#3487 Updated aria attributes handling with refs
  .changeset/slow-chairs-brush.md
  packages/components/modal/src/drawer-content.tsx
  packages/components/modal/src/modal-body.tsx
  packages/components/modal/src/modal-content.tsx
  packages/components/modal/src/modal-context.ts
  packages/components/modal/src/modal-header.tsx
  packages/components/modal/src/modal.tsx
  packages/components/popover/src/popover-body.tsx
  packages/components/popover/src/popover-header.tsx
  packages/components/popover/src/popover.tsx
Labels: review wanted, merge request

#3521 Added "triage" label to issue filters
  docs/pages/api/github/observe/update-issues.ts
Labels: merge request

#3514 feat(Pagination): remove `is` prefix in props
  .changeset/tasty-phones-lick.md
  packages/components/pagination/src/pagination-item.tsx
  packages/components/pagination/src/pagination.tsx
  packages/components/pagination/src/use-pagination.ts
Labels: merge request

#3540 Replaced lucide icon to internal icon
  .changeset/proud-doors-shake.md
  .changeset/sweet-chicken-begin.md
  package.json
  packages/components/alert/package.json
  packages/components/alert/src/alert.tsx
  packages/components/alert/tests/alert.test.tsx
  packages/components/icon/src/icon.tsx
  pnpm-lock.yaml
Labels: merge request

#3463 Improved accessibility prop handling
  .changeset/fuzzy-months-tap.md
  packages/components/dropzone/src/dropzone.tsx
Labels: review wanted, merge request

#3442 `Accordion`: remove `is` prefix in props
  .changeset/gentle-planets-accept.md
  packages/components/accordion/src/accordion-context.tsx
  packages/components/accordion/src/accordion-item.tsx
  packages/components/accordion/src/accordion-label.tsx
  packages/components/accordion/src/accordion-panel.tsx
  packages/components/accordion/src/accordion.tsx
  stories/components/disclosure/accordion.stories.tsx
Labels: merge request

#3543 `Link`: remove is prefix in props
  .changeset/stale-singers-joke.md
  packages/components/link/src/link-box.tsx
  packages/components/link/src/link.tsx
  packages/components/link/tests/link.test.tsx
  stories/components/data-display/table.stories.tsx
  stories/components/navigation/link-box.stories.tsx
  stories/components/navigation/link.stories.tsx
Labels: merge request

#3472 feat: enhance keyboard interactions
  .changeset/yellow-grapes-whisper.md
  packages/components/pin-input/src/pin-input.tsx
  packages/components/pin-input/tests/pin-input.test.tsx
Labels: merge request

#3491 Remove `is` prefix in `@yamada-ui/autocomplete`
  .changeset/heavy-mugs-report.md
  packages/components/autocomplete/src/multi-autocomplete.tsx
  packages/components/autocomplete/src/use-autocomplete-option.ts
  packages/components/autocomplete/src/use-autocomplete.tsx
  packages/components/autocomplete/tests/autocomplete.test.tsx
  stories/components/forms/autocomplete.stories.tsx
Labels: merge request

#3561 feat(highlight): remove is prefix in props
  .changeset/neat-suns-pay.md
  packages/components/highlight/src/highlight.tsx
Labels: merge request

#3552 Standardize color to 'muted' across components
  .changeset/fair-waves-train.md
  docs/components/forms/search.tsx
  docs/components/navigation/related-links.tsx
  docs/pages/icons/list.tsx
  packages/theme/src/components/blockquote.ts
  packages/theme/src/components/calendar.ts
  packages/theme/src/components/color-selector.ts
  packages/theme/src/components/dropzone.ts
  packages/theme/src/components/form-control.ts
  packages/theme/src/components/line-chart.ts
  packages/theme/src/components/markdown.ts
  packages/theme/src/components/menu.ts
  packages/theme/src/components/native-table.ts
  packages/theme/src/components/radar-chart.ts
  packages/theme/src/components/stat.ts
  packages/theme/src/components/stepper.ts
Labels: merge request

#3553 Update dependencies and add new icons
  .changeset/lucky-bananas-mix.md
  .changeset/young-moons-stare.md
  docs/package.json
  examples/create-react-app/package.json
  examples/hono/package.json
  examples/next/app/package.json
  examples/next/pages/package.json
  examples/remix/package.json
  examples/vite/package.json
  package.json
  packages/components/carousel/package.json
  packages/components/fontawesome/package.json
  packages/components/lucide/package.json
  packages/components/lucide/src/icons/cloud-alert.tsx
  packages/components/lucide/src/icons/equal-approximately.tsx
  packages/components/lucide/src/icons/index.ts
  packages/components/lucide/src/icons/index.types.ts
  packages/components/lucide/src/icons/laptop-minimal-check.tsx
  packages/components/lucide/src/icons/toilet.tsx
  packages/components/resizable/package.json
  packages/next/package.json
  pnpm-lock.yaml
Labels: merge request

#3568 feat(editable): remove is prefix in props
  .changeset/stale-dolphins-jog.md
  packages/components/editable/src/editable.tsx
  stories/components/forms/editable.stories.tsx
Labels: merge request

#3566 feat(focus-lock): remove is prefix in props
  .changeset/brown-walls-dream.md
  packages/components/focus-lock/src/focus-lock.tsx
Labels: merge request

#3558 feat(indicator): remove is prefix in props
  .changeset/eighty-flies-check.md
  packages/components/indicator/src/indicator.tsx
Labels: merge request

#3529 fix: replace `ChevronIcon` in `Carousel` with `@yamada-ui/lucide`
  .changeset/hip-ladybugs-approve.md
  packages/components/carousel/package.json
  packages/components/carousel/src/carousel-control.tsx
  pnpm-lock.yaml
Labels: review wanted, merge request

#3560 Fix orientation data selector not working in firefox
  .changeset/plenty-points-appear.md
  packages/core/src/pseudos.ts
Labels: merge request

#3504 Remove deprecated `size` prop and cleanup from `CircleProgress`
  .changeset/gentle-olives-cover.md
  packages/components/progress/src/circle-progress.tsx
Labels: review wanted, merge request

#3505 Remove deprecated `size` prop and cleanup from `Image`
  .changeset/happy-jars-count.md
  packages/components/image/src/image.tsx
Labels: review wanted

#3588 Fixed prop reflection in list component
  .changeset/moody-cheetahs-rescue.md
  packages/components/list/src/list.tsx
Labels: merge request

#3589 Updated props and Popper integration
  .changeset/big-dodos-scream.md
  packages/components/tooltip/src/tooltip.tsx
Labels: merge request

#3527 `Tabs`: remove `is` prefix in props
  .changeset/tricky-gifts-hear.md
  packages/components/tabs/src/tab-panel.tsx
  packages/components/tabs/src/tab-panels.tsx
  packages/components/tabs/src/tab.tsx
  packages/components/tabs/src/tabs-context.tsx
  packages/components/tabs/src/tabs.tsx
  packages/components/tabs/tests/tabs.test.tsx
  packages/hooks/use-clickable/src/index.ts
  stories/components/disclosure/tabs.stories.tsx
Labels: review wanted

#3562 feat: add accessibility documentation for PinInput component
  docs/contents/components/forms/input/index.ja.mdx
  docs/contents/components/forms/input/index.mdx
  docs/contents/components/forms/pin-input/accessibility.ja.mdx
  docs/contents/components/forms/pin-input/accessibility.mdx
  stories/components/forms/pin-input.stories.tsx
Labels: review wanted

#3590 Updated `.nvmrc` version constraint
  .nvmrc
Labels: merge request

#3591 Added generic type to component exports
  plop/component/theme-multi/{{dashCase packageName}}.ts.hbs
  plop/component/theme/{{dashCase packageName}}.ts.hbs
Labels: merge request

#3548 feat: remove is prefix in variables
  .changeset/fair-sloths-film.md
  packages/components/radio/src/radio-group.tsx
  packages/components/radio/src/radio.tsx
  packages/components/radio/tests/radio.test.tsx
  stories/components/forms/radio.stories.tsx
Labels: review wanted

#3550 Added `EmptyState` component
  .changeset/honest-dingos-watch.md
  packages/components/empty-state/DOCS.json
  packages/components/empty-state/README.md
  packages/components/empty-state/package.json
  packages/components/empty-state/src/empty-state.tsx
  packages/components/empty-state/src/index.ts
  packages/components/empty-state/tests/empty-state.test.tsx
  packages/components/empty-state/tsconfig.json
  packages/core/src/generated-theme.types.ts
  packages/react/package.json
  packages/react/src/index.ts
  packages/theme/src/components/empty-state.ts
  packages/theme/src/components/index.ts
  pnpm-lock.yaml
  stories/components/other/empty-state.stories.tsx
  stories/components/other/for.stories.tsx
Labels: review wanted, merge request

#3551 Added `DataList` component
  .changeset/lucky-toes-watch.md
  .changeset/ten-tips-wonder.md
  packages/components/data-list/README.md
  packages/components/data-list/package.json
  packages/components/data-list/src/data-list.tsx
  packages/components/data-list/src/index.ts
  packages/components/data-list/tests/data-list.test.tsx
  packages/components/data-list/tsconfig.json
  packages/core/src/generated-theme.types.ts
  packages/core/src/pseudos.ts
  packages/react/package.json
  packages/react/src/index.ts
  packages/theme/src/components/data-list.ts
  packages/theme/src/components/index.ts
  packages/theme/src/styles/reset-style.ts
  pnpm-lock.yaml
  stories/components/data-display/data-list.stories.tsx
Labels: review wanted, merge request

#3592 Fixed `For` component theme
  packages/theme/src/components/for.ts
Labels: merge request

#3586 fix: fix `Icon` to `FontAwesomeIcon`
  docs/contents/components/media-and-icons/fontawesome/index.ja.mdx
  docs/contents/components/media-and-icons/fontawesome/index.mdx
  docs/contents/components/media-and-icons/icon/index.ja.mdx
  docs/contents/components/media-and-icons/icon/index.mdx
Labels: review wanted, merge request

#3598 feat(color-picker): remove is prefix from props
  .changeset/three-books-care.md
  packages/components/color-picker/src/color-swatch.tsx
  packages/components/color-picker/src/use-color-picker.ts
  packages/components/color-picker/src/use-color-selector.ts
  packages/components/color-picker/src/use-color-slider.ts
  packages/components/color-picker/src/use-saturation-slider.ts
Labels: merge request

#3615 Added default value comment for `max`
  .changeset/tricky-spiders-tease.md
  packages/components/password-input/src/password-input-strength-meter.tsx
Labels: merge request

#3628 Removed list style from header items
  docs/pages/examples/tasks/header.tsx
Labels: merge request

#3626 Added `DOCS.json`
  packages/components/for/DOCS.json
  packages/components/format/DOCS.json
  packages/components/password-input/DOCS.json
  packages/components/status/DOCS.json
Labels: merge request

#3634 Corrected border style handling in buttons
  .changeset/sour-chefs-arrive.md
  packages/components/button/src/button-group.tsx
Labels: merge request

#3582 Rename props: is* eliminates all is prefix in the button package
  .changeset/moody-trains-poke.md
  packages/components/button/src/button-group.tsx
  packages/components/button/src/button.tsx
  packages/components/button/tests/button.test.tsx
  stories/components/forms/button.stories.tsx
Labels: review wanted

#3646 Added `PasswordInput` documentation
  docs/contents/components/forms/password-input/accessibility.ja.mdx
  docs/contents/components/forms/password-input/accessibility.mdx
  docs/contents/components/forms/password-input/index.ja.mdx
  docs/contents/components/forms/password-input/index.mdx
  docs/contents/components/forms/password-input/props.ja.mdx
  docs/contents/components/forms/password-input/props.mdx
  docs/contents/components/forms/password-input/theming.ja.mdx
  docs/contents/components/forms/password-input/theming.mdx
  docs/i18n/content.en.json
  docs/i18n/content.ja.json
  stories/components/forms/password-input.stories.tsx
Labels: merge request

#3642 Added `For` and `EmptyState` documentation
  docs/components/mdx/editable-code-block.tsx
  docs/contents/components/other/empty-state/index.ja.mdx
  docs/contents/components/other/empty-state/index.mdx
  docs/contents/components/other/empty-state/props.ja.mdx
  docs/contents/components/other/empty-state/props.mdx
  docs/contents/components/other/empty-state/theming.ja.mdx
  docs/contents/components/other/empty-state/theming.mdx
  docs/contents/components/other/focus-lock/index.ja.mdx
  docs/contents/components/other/focus-lock/index.mdx
  docs/contents/components/other/for/index.ja.mdx
  docs/contents/components/other/for/index.mdx
  docs/contents/components/other/for/props.ja.mdx
  docs/contents/components/other/for/props.mdx
  docs/contents/components/other/for/theming.ja.mdx
  docs/contents/components/other/for/theming.mdx
  docs/contents/components/other/portal/index.ja.mdx
  docs/contents/components/other/portal/index.mdx
  docs/contents/components/other/visually-hidden/index.ja.mdx
  docs/contents/components/other/visually-hidden/index.mdx
  docs/i18n/content.en.json
  docs/i18n/content.ja.json
  stories/components/other/for.stories.tsx
Labels: merge request

#3668 Fix props doc generation script for windows
  docs/scripts/component/props.ts
Labels: merge request

#3643 Added `DataList` documentation
  docs/contents/components/data-display/area-chart/index.ja.mdx
  docs/contents/components/data-display/area-chart/index.mdx
  docs/contents/components/data-display/bar-chart/index.ja.mdx
  docs/contents/components/data-display/bar-chart/index.mdx
  docs/contents/components/data-display/calendar/index.ja.mdx
  docs/contents/components/data-display/calendar/index.mdx
  docs/contents/components/data-display/card/index.ja.mdx
  docs/contents/components/data-display/card/index.mdx
  docs/contents/components/data-display/carousel/index.ja.mdx
  docs/contents/components/data-display/carousel/index.mdx
  docs/contents/components/data-display/data-list/index.ja.mdx
  docs/contents/components/data-display/data-list/index.mdx
  docs/contents/components/data-display/data-list/props.ja.mdx
  docs/contents/components/data-display/data-list/props.mdx
  docs/contents/components/data-display/data-list/theming.ja.mdx
  docs/contents/components/data-display/data-list/theming.mdx
  docs/contents/components/data-display/dockable/index.ja.mdx
  docs/contents/components/data-display/dockable/index.mdx
  docs/contents/components/data-display/donut-chart/index.ja.mdx
  docs/contents/components/data-display/donut-chart/index.mdx
  docs/contents/components/data-display/infinite-scroll-area/index.ja.mdx
  docs/contents/components/data-display/infinite-scroll-area/index.mdx
  docs/contents/components/data-display/line-chart/index.ja.mdx
  docs/contents/components/data-display/line-chart/index.mdx
  docs/contents/components/data-display/native-table/index.ja.mdx
  docs/contents/components/data-display/native-table/index.mdx
  docs/contents/components/data-display/paging-table/index.ja.mdx
  docs/contents/components/data-display/paging-table/index.mdx
  docs/contents/components/data-display/pie-chart/index.ja.mdx
  docs/contents/components/data-display/pie-chart/index.mdx
  docs/contents/components/data-display/radar-chart/index.ja.mdx
  docs/contents/components/data-display/radar-chart/index.mdx
  docs/contents/components/data-display/radial-chart/index.ja.mdx
  docs/contents/components/data-display/radial-chart/index.mdx
  docs/contents/components/data-display/reorder/index.ja.mdx
  docs/contents/components/data-display/reorder/index.mdx
  docs/contents/components/data-display/resizable/index.ja.mdx
  docs/contents/components/data-display/resizable/index.mdx
  docs/contents/components/data-display/scroll-area/index.ja.mdx
  docs/contents/components/data-display/scroll-area/index.mdx
  docs/contents/components/data-display/stat/index.ja.mdx
  docs/contents/components/data-display/stat/index.mdx
  docs/contents/components/data-display/table/index.ja.mdx
  docs/contents/components/data-display/table/index.mdx
  docs/i18n/content.en.json
  docs/i18n/content.ja.json
  packages/components/data-list/src/data-list.tsx
Labels: merge request

#3635 Reordered story components
  stories/components/forms/checkbox.stories.tsx
  stories/components/forms/radio.stories.tsx
Labels: merge request

#3644 Added `Status` documentation
  docs/contents/components/feedback/circle-progress/index.ja.mdx
  docs/contents/components/feedback/circle-progress/index.mdx
  docs/contents/components/feedback/loading/index.ja.mdx
  docs/contents/components/feedback/loading/index.mdx
  docs/contents/components/feedback/progress/index.ja.mdx
  docs/contents/components/feedback/progress/index.mdx
  docs/contents/components/feedback/skeleton/index.ja.mdx
  docs/contents/components/feedback/skeleton/index.mdx
  docs/contents/components/feedback/status/index.ja.mdx
  docs/contents/components/feedback/status/index.mdx
  docs/contents/components/feedback/status/props.ja.mdx
  docs/contents/components/feedback/status/props.mdx
  docs/contents/components/feedback/status/theming.ja.mdx
  docs/contents/components/feedback/status/theming.mdx
  stories/components/data-display/status.stories.tsx
Labels: merge request

#3657 feat: rename is prefix in variables for portal
  .changeset/fluffy-trees-appear.md
  packages/components/portal/src/portal.tsx
  packages/components/portal/tests/portal.test.tsx
Labels: merge request

#3670 Updated component documentation descriptions
  .changeset/pretty-hotels-lay.md
  packages/components/format/src/format-byte.tsx
  packages/components/format/src/format-number.tsx
Labels: merge request

#3605 feat(calendar): remove is prefix from props
  .changeset/seven-onions-sit.md
  packages/components/calendar/src/calendar-utils.ts
  packages/components/calendar/src/date-picker.tsx
  packages/components/calendar/src/month-picker.tsx
  packages/components/calendar/src/month.tsx
  packages/components/calendar/src/multi-date-picker.tsx
  packages/components/calendar/src/use-calendar-picker.ts
  packages/components/calendar/src/use-calendar.ts
  packages/components/calendar/src/use-month-list.tsx
  packages/components/calendar/src/use-month.tsx
  packages/components/calendar/src/use-multi-date-picker.ts
  packages/components/calendar/src/use-range-date-picker.ts
  packages/components/calendar/src/use-year-list.tsx
  packages/components/calendar/src/year-picker.tsx
  stories/components/data-display/calendar.stories.tsx
Labels: review wanted

#3647 Replace `Fieldset` with `FormControl` in forms
  docs/contents/components/forms/input/index.ja.mdx
  docs/contents/components/forms/input/index.mdx
Labels: merge request

#3673 feat(tag): remove is prefix from props
  .changeset/thick-turkeys-drop.md
  packages/components/tag/src/tag.tsx
Labels: merge request

#3669 Added `fit-content` width to `DataList`
  .changeset/tricky-ligers-run.md
  packages/theme/src/components/data-list.ts
Labels: merge request

#3660 Added `MenuSeparator` component replacing `MenuDivider`
  .changeset/eleven-fishes-give.md
  packages/components/menu/src/index.ts
  packages/components/menu/src/menu-divider.tsx
  packages/components/menu/src/menu-separator.tsx
  packages/theme/src/components/color-picker.ts
  packages/theme/src/components/menu.ts
  stories/components/overlay/context-menu.stories.tsx
  stories/components/overlay/menu.stories.tsx
Labels: merge request

#3671 Updated default config documentation
  docs/contents/styled-system/configure/default-config.ja.mdx
  docs/contents/styled-system/configure/default-config.mdx
Labels: merge request

#3677 Change `MenuDivider` to `MenuSeparator`
  docs/contents/components/forms/color-picker/theming.ja.mdx
  docs/contents/components/forms/color-picker/theming.mdx
  docs/contents/components/overlay/context-menu/index.ja.mdx
  docs/contents/components/overlay/context-menu/index.mdx
  docs/contents/components/overlay/menu/index.ja.mdx
  docs/contents/components/overlay/menu/index.mdx
  docs/contents/components/overlay/menu/props.ja.mdx
  docs/contents/components/overlay/menu/props.mdx
  docs/contents/components/overlay/menu/theming.ja.mdx
  docs/contents/components/overlay/menu/theming.mdx
  docs/pages/examples/music/header.tsx
  docs/pages/examples/tasks/data-table.tsx
  docs/pages/examples/tasks/header.tsx
  packages/components/tag/src/tag.tsx
Labels: merge request
