Repository yamada-ui/yamada-ui, pull requests merged in 2024-03, with the labels that each got.

#966 Enhancement/calendar test coverage
  packages/components/calendar/tests/calendar.test.tsx
Labels: test

#937 test(modal): enhance test coverage
  packages/components/modal/tests/dialog.test.tsx
  packages/components/modal/tests/drawer.test.tsx
Labels: test

#924 feat: close the Drawer by dragging
  .changeset/early-mirrors-fry.md
  .changeset/mighty-pens-draw.md
  packages/components/modal/src/drawer.tsx
  packages/hooks/use-pan-event/src/index.ts
  stories/components/overlay/drawer.stories.tsx
Labels: help wanted

#1004 Stop uploading test coverages to Codecov temporarily
  .github/workflows/quality.yml
Labels: test

#1007 [Storybook] Upgrade to v8
  .storybook/main.ts
  package.json
  pnpm-lock.yaml
  stories/documents/theme/borders.mdx
  stories/documents/theme/breakpoints.mdx
  stories/documents/theme/colors.mdx
  stories/documents/theme/gradients.mdx
  stories/documents/theme/radii.mdx
  stories/documents/theme/shadows.mdx
  stories/documents/theme/sizes.mdx
  stories/documents/theme/spaces.mdx
  stories/documents/theme/transitions.mdx
  stories/documents/theme/typography.mdx
  stories/documents/theme/z-index.mdx
  stories/documents/welcome.mdx
Labels: documentation
