Repository yamada-ui/yamada-ui, pull requests merged in 2024-12, with the labels that each got.

#3661 Restructured pagination item styles
  .changeset/proud-pans-decide.md
  packages/theme/src/components/pagination.ts
Labels: review wanted, merge request

#3678 feat(checkbox): remove is prefix from props
  .changeset/fuzzy-paws-cross.md
  packages/components/checkbox/src/checkbox.tsx
  packages/components/checkbox/src/use-checkbox-group.ts
  packages/components/checkbox/src/use-checkbox.ts
Labels: merge request

#3679 feat(number-input): remove is prefix from props
  .changeset/purple-carrots-pump.md
  packages/components/number-input/src/number-input.tsx
Labels: merge request

#3681 `popover`: remove is prefix from props
  .changeset/stupid-rivers-behave.md
  packages/components/popover/src/popover-content.tsx
  packages/components/popover/src/popover.tsx
  packages/components/popover/tests/popover.test.tsx
  stories/components/overlay/popover.stories.tsx
Labels: merge request

#3680 feat(native-table): remove is prefix from props
  .changeset/brave-peaches-itch.md
  packages/components/native-table/src/td.tsx
  packages/components/native-table/src/th.tsx
Labels: merge request

#3606 feat(input): remove is prefix from props
  .changeset/lemon-actors-cough.md
  packages/components/input/src/input-element.tsx
Labels: review wanted

#3684 `carousel`: remove is prefix from props and variables
  .changeset/polite-moose-dress.md
  packages/components/carousel/src/carousel-control.tsx
  packages/components/carousel/src/carousel-indicators.tsx
  packages/components/carousel/src/use-carousel.ts
  packages/components/carousel/tests/carousel.test.tsx
  stories/components/data-display/carousel.stories.tsx
Labels: review wanted

#3694 Update contributor and maintainer lists
  docs/constant/contributors.ts
  docs/constant/maintainers.ts
  docs/constant/members.ts
  docs/i18n/content.en.json
  docs/i18n/content.ja.json
Labels: merge request

#3690 feat: rename is prefix in variables for resizable
  .changeset/tricky-mails-agree.md
  packages/components/resizable/src/use-resizable.ts
  stories/components/data-display/resizable.stories.tsx
Labels: merge request

#3799 feat(radio): add `@deprecated` to the `isNative` prop
  .changeset/rude-monkeys-sin.md
  packages/components/radio/src/use-radio-group.ts
Labels: merge request

#3800 feat(progress): remove is prefix from props
  .changeset/tidy-teachers-shout.md
  packages/components/progress/src/circle-progress.tsx
  packages/components/progress/src/progress.tsx
Labels: merge request

#3803 Moved animate declaration for clarity
  .changeset/forty-starfishes-protect.md
  packages/components/transitions/src/scale-fade.tsx
Labels: merge request

#3806 feat(use-animation): remove is prefix from props
  .changeset/tame-hornets-argue.md
  packages/hooks/use-animation/src/index.ts
Labels: merge request

#3807 feat(use-disclosure): remove is prefix from props
  .changeset/purple-pigs-stare.md
  packages/hooks/use-disclosure/src/index.ts
Labels: merge request

#3801 docs(slider): update "Control externally" example to use <ButtonGroup />
  docs/contents/components/forms/slider/index.ja.mdx
  docs/contents/components/forms/slider/index.mdx
  stories/components/forms/slider.stories.tsx
Labels: merge request

#3802 Added `separatorProps` to components
  .changeset/gentle-paws-care.md
  docs/components/navigation/breadcrumb.tsx
  packages/components/breadcrumb/src/breadcrumb.tsx
  stories/components/navigation/breadcrumb.stories.tsx
Labels: review wanted, merge request

#3830 Enhance Test Coverage for `@yamada-ui/password-input`
  packages/components/password-input/tests/password-input.test.tsx
Labels: merge request

#3689 test: added tests for menu separator component
  packages/components/menu/tests/menu.test.tsx
Labels: review wanted, merge request

#3832 Refactor `convertColor` to replace lookbehind in regular expression.
  .changeset/itchy-dryers-burn.md
  packages/utils/src/color.ts
Labels: merge request

#3296 Enhance Test Coverage for @yamada-ui/popover
  packages/components/popover/tests/popover.test.tsx
Labels: review wanted, merge request

#3833 test: increased test coverage for EmptyState component
  packages/components/empty-state/tests/empty-state.test.tsx
Labels: merge request

#3834 Use <For /> in Heading documentation
  docs/contents/components/typography/heading/index.ja.mdx
  docs/contents/components/typography/heading/index.mdx
Labels: merge request

#3836 Replaced `For` in `CloseButton` documentation
  docs/contents/components/other/close-button/index.ja.mdx
  docs/contents/components/other/close-button/index.mdx
Labels: merge request

#3846 Enhanced Test Coverage for `@yamada-ui/radio`
  packages/components/radio/tests/radio-card.test.tsx
Labels: merge request

#3850 Use <For/> in `FileInput` documentation
  docs/contents/components/forms/file-input/index.ja.mdx
  docs/contents/components/forms/file-input/index.mdx
Labels: merge request

#3862 Use <For/> in `List` documentation
  docs/contents/components/data-display/list/index.ja.mdx
  docs/contents/components/data-display/list/index.mdx
Labels: merge request

#3840 Use <For/> in `Badge` documentation
  docs/contents/components/data-display/badge/index.ja.mdx
  docs/contents/components/data-display/badge/index.mdx
Labels: merge request

#3848 Use <For/> in `Separator` documentation
  docs/contents/components/layouts/separator/index.ja.mdx
  docs/contents/components/layouts/separator/index.mdx
Labels: merge request

#3849 Use <For/> in `SimpleGrid` documentation
  docs/contents/components/layouts/simple-grid/index.ja.mdx
  docs/contents/components/layouts/simple-grid/index.mdx
Labels: merge request

#3839 Use <For /> in `Flex` documentation
  docs/contents/components/layouts/flex/index.ja.mdx
  docs/contents/components/layouts/flex/index.mdx
Labels: merge request

#3838 Use <For /> in `Divider` documentation
  docs/contents/components/layouts/divider/index.ja.mdx
  docs/contents/components/layouts/divider/index.mdx
Labels: merge request

#3973 Use <For/> in `FileButton` documentation
  docs/contents/components/forms/file-button/index.ja.mdx
  docs/contents/components/forms/file-button/index.mdx
Labels: merge request

#3874 Use <For/> in `Blockquote` documentation
  docs/contents/components/typography/blockquote/index.ja.mdx
  docs/contents/components/typography/blockquote/index.mdx
Labels: merge request

#3979 Use <For/> in `AlphaSlider` documentation
  docs/contents/components/forms/alpha-slider/index.ja.mdx
  docs/contents/components/forms/alpha-slider/index.mdx
Labels: merge request

#3984 Updated useDarkMode hook implementation
  .storybook/preview.tsx
  pnpm-lock.yaml
Labels: merge request

#3978 Use <For/> in `HueSlider` documentation
  docs/contents/components/forms/hue-slider/index.ja.mdx
  docs/contents/components/forms/hue-slider/index.mdx
Labels: merge request

#3976 Use <For/> in `Slider` documentation
  docs/contents/components/forms/slider/index.ja.mdx
  docs/contents/components/forms/slider/index.mdx
Labels: merge request

#3949 Use <For/> in`InfiniteScrollArea` documentation
  docs/contents/components/data-display/infinite-scroll-area/index.ja.mdx
  docs/contents/components/data-display/infinite-scroll-area/index.mdx
Labels: merge request

#4025 Use <For /> in `useInfiniteScroll` documentation
  docs/contents/hooks/use-infinite-scroll.ja.mdx
  docs/contents/hooks/use-infinite-scroll.mdx
Labels: merge request

#3977 Use <For/> in `RangeSlider` documentation
  docs/contents/components/forms/range-slider/index.ja.mdx
  docs/contents/components/forms/range-slider/index.mdx
Labels: merge request

#3538 `segmented-control`: remove is prefix in props
  .changeset/kind-dots-repair.md
  packages/components/segmented-control/src/segmented-control.tsx
  packages/components/segmented-control/tests/segmented-control.test.tsx
  packages/components/skeleton/src/skeleton.tsx
  packages/utils/src/react.tsx
Labels: review wanted

#3837 fix: adjust hover background colors for disabled/focus item
  .changeset/rare-sloths-exist.md
  packages/theme/src/components/menu.ts
  packages/theme/src/components/select.ts
Labels: review wanted

#3672 feat: remove prefix in props from FormControl and Fieldset components
  .changeset/thirty-hairs-give.md
  packages/components/form-control/src/fieldset.tsx
  packages/components/form-control/src/form-control.tsx
  packages/components/form-control/tests/fieldset.test.tsx
  packages/components/form-control/tests/form-control.test.tsx
  stories/components/forms/form-control.stories.tsx
Labels: review wanted, merge request

#3798 feat(slider): remove is prefix from props
  .changeset/few-owls-yell.md
  packages/components/slider/src/range-slider.tsx
  packages/components/slider/src/slider.tsx
Labels: review wanted

#3686 feat: rename is prefix in variables for select
  .changeset/perfect-ads-burn.md
  .changeset/perfect-rabbits-yawn.md
  .changeset/pink-icons-talk.md
  packages/components/autocomplete/src/autocomplete-option.tsx
  packages/components/autocomplete/src/use-autocomplete-option.ts
  packages/components/autocomplete/tests/autocomplete.test.tsx
  packages/components/popover/src/popover.tsx
  packages/components/select/src/multi-select.tsx
  packages/components/select/src/option.tsx
  packages/components/select/src/select-icon.tsx
  packages/components/select/src/select.tsx
  packages/components/select/src/use-select-list.ts
  packages/components/select/src/use-select-option-group.ts
  packages/components/select/src/use-select-option.ts
  packages/components/select/src/use-select.tsx
  packages/hooks/use-disclosure/src/index.ts
Labels: review wanted

#3693 `menu`: remove is from props
  .changeset/ten-actors-punch.md
  packages/components/menu/src/menu-button.tsx
  packages/components/menu/src/menu-context.ts
  packages/components/menu/src/menu-item.tsx
  packages/components/menu/src/menu-option-group.tsx
  packages/components/menu/src/menu.tsx
Labels: review wanted

#4046 Updated node version and package configs
  .github/composite-actions/install/action.yml
  .npmrc
  .nvmrc
  package.json
  pnpm-lock.yaml
Labels: review wanted, merge request

#4074 Updated type definition
  .changeset/fair-poets-divide.md
  .changeset/metal-points-add.md
  packages/components/breadcrumb/src/breadcrumb.tsx
  packages/components/button/src/button-group.tsx
  packages/components/card/src/card.tsx
  packages/components/carousel/src/carousel-slide.tsx
  packages/components/color-picker/src/color-selector-swatches.tsx
  packages/components/layouts/src/grid.tsx
  packages/components/layouts/src/stack.tsx
  packages/components/native-table/src/native-table.tsx
  packages/components/table/src/paging-table.tsx
  packages/components/table/src/table.tsx
  packages/components/toggle/src/toggle-group.tsx
  packages/core/src/css/use-var.ts
Labels: merge request

#4049 Use <For /> in Avatar documentation
  docs/contents/components/media-and-icons/avatar/index.ja.mdx
  docs/contents/components/media-and-icons/avatar/index.mdx
Labels: merge request

#4097 Use <For /> in EmptyState documentation
  docs/contents/components/other/empty-state/index.ja.mdx
  docs/contents/components/other/empty-state/index.mdx
Labels: merge request

#4096 Use <For /> in Text documentation
  docs/contents/components/typography/text/index.ja.mdx
  docs/contents/components/typography/text/index.mdx
Labels: merge request

#4075 Use `<For />` in `Stat` docs
  docs/contents/components/data-display/stat/index.ja.mdx
  docs/contents/components/data-display/stat/index.mdx
Labels: merge request

#4029 Use <For/> in `Stack` documentation
  docs/contents/components/layouts/stack/index.ja.mdx
  docs/contents/components/layouts/stack/index.mdx
Labels: review wanted, merge request

#4100 Use <For /> in `Code` documentation
  docs/contents/components/typography/code/index.ja.mdx
  docs/contents/components/typography/code/index.mdx
Labels: merge request

#4148 Use <For/> `Grid` documentation
  docs/contents/components/layouts/grid/index.ja.mdx
  docs/contents/components/layouts/grid/index.mdx
Labels: merge request

#4147 Use <For/> `Wrap` documentation
  docs/contents/components/layouts/wrap/index.ja.mdx
  docs/contents/components/layouts/wrap/index.mdx
Labels: merge request

#4103 Use <For /> in Progress documentation
  docs/contents/components/feedback/progress/index.ja.mdx
  docs/contents/components/feedback/progress/index.mdx
Labels: merge request

#4078 Use <For /> in Icon documentation
  docs/contents/components/media-and-icons/icon/index.ja.mdx
  docs/contents/components/media-and-icons/icon/index.mdx
Labels: review wanted, merge request

#4045 Use <For/> in `pagination` documentation
  docs/contents/components/navigation/pagination/index.ja.mdx
  docs/contents/components/navigation/pagination/index.mdx
Labels: review wanted, merge request

#3981 Use <For/> in `Rating` documentation
  docs/contents/components/forms/rating/index.ja.mdx
  docs/contents/components/forms/rating/index.mdx
Labels: merge request

#4146 Use `For` in `dialog` documentation
  docs/contents/components/overlay/dialog/index.ja.mdx
  docs/contents/components/overlay/dialog/index.mdx
Labels: merge request

#4150 Use <For/> in `textarea` documentation
  docs/contents/components/forms/textarea/index.ja.mdx
  docs/contents/components/forms/textarea/index.mdx
Labels: merge request

#4076 Use <For /> in Tooltip docs
  docs/contents/components/overlay/tooltip/index.ja.mdx
  docs/contents/components/overlay/tooltip/index.mdx
Labels: merge request

#4079 Use <For /> in Card documentation
  docs/contents/components/data-display/card/index.ja.mdx
  docs/contents/components/data-display/card/index.mdx
Labels: merge request

#4102 Use <For /> in Status documentation
  docs/contents/components/feedback/status/index.ja.mdx
  docs/contents/components/feedback/status/index.mdx
Labels: merge request

#4182 fix: replaced icon in `Autocomplete`
  packages/react/src/components/autocomplete/autocomplete-create.tsx
  packages/react/src/components/autocomplete/autocomplete-empty.tsx
  packages/react/src/components/autocomplete/autocomplete-icon.tsx
  packages/react/src/components/autocomplete/autocomplete-option.tsx
Labels: merge request

#4048 test: increased coverage for @yamada-ui/checkbox
  packages/components/checkbox/tests/checkbox-card.test.tsx
  packages/components/checkbox/tests/use-checkbox.test.tsx
Labels: merge request

#4189 Replaced icon in `Avatar`
  packages/react/src/components/avatar/avatar-badge.tsx
  packages/react/src/components/avatar/avatar-group.tsx
  packages/react/src/components/avatar/avatar-icon.tsx
  packages/react/src/components/avatar/avatar-name.tsx
  packages/react/src/components/avatar/avatar.tsx
Labels: merge request

#4190 fix: replaced icon in `Breadcrumb`
  packages/react/src/components/breadcrumb/breadcrumb.tsx
Labels: merge request

#4101 Use <For /> in Highlight documentation
  docs/contents/components/typography/highlight/index.ja.mdx
  docs/contents/components/typography/highlight/index.mdx
Labels: merge request

#4194 `avatar`: remove deprecated props
  packages/react/src/components/avatar/avatar.stories.tsx
  packages/react/src/components/avatar/avatar.tsx
Labels: merge request

#4198 `bleed`: rename internal variables
  packages/react/src/components/bleed/bleed.tsx
Labels: merge request

#4200 Supported React 19.
  .changeset/great-turkeys-sparkle.md
  .changeset/silly-moose-fetch.md
  .changeset/young-tigers-warn.md
  packages/components/layouts/src/stack.tsx
  packages/components/markdown/src/markdown.tsx
  packages/components/motion/src/motion.types.ts
  packages/components/popover/src/popover-anchor.tsx
  packages/components/popover/src/popover-trigger.tsx
  packages/components/tooltip/src/tooltip.tsx
  packages/core/src/components/component.types.ts
  packages/utils/src/react.tsx
Labels: merge request

#4191 fix: replaced icon in `Carousel`
  packages/react/src/components/carousel/carousel-control.tsx
Labels: review wanted, merge request

#4187 fix: replace reorder icon
  packages/react/src/components/reorder/reorder-trigger.tsx
Labels: merge request

#4205 `breadcrumb`: remove deprecated props
  packages/react/src/components/breadcrumb/breadcrumb.tsx
Labels: merge request

#4203 refactor: move styles to theme for card
  packages/react/src/components/card/card.tsx
  packages/react/src/theme/components/card.ts
Labels: merge request

#4204 refactor: remove css ui object for data list
  packages/react/src/components/data-list/data-list.tsx
Labels: merge request

#4209 `charts`: remove deprecated props and rename variables
  packages/react/src/components/charts/area-chart.stories.tsx
  packages/react/src/components/charts/chart-utils.ts
  packages/react/src/components/charts/donut-chart.tsx
  packages/react/src/components/charts/pie-chart.test.tsx
  packages/react/src/components/charts/pie-chart.tsx
  packages/react/src/components/charts/use-pie-chart.ts
Labels: merge request

#4207 refactor: move styles to theme for dropzone
  packages/react/src/components/dropzone/dropzone.tsx
  packages/react/src/theme/components/dropzone.ts
Labels: merge request

#4196 refactor: move styles to theme for avatar
  packages/react/src/components/avatar/avatar-badge.tsx
  packages/react/src/components/avatar/avatar-group.tsx
  packages/react/src/components/avatar/avatar-name.tsx
  packages/react/src/components/avatar/avatar.tsx
  packages/react/src/theme/components/avatar.ts
Labels: merge request

#3842 Use <For/> in `ColorPicker` documentation
  docs/contents/components/forms/color-picker/index.ja.mdx
  docs/contents/components/forms/color-picker/index.mdx
Labels: merge request

#4213 refactor: move styles to theme for editable
  packages/react/src/components/editable/editable.tsx
  packages/react/src/theme/components/editable.ts
Labels: merge request

#4208 `carousel`: remove deprecated props
  packages/react/src/components/carousel/carousel-indicators.tsx
  packages/react/src/components/carousel/use-carousel.ts
Labels: review wanted, merge request

#4219 `close-button`: rename isRounded to fullRounded
  .changeset/plenty-kangaroos-cough.md
  packages/components/close-button/src/close-button.tsx
Labels: merge request

#4212 refactor: move styles to theme for calendar
  packages/react/src/components/calendar/calendar.tsx
  packages/react/src/theme/components/calendar.ts
Labels: merge request

#4077 Use `<For />` in `Float` documentation
  docs/contents/components/layouts/float/index.ja.mdx
  docs/contents/components/layouts/float/index.mdx
Labels: merge request

#4183 refactor: move styles to theme for input
  packages/react/src/components/input/input-addon.tsx
  packages/react/src/components/input/input-element.tsx
  packages/react/src/components/input/input-group.tsx
  packages/react/src/components/input/input.tsx
  packages/react/src/theme/components/input.ts
Labels: review wanted

#4224 `editable`: remove deprecated props
  packages/react/src/components/editable/editable.stories.tsx
  packages/react/src/components/editable/editable.test.tsx
  packages/react/src/components/editable/editable.tsx
Labels: merge request

#4225 `file-button`: remove reprecated props
  packages/react/src/components/file-button/file-button.stories.tsx
  packages/react/src/components/file-button/file-button.test.tsx
  packages/react/src/components/file-button/file-button.tsx
Labels: merge request

#4226 `file-input`: remove deprecated props
  packages/react/src/components/file-input/file-input.stories.tsx
  packages/react/src/components/file-input/file-input.test.tsx
  packages/react/src/components/file-input/file-input.tsx
Labels: merge request

#4228 `input`: remove deprecated props
  packages/react/src/components/input/input-element.tsx
  packages/react/src/components/input/input-group.tsx
  packages/react/src/components/input/input.stories.tsx
  packages/react/src/components/input/input.test.tsx
Labels: merge request

#4215 refactor: move styles to theme for form infinite-scroll-area
  packages/react/src/components/infinite-scroll-area/infinite-scroll-area.tsx
  packages/react/src/theme/components/infinite-scroll-area.ts
Labels: merge request

#4227 `focus-lock`: remove deprecated props
  packages/react/src/components/focus-lock/focus-lock.tsx
Labels: merge request

#4229 fix: replaced `EyeDropperIcon` in `ColorPicker` and `ColorSelector`.
  packages/react/src/components/color-picker/color-picker.tsx
  packages/react/src/components/color-picker/color-selector-eye-dropper.tsx
Labels: merge request

#4232 refactor: move styles to theme for form number-input
  packages/react/src/components/number-input/number-input.tsx
  packages/react/src/theme/components/number-input.ts
Labels: merge request

#4199 Remove all svg icon.
  packages/react/src/components/accordion/accordion-label.tsx
  packages/react/src/components/autocomplete/autocomplete-icon.tsx
  packages/react/src/components/autocomplete/autocomplete-option.tsx
  packages/react/src/components/calendar/calendar-header.tsx
  packages/react/src/components/calendar/date-picker.tsx
  packages/react/src/components/close-button/close-button.tsx
  packages/react/src/components/icon/icon.test.tsx
  packages/react/src/components/icon/icon.tsx
  packages/react/src/components/icon/index.ts
  packages/react/src/components/menu/menu-button.tsx
  packages/react/src/components/menu/menu-item.tsx
  packages/react/src/components/native-select/native-select.tsx
  packages/react/src/components/number-input/number-input.tsx
  packages/react/src/components/select/select-icon.tsx
  packages/react/src/components/table/table-sort-button.tsx
Labels: merge request

#4223 `dropzone`: remove deprecated props
  packages/react/src/components/dropzone/dropzone.stories.tsx
  packages/react/src/components/dropzone/dropzone.test.tsx
  packages/react/src/components/dropzone/dropzone.tsx
Labels: review wanted, merge request

#4216 `checkbox`: remove deprecated props
  packages/react/src/components/checkbox/checkbox-card.stories.tsx
  packages/react/src/components/checkbox/checkbox-card.tsx
  packages/react/src/components/checkbox/checkbox.stories.tsx
  packages/react/src/components/checkbox/checkbox.test.tsx
  packages/react/src/components/checkbox/checkbox.tsx
  packages/react/src/components/checkbox/use-checkbox-group.ts
  packages/react/src/components/checkbox/use-checkbox.ts
Labels: merge request

#4241 refactor: move styles to theme for form segmented-control
  packages/react/src/components/segmented-control/segmented-control.tsx
  packages/react/src/theme/components/segmented-control.ts
Labels: merge request

#4237 refactor: move styles to theme for form table
  packages/react/src/components/table/paging-table.tsx
  packages/react/src/components/table/table-sort-button.tsx
  packages/react/src/components/table/table.tsx
  packages/react/src/theme/components/table.ts
Labels: merge request

#4239 refactor: move styles to theme for form stat
  packages/react/src/components/stat/stat.tsx
  packages/react/src/theme/components/stat.ts
Labels: merge request

#4240 refactor: move styles to theme for form slider
  packages/react/src/components/slider/range-slider.tsx
  packages/react/src/components/slider/slider.tsx
  packages/react/src/theme/components/slider.ts
Labels: merge request

#4244 refactor: move styles to theme for form resizable
  packages/react/src/components/resizable/resizable-item.tsx
  packages/react/src/components/resizable/resizable-trigger.tsx
  packages/react/src/components/resizable/resizable.tsx
  packages/react/src/theme/components/resizable.ts
Labels: merge request

#4247 refactor: move styles to theme for form progress
  packages/react/src/components/progress/progress.tsx
  packages/react/src/theme/components/progress.ts
Labels: merge request

#4246 refactor: move styles to theme for form rating
  packages/react/src/components/rating/rating-item.tsx
  packages/react/src/components/rating/rating.tsx
  packages/react/src/theme/components/rating.ts
Labels: merge request

#4269 `stack`: rename variables
  packages/react/src/components/stack/z-stack.tsx
Labels: merge request

#4257 `pin-input`: remove deprecated props
  packages/react/src/components/pin-input/pin-input.stories.tsx
  packages/react/src/components/pin-input/pin-input.tsx
Labels: merge request

#4238 refactor: move styles to theme for form switch
  packages/react/src/components/switch/switch.tsx
  packages/react/src/theme/components/switch.ts
Labels: merge request

#4258 `password-input`: remove deprecated props
  packages/react/src/components/password-input/password-input.stories.tsx
  packages/react/src/components/password-input/use-password-input.tsx
Labels: merge request
