Repository yamada-ui/yamada-ui, pull requests merged in 2024-07, with the labels that each got.

#2140 Enhance the accessibility of InfiniteScrollArea (@yamada-ui/infinite-scroll-area) component
  .changeset/dirty-geckos-rescue.md
  packages/components/infinite-scroll-area/src/infinite-scroll-area.tsx
  packages/components/infinite-scroll-area/tests/infinite-scroll-area.test.tsx
  packages/hooks/use-infinite-scroll/src/index.ts
Labels: a11y, review wanted

#2218 Expanded unit validation regex in isUnit
  .changeset/weak-dots-invite.md
  packages/utils/src/assertion.ts
Labels: merge request

#2205 Fixed `getObject` path parsing issue
  .changeset/soft-cooks-brake.md
  packages/utils/src/object.ts
Labels: merge request

#2227 refactor: improve Skeleton test code
  packages/components/skeleton/tests/skeleton.test.tsx
Labels: merge request

#2224 refactor(component-test): fixed a typo in file-name
  packages/core/tests/component.test.tsx
Labels: merge request

#2207 Fixed item update logic in useAutocomplete
  .changeset/forty-pants-tap.md
  packages/components/autocomplete/src/use-autocomplete.tsx
  packages/components/autocomplete/tests/autocomplete.test.tsx
Labels: merge request

#2223 added chart axis label
  .changeset/slimy-beans-smile.md
  packages/components/charts/src/area-chart.tsx
  packages/components/charts/src/bar-chart.tsx
  packages/components/charts/src/chart.types.ts
  packages/components/charts/src/line-chart.tsx
  packages/components/charts/src/rechart-properties.ts
  packages/components/charts/src/use-area-chart.ts
  packages/components/charts/src/use-bar-chart.ts
  packages/components/charts/src/use-chart-axis.ts
  packages/components/charts/src/use-line-chart.ts
  packages/components/charts/tests/area-chart.test.tsx
  packages/components/charts/tests/bar-chart.test.tsx
  packages/components/charts/tests/donut-chart.test.tsx
  packages/components/charts/tests/line-chart.test.tsx
  packages/components/charts/tests/pie-chart.test.tsx
  packages/components/charts/tests/radar-chart.test.tsx
  packages/theme/src/components/line-chart.ts
  stories/components/feedback/area-chart.stories.tsx
  stories/components/feedback/bar-chart.stories.tsx
  stories/components/feedback/line-chart.stories.tsx
Labels: merge request

#2147 add accessibility section for `Avatar`
  docs/contents/components/media-and-icons/avatar/accessibility.ja.mdx
  docs/contents/components/media-and-icons/avatar/accessibility.mdx
Labels: a11y

#2237 Enhanced iframe theming support
  docs/components/mdx/editable-code-block.tsx
Labels: merge request

#2234 Make `Progress` component headless
  .changeset/twelve-pens-arrive.md
  packages/components/indicator/tests/indicator.test.tsx
  packages/components/progress/src/progress.tsx
  packages/theme/src/components/progress.ts
Labels: merge request

#2233 Updated value propagation in pickers
  .changeset/giant-pears-lie.md
  packages/components/calendar/src/use-date-picker.ts
  packages/components/calendar/src/use-month-picker.ts
  packages/components/calendar/src/use-multi-date-picker.ts
  packages/components/calendar/src/use-range-date-picker.ts
  packages/components/calendar/src/use-year-picker.ts
Labels: merge request

#2239 Updated accessibility documentation text
  docs/contents/components/forms/radio/accessibility.ja.mdx
  docs/contents/components/forms/radio/accessibility.mdx
Labels: merge request

#2240 AccordionLabel does not match the theme key.
  .changeset/unlucky-cougars-lie.md
  docs/contents/components/disclosure/accordion/accessibility.ja.mdx
  docs/contents/components/disclosure/accordion/accessibility.mdx
  docs/contents/components/disclosure/accordion/index.ja.mdx
  docs/contents/components/disclosure/accordion/index.mdx
  docs/contents/components/disclosure/accordion/props.ja.mdx
  docs/contents/components/disclosure/accordion/props.mdx
  docs/i18n/content.en.json
  docs/i18n/content.ja.json
  packages/components/accordion/DOCS.json
  packages/components/accordion/src/accordion-button.tsx
  packages/components/accordion/src/accordion-item.tsx
  packages/components/accordion/src/index.ts
  packages/components/accordion/tests/accordion.test.tsx
  stories/components/disclosure/accordion.stories.tsx
Labels: merge request

#2195 Created `Checkbox` a11y docs
  docs/contents/components/forms/checkbox/accessibility.ja.mdx
  docs/contents/components/forms/checkbox/accessibility.mdx
Labels: documentation, a11y, review wanted, merge request

#2220 Fixed use-select & use-autocomplete logic
  .changeset/hip-peas-fold.md
  packages/components/autocomplete/src/use-autocomplete.tsx
  packages/components/select/src/use-select.ts
Labels: merge request

#2171 Enhance Test Coverage for `@yamada-ui/autocomplete`
  packages/components/autocomplete/tests/autocomplete.test.tsx
  packages/components/autocomplete/tests/multi-autocomplete.test.tsx
Labels: help wanted, merge request

#2242 Enhance `Skelton` component accessibility
  .changeset/neat-queens-drive.md
  packages/components/skeleton/src/skeleton.tsx
Labels: merge request

#2204 Enhance the accessibility of MonthPicker `@yamada-ui/calendar` component
  .changeset/sharp-badgers-reply.md
  packages/components/calendar/src/month-picker.tsx
  packages/components/calendar/src/use-calendar-header.tsx
  packages/components/calendar/src/use-calendar-picker.ts
  packages/components/calendar/src/use-month-list.tsx
  packages/components/calendar/src/use-month-picker.ts
Labels: merge request

#2244 Updated dependencies
  .changeset/short-humans-rule.md
  .changeset/smooth-camels-stare.md
  package.json
  packages/components/calendar/package.json
  packages/components/lucide/package.json
  packages/components/lucide/src/icons/home.tsx
  packages/components/lucide/src/icons/house-plug.tsx
  packages/components/lucide/src/icons/house-plus.tsx
  packages/components/lucide/src/icons/house.tsx
  packages/components/lucide/src/icons/index.ts
  packages/components/lucide/src/icons/index.types.ts.tsx
  packages/components/lucide/src/icons/logs.tsx
  packages/components/lucide/src/icons/printer-check.tsx
  packages/components/lucide/src/icons/save-off.tsx
  packages/components/lucide/src/icons/signature.tsx
  pnpm-lock.yaml
Labels: merge request

#2250 Moved `EnvironmentProvider` and `useEnvironment` to `@yamada-ui/core`.
  .changeset/few-goats-kick.md
  .changeset/friendly-flies-tan.md
  .changeset/light-dancers-try.md
  docs/components/mdx/editable-code-block.tsx
  packages/core/src/providers/color-mode-provider.tsx
  packages/core/src/providers/color-mode-utils.ts
  packages/core/src/providers/environment-provider.tsx
  packages/core/src/providers/index.ts
  packages/core/src/providers/provider-utils.ts
  packages/core/src/providers/theme-provider.tsx
  packages/hooks/use-media-query/package.json
  packages/hooks/use-media-query/src/index.ts
  packages/hooks/use-media-query/tests/index.test.tsx
  packages/providers/src/index.ts
  packages/providers/src/ui-provider.tsx
  packages/react/src/index.ts
  pnpm-lock.yaml
Labels: merge request

#2252 Enhance the accessibility of `RangeDatePicker` (`@yamada-ui/calendar`) component
  .changeset/slimy-kangaroos-give.md
  packages/components/calendar/src/range-date-picker.tsx
  packages/components/calendar/src/use-month.tsx
  packages/components/calendar/src/use-range-date-picker.ts
Labels: merge request

#2254 Added the ability to adjust the label display position
  .changeset/mighty-feet-glow.md
  packages/components/charts/src/chart.types.ts
  packages/components/charts/src/donut-chart.tsx
  packages/components/charts/src/pie-chart-label.tsx
  packages/components/charts/src/pie-chart.tsx
  packages/components/charts/src/use-pie-chart.ts
  packages/components/charts/tests/donut-chart.test.tsx
  packages/components/charts/tests/pie-chart.test.tsx
  packages/theme/src/components/pie-chart.ts
  stories/components/feedback/donut-chart.stories.tsx
  stories/components/feedback/pie-chart.stories.tsx
Labels: merge request

#2263 [List] rewrote unittests
  packages/components/list/tests/list.test.tsx
Labels: test, merge request

#2268 Updated dependencies
  .changeset/hungry-rocks-shake.md
  packages/components/motion/package.json
  packages/components/motion/tests/motion.test.tsx
  packages/components/transitions/tests/slide-fade.test.tsx
  packages/components/transitions/tests/slide.test.tsx
  pnpm-lock.yaml
Labels: merge request

#2257 fix test of layouts
  packages/components/layouts/tests/layouts.test.tsx
Labels: merge request

#2249 Enhance the accessibility of `YearPicker`
  .changeset/odd-doors-poke.md
  packages/components/calendar/src/use-year-list.tsx
  packages/components/calendar/src/use-year-picker.ts
  packages/components/calendar/src/year-picker.tsx
Labels: merge request

#2238 [Select] Enhance `Select` component accessibility
  .changeset/itchy-cameras-roll.md
  packages/components/select/src/option.tsx
  packages/components/select/src/use-select.ts
  packages/components/select/tests/select.test.tsx
Labels: test, merge request

#2272 refactoring of `motion` and `transitions` tests
  packages/components/motion/tests/motion.test.tsx
  packages/components/transitions/tests/collapse.test.tsx
  packages/components/transitions/tests/fade.test.tsx
  packages/components/transitions/tests/scale-fade.test.tsx
  packages/components/transitions/tests/slide-fade.test.tsx
  packages/components/transitions/tests/slide.test.tsx
Labels: merge request

#2258 added charts documention
  docs/contents/components/feedback/area-chart/index.ja.mdx
  docs/contents/components/feedback/area-chart/index.mdx
  docs/contents/components/feedback/bar-chart/index.ja.mdx
  docs/contents/components/feedback/bar-chart/index.mdx
  docs/contents/components/feedback/donut-chart/index.ja.mdx
  docs/contents/components/feedback/donut-chart/index.mdx
  docs/contents/components/feedback/line-chart/index.ja.mdx
  docs/contents/components/feedback/line-chart/index.mdx
  docs/contents/components/feedback/pie-chart/index.ja.mdx
  docs/contents/components/feedback/pie-chart/index.mdx
Labels: merge request

#2274 test: improved test coverage rate for tables
  packages/components/table/tests/table.test.tsx
Labels: merge request

#2261 Enhance the accessibility of `MultiDatePicker` component
  .changeset/large-students-cover.md
  packages/components/calendar/src/multi-date-picker.tsx
  packages/components/calendar/src/use-month.tsx
  packages/components/calendar/src/use-multi-date-picker.ts
Labels: merge request

#2259 Enhance test coverage for `segmented-control`
  packages/components/segmented-control/tests/segmented-control.test.tsx
Labels: merge request

#2276 Enhance the accessibility of `DatePicker`
  .changeset/proud-guests-complain.md
  packages/components/calendar/src/date-picker.tsx
  packages/components/calendar/src/use-date-picker.ts
Labels: merge request

#2280 Added `cspell`
  cspell.json
  docs/contents/components/data-display/card/index.ja.mdx
  docs/contents/components/data-display/card/index.mdx
  docs/contents/components/data-display/native-table/index.ja.mdx
  docs/contents/components/data-display/table/index.ja.mdx
  docs/contents/components/disclosure/tabs/accessibility.ja.mdx
  docs/contents/components/disclosure/tabs/accessibility.mdx
  docs/contents/components/forms/checkbox/accessibility.ja.mdx
  docs/contents/components/forms/radio/accessibility.ja.mdx
  docs/contents/components/other/ripple/index.ja.mdx
  docs/contents/components/overlay/drawer/index.ja.mdx
  docs/contents/components/overlay/drawer/index.mdx
  docs/contents/components/overlay/modal/index.ja.mdx
  docs/contents/components/overlay/modal/index.mdx
  docs/contents/components/overlay/tooltip/index.ja.mdx
  docs/contents/hooks/use-notice.ja.mdx
  docs/contents/hooks/use-snacks.ja.mdx
  docs/contents/hooks/use-theme.ja.mdx
  docs/contents/hooks/use-theme.mdx
  docs/contents/styled-system/theming/customize-theme.ja.mdx
  docs/contents/styled-system/theming/customize-theme.mdx
  package.json
  packages/components/autocomplete/tests/multi-autocomplete.test.tsx
  packages/components/calendar/tests/calendar.test.tsx
  packages/components/carousel/src/carousel-indicators.tsx
  packages/components/charts/tests/area-chart.test.tsx
  packages/components/charts/tests/bar-chart.test.tsx
  packages/components/charts/tests/line-chart.test.tsx
  packages/components/charts/tests/radar-chart.test.tsx
  packages/components/color-picker/tests/alpha-slider.test.tsx
  packages/components/file-button/tests/file-button.test.tsx
  packages/components/file-input/tests/file-input.test.tsx
  packages/components/motion/tests/motion.test.tsx
  packages/components/pagination/src/pagination-item.tsx
  packages/components/portal/tests/portal.test.tsx
  packages/components/segmented-control/tests/segmented-control.test.tsx
  packages/components/snacks/tests/snacks.test.tsx
  packages/components/table/tests/table.test.tsx
  packages/hooks/use-infinite-scroll/tests/index.test.tsx
  packages/hooks/use-os/tests/use-os.test.tsx
  pnpm-lock.yaml
  stories/hooks/use-disclosure.stories.tsx
Labels: merge request

#2290 Updated dependencies and refactored code
  package.json
  packages/components/accordion/src/accordion.tsx
  packages/components/portal/src/default-portal.tsx
  packages/hooks/use-descendant/src/index.ts
  packages/hooks/use-event-listener/src/index.ts
  pnpm-lock.yaml
  scripts/generate-css/index.ts
Labels: merge request

#2279 Corrected typo in variable name 'isPercent'
  .changeset/healthy-geese-perform.md
  docs/contents/components/feedback/donut-chart/index.ja.mdx
  docs/contents/components/feedback/donut-chart/index.mdx
  docs/contents/components/feedback/donut-chart/props.ja.mdx
  docs/contents/components/feedback/donut-chart/props.mdx
  docs/contents/components/feedback/pie-chart/index.ja.mdx
  docs/contents/components/feedback/pie-chart/index.mdx
  docs/contents/components/feedback/pie-chart/props.ja.mdx
  docs/contents/components/feedback/pie-chart/props.mdx
  packages/components/charts/DOCS.json
  packages/components/charts/src/donut-chart.tsx
  packages/components/charts/src/pie-chart-label.tsx
  packages/components/charts/src/pie-chart.tsx
  packages/components/charts/src/use-pie-chart.ts
  packages/components/charts/tests/donut-chart.test.tsx
  packages/components/charts/tests/pie-chart.test.tsx
  stories/components/feedback/donut-chart.stories.tsx
  stories/components/feedback/pie-chart.stories.tsx
Labels: merge request

#2253 [Markdown] Refactoring and expanding unit tests
  .changeset/moody-plants-tie.md
  packages/components/markdown/src/markdown.tsx
  packages/components/markdown/src/patterns.ts
  packages/components/markdown/src/remark-ui-component.ts
  packages/components/markdown/src/utils.ts
  packages/components/markdown/tests/markdown.test.tsx
  packages/components/markdown/tests/with-note-components.test.tsx
Labels: merge request

#2293 test(avatar): refactor unittests for `<Avatar />`
  packages/components/avatar/tests/avatar.test.tsx
Labels: test, merge request

#2297 Updated proxy target parameter name
  packages/components/markdown/src/remark-ui-component.ts
Labels: merge request

#2281 Move @yamada-ui/charts to Data Display
  docs/contents/components/data-display/area-chart/index.ja.mdx
  docs/contents/components/data-display/area-chart/index.mdx
  docs/contents/components/data-display/area-chart/props.ja.mdx
  docs/contents/components/data-display/area-chart/props.mdx
  docs/contents/components/data-display/area-chart/theming.ja.mdx
  docs/contents/components/data-display/area-chart/theming.mdx
  docs/contents/components/data-display/bar-chart/index.ja.mdx
  docs/contents/components/data-display/bar-chart/index.mdx
  docs/contents/components/data-display/bar-chart/props.ja.mdx
  docs/contents/components/data-display/bar-chart/props.mdx
  docs/contents/components/data-display/bar-chart/theming.ja.mdx
  docs/contents/components/data-display/bar-chart/theming.mdx
  docs/contents/components/data-display/donut-chart/index.ja.mdx
  docs/contents/components/data-display/donut-chart/index.mdx
  docs/contents/components/data-display/donut-chart/props.ja.mdx
  docs/contents/components/data-display/donut-chart/props.mdx
  docs/contents/components/data-display/donut-chart/theming.ja.mdx
  docs/contents/components/data-display/donut-chart/theming.mdx
  docs/contents/components/data-display/line-chart/index.ja.mdx
  docs/contents/components/data-display/line-chart/index.mdx
  docs/contents/components/data-display/line-chart/props.ja.mdx
  docs/contents/components/data-display/line-chart/props.mdx
  docs/contents/components/data-display/line-chart/theming.ja.mdx
  docs/contents/components/data-display/line-chart/theming.mdx
  docs/contents/components/data-display/pie-chart/index.ja.mdx
  docs/contents/components/data-display/pie-chart/index.mdx
  docs/contents/components/data-display/pie-chart/props.ja.mdx
  docs/contents/components/data-display/pie-chart/props.mdx
  docs/contents/components/data-display/pie-chart/theming.ja.mdx
  docs/contents/components/data-display/pie-chart/theming.mdx
  docs/contents/components/data-display/radar-chart/index.ja.mdx
  docs/contents/components/data-display/radar-chart/index.mdx
  docs/contents/components/data-display/radar-chart/props.ja.mdx
  docs/contents/components/data-display/radar-chart/props.mdx
  docs/contents/components/data-display/radar-chart/theming.ja.mdx
  docs/contents/components/data-display/radar-chart/theming.mdx
  stories/components/data-display/area-chart.stories.tsx
  stories/components/data-display/bar-chart.stories.tsx
  stories/components/data-display/donut-chart.stories.tsx
  stories/components/data-display/line-chart.stories.tsx
  stories/components/data-display/pie-chart.stories.tsx
  stories/components/data-display/radar-chart.stories.tsx
Labels: merge request

#2302 Updated payload format in CI script
  .github/workflows/observe-issue-and-pull-request.yml
Labels: merge request

#2273 feat(docs): add the a11y section for `Modal` component
  docs/contents/components/overlay/modal/accessibility.ja.mdx
  docs/contents/components/overlay/modal/accessibility.mdx
  docs/contents/components/overlay/modal/props.ja.mdx
  docs/contents/components/overlay/modal/props.mdx
  docs/contents/components/overlay/modal/theming.ja.mdx
  docs/contents/components/overlay/modal/theming.mdx
Labels: documentation, a11y

#2292 feat(docs): add the a11y section for `CloseButton` component
  docs/contents/components/other/close-button/accessibility.ja.mdx
  docs/contents/components/other/close-button/accessibility.mdx
  docs/contents/components/other/close-button/props.ja.mdx
  docs/contents/components/other/close-button/props.mdx
  docs/contents/components/other/close-button/theming.ja.mdx
  docs/contents/components/other/close-button/theming.mdx
Labels: documentation, a11y

#2308 Fixed popover close issue on multiple opens
  .changeset/yellow-lobsters-travel.md
  packages/hooks/use-focus/src/index.ts
Labels: merge request

#2304 Updated invalid input documentation
  docs/contents/components/forms/editable/index.ja.mdx
  docs/contents/components/forms/editable/index.mdx
Labels: merge request

#2309 Thematize `Icon` component
  .changeset/brave-bulldogs-compare.md
  packages/components/icon/src/icon.tsx
  packages/theme/src/components/icon.ts
  packages/theme/src/components/index.ts
Labels: merge request

#2303 feat: add a11y section for file-button
  docs/contents/components/forms/file-button/accessibility.ja.mdx
  docs/contents/components/forms/file-button/accessibility.mdx
  docs/contents/components/forms/file-button/props.ja.mdx
  docs/contents/components/forms/file-button/props.mdx
Labels: merge request

#2306 fix: remove `UIComponents`
  docs/components/mdx/editable-code-block.tsx
Labels: review wanted, merge request

#2314 Fix typo in `Stack` component
  .changeset/wild-adults-punch.md
  packages/components/layouts/src/stack.tsx
Labels: merge request

#2322 Fixed version to 8.2.0
  package.json
  pnpm-lock.yaml
Labels: merge request

#2311 Fixed a bug where the numbers were not correct
  scripts/report-insights.ts
Labels: merge request

#2316 fix: remove duplicate dates declaration in getRangeDates function
  .changeset/tall-walls-march.md
  packages/components/calendar/src/calendar-utils.ts
Labels: merge request

#2318 Added `onConsoleLog` filter for stderr
  vitest.config.mts
Labels: merge request

#2312 Enhance Test Coverage for `@yamada-ui/layouts`
  packages/components/layouts/tests/layouts.test.tsx
Labels: merge request

#2321 Optimized output variable assignments
  .github/composite-actions/check-modified-files/action.yml
  .github/workflows/quality.yml
Labels: merge request

#2287 Add accessibility section for `Stat`
  docs/contents/components/data-display/stat/accessibility.ja.mdx
  docs/contents/components/data-display/stat/accessibility.mdx
  docs/contents/components/data-display/stat/props.ja.mdx
  docs/contents/components/data-display/stat/props.mdx
  docs/contents/components/data-display/stat/theming.ja.mdx
  docs/contents/components/data-display/stat/theming.mdx
Labels: review wanted

#2326 Update script naming and organization
  .github/composite-actions/update-docs/action.yml
  docs/package.json
  docs/scripts/component/props.ts
  docs/scripts/component/theme.ts
  docs/scripts/component/utils.ts
  docs/scripts/content/changelog.ts
  docs/scripts/content/contributors.ts
  docs/scripts/content/search.ts
  docs/scripts/content/styled-system.ts
  docs/scripts/content/translate.ts
  docs/scripts/generate-icon-tags.ts
  docs/scripts/utils.ts
  package.json
Labels: merge request

#2317 Added `use-breakpoint` tests
  .changeset/chilled-ravens-leave.md
  packages/hooks/use-breakpoint/src/index.ts
  packages/hooks/use-breakpoint/tests/index.test.tsx
Labels: review wanted, merge request

#2331 Updated GitHub action dependencies
  .github/composite-actions/update-docs/action.yml
Labels: merge request

#2332 Expanded conditions for skipping pr actions
  docs/pages/api/github/observe/update-pull-requests.ts
  docs/pages/api/github/webhook/pull-request/opened.ts
Labels: merge request

#2334 Fixed a bug where `Icon`'s `baseStyle` was set to `defaultProps`
  .changeset/cuddly-mayflies-refuse.md
  .changeset/fluffy-maps-bake.md
  packages/components/icon/src/icon.tsx
  packages/theme/src/components/icon.ts
Labels: merge request

#2336 Added theme support and refactored code
  .changeset/proud-snakes-wave.md
  .changeset/rare-pears-teach.md
  packages/components/file-button/src/file-button.tsx
  packages/core/src/components/component.types.ts
  packages/core/src/components/use-component-style.tsx
  packages/core/src/css/css.types.ts
  packages/core/src/theme.ts
  packages/theme/src/components/file-button.ts
  packages/theme/src/components/index.ts
Labels: merge request

#2345 Added cleanup function test
  packages/hooks/use-event-listener/tests/index.test.ts
Labels: merge request

#2346 Added tests for accept, reject, idle states
  packages/components/dropzone/tests/dropzone.test.tsx
Labels: merge request

#2340 Updated type definitions and styles
  .changeset/little-students-itch.md
  docs/theme/components/button.ts
  docs/theme/components/mark.ts
  packages/core/src/theme.types.ts
Labels: merge request

#2343 Added `Reorder` tests.
  .changeset/short-beers-hope.md
  packages/components/reorder/src/reorder.tsx
  packages/components/reorder/tests/reorder.test.tsx
Labels: merge request

#2352 Added `changeset-release/docs` to CI triggers
  .github/workflows/quality.yml
Labels: merge request

#2337 Updated user exclusion logic in insights
  scripts/report-insights.ts
Labels: merge request

#2349 Update theming logic and props handling
  .changeset/blue-crabs-pretend.md
  .changeset/nervous-papayas-retire.md
  .changeset/proud-snakes-wave.md
  .changeset/six-dragons-grab.md
  packages/components/button/src/button.tsx
  packages/components/file-button/src/file-button.tsx
  packages/core/src/components/use-component-style.tsx
  packages/core/src/css/css.types.ts
  packages/core/src/theme.ts
  packages/core/src/theme.types.ts
Labels: merge request

#2351 Updated Japanese and English documentation
  docs/contents/styled-system/theming/component-styles.ja.mdx
  docs/contents/styled-system/theming/component-styles.mdx
Labels: merge request

#2344 Updated position calculation logic
  packages/components/layouts/src/stack.tsx
  packages/components/layouts/tests/layouts.test.tsx
Labels: review wanted, merge request

#2350 Updated terminology and added event handlers
  docs/contents/components/data-display/carousel/index.ja.mdx
  docs/contents/components/data-display/carousel/index.mdx
Labels: review wanted, merge request

#2362 Updated token references in actions
  .github/composite-actions/update-docs/action.yml
  .github/workflows/release.yml
Labels: merge request

#2363 Updated documentation
  docs/contents/components/data-display/carousel/index.ja.mdx
  docs/contents/components/data-display/carousel/index.mdx
  docs/contents/components/data-display/carousel/props.ja.mdx
  docs/contents/components/data-display/carousel/props.mdx
  docs/contents/components/forms/file-button/props.ja.mdx
  docs/contents/components/forms/file-button/props.mdx
  docs/contents/components/forms/file-button/theming.ja.mdx
  docs/contents/components/forms/file-button/theming.mdx
  docs/contents/components/media-and-icons/fontawesome/props.ja.mdx
  docs/contents/components/media-and-icons/fontawesome/props.mdx
  docs/contents/components/media-and-icons/icon/props.ja.mdx
  docs/contents/components/media-and-icons/icon/props.mdx
  docs/contents/components/media-and-icons/icon/theming.ja.mdx
  docs/contents/components/media-and-icons/icon/theming.mdx
  docs/contents/components/media-and-icons/image/theming.ja.mdx
  docs/contents/components/media-and-icons/image/theming.mdx
  docs/contents/components/media-and-icons/lucide/props.ja.mdx
  docs/contents/components/media-and-icons/lucide/props.mdx
  docs/contents/styled-system/theming/component-styles.ja.mdx
  docs/contents/styled-system/theming/component-styles.mdx
  docs/i18n/content.en.json
  docs/i18n/content.ja.json
  docs/pages/icons/tags.ts
  packages/components/calendar/DOCS.json
  packages/components/carousel/DOCS.json
  packages/components/file-button/DOCS.json
  packages/components/fontawesome/DOCS.json
  packages/components/icon/DOCS.json
  packages/components/lucide/DOCS.json
Labels: merge request

#2366 Fixed selection issue in `Select` components
  .changeset/angry-tips-move.md
  packages/components/select/src/use-select.ts
Labels: merge request

#2369 Updated documentation order for fileButton
  docs/contents/components/forms/file-button/accessibility.ja.mdx
  docs/contents/components/forms/file-button/accessibility.mdx
  docs/contents/components/forms/file-button/theming.ja.mdx
  docs/contents/components/forms/file-button/theming.mdx
Labels: merge request

#2372 Updated documentation and fixed typos
  cspell.json
  docs/contents/components/data-display/list/index.ja.mdx
  docs/contents/components/data-display/list/index.mdx
  docs/contents/components/navigation/breadcrumb/index.mdx
  docs/contents/components/other/motion/index.ja.mdx
  docs/contents/components/other/motion/index.mdx
  docs/contents/styled-system/animation.ja.mdx
  docs/contents/styled-system/animation.mdx
  docs/contents/styled-system/gradient.mdx
  docs/contents/styled-system/notification.ja.mdx
  docs/contents/styled-system/text-and-layer-styles.mdx
  packages/components/markdown/tests/markdown.test.tsx
  stories/components/motion/scroll.stories.tsx
Labels: merge request

#2361 Updated pnpm action to v4 in CI config
  .github/composite-actions/install/action.yml
Labels: review wanted, merge request

#2364 Update package manager version and remove config
  package.json
  pnpm-lock.yaml
Labels: review wanted, merge request

#2371 fixed `Rating` document
  docs/contents/components/forms/rating/index.ja.mdx
Labels: merge request

#2375 fix: file-button testcodes fix
  packages/components/file-button/tests/file-button.test.tsx
Labels: merge request

#2377 Fixed `fontSize` and `boxSize` handling
  .changeset/little-walls-build.md
  packages/components/icon/src/icon.tsx
  packages/components/image/src/image.tsx
  packages/components/tag/tests/tag.test.tsx
Labels: merge request
