Repository yamada-ui/yamada-ui, pull requests merged in 2024-08, with the labels that each got.

#2382 chore(docs): remove `prepare` command in `package.json`
  docs/package.json
Labels: merge request

#2378 Update tests to use async assertions
  packages/components/reorder/tests/reorder.test.tsx
Labels: merge request

#2385 test(close-button): rename `test` to `tests`
  packages/components/close-button/tests/close-button.test.tsx
Labels: merge request

#2386 test(kbd): rename `test` to `tests`
  packages/components/kbd/tests/kbd.test.tsx
Labels: merge request

#2384 Update contributor and member lists
  docs/constant/contributors.ts
  docs/constant/maintainers.ts
  docs/constant/members.ts
Labels: merge request

#2383 Remove `axe-core` from `@yamada-ui/test`
  .changeset/mean-ghosts-protect.md
  packages/test/package.json
  packages/test/src/accessibility.tsx
  pnpm-lock.yaml
Labels: merge request

#2392 Updated type definitions for color props
  .changeset/shaggy-lies-suffer.md
  packages/components/color-picker/src/color-swatch.tsx
  packages/components/color-picker/src/use-color-selector.ts
Labels: merge request

#2389 Updated JSON body key order in script
  .github/workflows/observe-issue-and-pull-request.yml
Labels: merge request

#2397 Corrected type definitions and props handling
  .changeset/breezy-garlics-jog.md
  packages/components/autocomplete/src/autocomplete-list.tsx
  packages/components/modal/src/modal.tsx
  packages/components/motion/src/motion.tsx
  packages/components/popover/src/popover-content.tsx
  packages/components/select/src/select-list.tsx
Labels: merge request

#2404 Added `onClose` prop to children handling
  .changeset/nice-clouds-rhyme.md
  .changeset/witty-spiders-bathe.md
  packages/components/color-picker/src/color-picker.tsx
  packages/components/color-picker/src/use-color-picker.ts
  stories/components/forms/color-picker.stories.tsx
Labels: merge request

#2402 Added Hinata Ohyama to members list
  docs/constant/members.ts
Labels: merge request

#2395 Add formatter props to chart components
  .changeset/sixty-sheep-eat.md
  packages/components/charts/src/area-chart.tsx
  packages/components/charts/src/bar-chart.tsx
  packages/components/charts/src/chart-tooltip.tsx
  packages/components/charts/src/donut-chart.tsx
  packages/components/charts/src/line-chart.tsx
  packages/components/charts/src/pie-chart-label.tsx
  packages/components/charts/src/pie-chart.tsx
  packages/components/charts/src/radar-chart.tsx
  packages/components/charts/src/use-chart-axis.ts
  packages/components/charts/src/use-chart-tooltip.ts
  packages/components/charts/src/use-pie-chart.ts
  packages/components/charts/src/use-radar-chart.ts
  packages/components/charts/tests/area-chart.test.tsx
  packages/components/charts/tests/bar-chart.test.tsx
  packages/components/charts/tests/donut-chart.test.tsx
  packages/components/charts/tests/line-chart.test.tsx
  packages/components/charts/tests/pie-chart.test.tsx
  stories/components/data-display/area-chart.stories.tsx
  stories/components/data-display/bar-chart.stories.tsx
  stories/components/data-display/donut-chart.stories.tsx
  stories/components/data-display/line-chart.stories.tsx
  stories/components/data-display/pie-chart.stories.tsx
  stories/components/data-display/radar-chart.stories.tsx
Labels: merge request

#2300 Feat/doc a11y editable
  docs/contents/components/forms/editable/accessibility.ja.mdx
  docs/contents/components/forms/editable/accessibility.mdx
  docs/contents/components/forms/editable/props.ja.mdx
  docs/contents/components/forms/editable/props.mdx
  docs/contents/components/forms/editable/theming.ja.mdx
  docs/contents/components/forms/editable/theming.mdx
Labels: review wanted, merge request

#2414 Enhance Test Coverage for `@yamada-ui/use-size`
  packages/hooks/use-size/tests/index.test.tsx
Labels: merge request

#2416 Moved spaces to semantics tokens
  .changeset/dull-ghosts-beg.md
  packages/theme/src/semantics.ts
  packages/theme/src/tokens/spaces.ts
Labels: merge request

#2387 Updated reviewer assignment logic
  docs/pages/api/github/webhook/pull-request/opened.ts
Labels: merge request

#2419 Reorder theme size and spacing identifiers
  .changeset/beige-peaches-hug.md
  packages/core/src/generated-theme.types.ts
Labels: merge request

#2415 Added Insight page
  .github/workflows/insight-report.yml
  .github/workflows/insight-upload.yml
  docs/@types/insights.d.ts
  docs/components/transitions/count-up.tsx
  docs/components/transitions/index.ts
  docs/i18n/ui.en.json
  docs/i18n/ui.ja.json
  docs/package.json
  docs/pages/_app.page.tsx
  docs/pages/api/insights/index.api.ts
  docs/pages/insights/index.page.tsx
  docs/pages/insights/insights-header.tsx
  docs/pages/insights/insights-provider.tsx
  docs/pages/insights/insights-utils.ts
  docs/pages/insights/total-chart.tsx
  docs/pages/insights/user-chart.tsx
  docs/pages/insights/user-charts.tsx
  docs/theme/index.ts
  pnpm-lock.yaml
  scripts/report-insights.ts
  scripts/utils.ts
Labels: merge request

#2426 Adjusted weekstart calculation in CI script
  .github/workflows/insight-report.yml
Labels: merge request

#2401 Updated children prop types and docs
  .changeset/rotten-mugs-cheat.md
  packages/components/color-picker/src/color-selector.tsx
Labels: merge request

#2400 Add children prop and runIfFunc usage
  .changeset/brave-ties-work.md
  packages/components/calendar/src/date-picker.tsx
  packages/components/calendar/src/month-picker.tsx
  packages/components/calendar/src/multi-date-picker.tsx
  packages/components/calendar/src/range-date-picker.tsx
  packages/components/calendar/src/use-calendar-picker.ts
  packages/components/calendar/src/use-date-picker.ts
  packages/components/calendar/src/use-month-picker.ts
  packages/components/calendar/src/use-multi-date-picker.ts
  packages/components/calendar/src/use-range-date-picker.ts
  packages/components/calendar/src/use-year-picker.ts
  packages/components/calendar/src/year-picker.tsx
  stories/components/forms/date-picker.stories.tsx
  stories/components/forms/month-picker.stories.tsx
  stories/components/forms/multi-date-picker.stories.tsx
  stories/components/forms/range-date-picker.stories.tsx
  stories/components/forms/year-picker.stories.tsx
Labels: review wanted, merge request

#2413 update charts documentation
  cspell.json
  docs/contents/components/data-display/area-chart/index.ja.mdx
  docs/contents/components/data-display/area-chart/index.mdx
  docs/contents/components/data-display/bar-chart/index.ja.mdx
  docs/contents/components/data-display/bar-chart/index.mdx
  docs/contents/components/data-display/donut-chart/index.ja.mdx
  docs/contents/components/data-display/donut-chart/index.mdx
  docs/contents/components/data-display/line-chart/index.ja.mdx
  docs/contents/components/data-display/line-chart/index.mdx
  docs/contents/components/data-display/pie-chart/index.ja.mdx
  docs/contents/components/data-display/pie-chart/index.mdx
  docs/contents/components/data-display/radar-chart/index.ja.mdx
  docs/contents/components/data-display/radar-chart/index.mdx
Labels: review wanted

#2431 Added locale support to user names
  docs/pages/insights/user-chart.tsx
Labels: merge request

#2429 Added period suggest to Insights page
  docs/pages/insights/insights-header.tsx
Labels: merge request

#2428 Added cell props to BarChart and updated types
  .changeset/spicy-mugs-doubt.md
  packages/components/charts/src/bar-chart.tsx
  packages/components/charts/src/chart.types.ts
  packages/components/charts/src/index.ts
  packages/components/charts/src/use-bar-chart.tsx
Labels: merge request

#2430 Updated default start date calculation
  docs/pages/insights/index.page.tsx
Labels: merge request

#2423 feat: add `onDoubleClickRow` callback to `Tbody` component
  .changeset/chilled-foxes-develop.md
  packages/components/table/src/tbody.tsx
  packages/components/table/src/use-table.tsx
  packages/components/table/tests/table.test.tsx
  stories/components/data-display/table.stories.tsx
Labels: review wanted, merge request

#2417 Enhance Test Coverage for @yamada-ui/select
  packages/components/select/tests/multi-select.test.tsx
  packages/components/select/tests/select.test.tsx
Labels: merge request

#2442 Updated date handling and imports
  docs/pages/insights/insights-header.tsx
  docs/pages/insights/insights-utils.ts
Labels: merge request

#2444 Fixed a bug where the width was not changed even if `width` etc. was set in `listProps` of `Select` and `MultiSelect`.
  .changeset/bright-tigers-lick.md
  .changeset/green-berries-leave.md
  packages/components/autocomplete/src/autocomplete-list.tsx
  packages/components/select/src/select-list.tsx
Labels: merge request

#2447 Added `closeStrategy`
  .changeset/six-buses-count.md
  .changeset/sweet-maps-jam.md
  packages/components/notice/src/notice.tsx
  packages/components/snacks/src/use-snacks.tsx
  packages/core/src/theme.types.ts
  stories/hooks/use-notice.stories.tsx
  stories/hooks/use-snacks.stories.tsx
Labels: merge request

#2454 Updated space tokens.
  .changeset/quiet-starfishes-drum.md
  packages/theme/src/tokens/spaces.ts
  stories/documents/theme/colors.mdx
  stories/documents/theme/spaces.mdx
Labels: merge request

#2458 Fix a full-width space in the token to half-width space.
  .changeset/late-days-hug.md
  packages/theme/src/tokens/shadows.ts
Labels: merge request

#2460 Added `generate` function for themes
  .changeset/wise-forks-double.md
  packages/theme-tools/src/generate.ts
  packages/theme-tools/src/index.ts
  packages/theme-tools/tests/generate.test.ts
Labels: merge request

#2452 Updated space tokens documentation
  docs/contents/getting-started/basics.ja.mdx
  docs/contents/getting-started/basics.mdx
  docs/contents/styled-system/semantic-tokens.ja.mdx
  docs/contents/styled-system/semantic-tokens.mdx
  docs/contents/styled-system/theming/customize-theme.ja.mdx
  docs/contents/styled-system/theming/customize-theme.mdx
  docs/contents/styled-system/theming/default-theme.ja.mdx
  docs/contents/styled-system/theming/default-theme.mdx
Labels: merge request

#2478 Fixed en docs for `Typography`
  docs/contents/styled-system/theming/default-theme.mdx
  docs/i18n/content.en.json
Labels: merge request

#2470 Added api tests
  docs/.eslintrc.json
  docs/package.json
  docs/pages/api/github/observe/index.api.ts
  docs/pages/api/github/observe/update-issues.test.ts
  docs/pages/api/github/observe/update-issues.ts
  docs/pages/api/github/observe/update-pull-request.test.ts
  docs/pages/api/github/observe/update-pull-requests.ts
  docs/pages/api/github/webhook/pull-request/review-request-removed.ts
  docs/scripts/setup-test.ts
  docs/utils/github.ts
  docs/vitest.config.mts
  package.json
  pnpm-lock.yaml
Labels: merge request

#2445 Added listProps and itemProps to notice components
  .changeset/little-socks-reflect.md
  packages/components/notice/src/notice-provider.tsx
  packages/core/src/theme.types.ts
Labels: merge request

#2480 feat(core): add new size options to theme types
  .changeset/old-carpets-reply.md
  packages/core/src/generated-theme.types.ts
Labels: merge request

#2501 Fix deprecated `size` prop usage in `Menu` test code
  packages/components/menu/tests/menu.test.tsx
Labels: merge request

#2504 Fix deprecated `size` props usage in the Storybook `Loading` page
  stories/components/feedback/loading.stories.tsx
Labels: merge request

#2505 Update pre-commit and commit-msg hooks
  lefthook.yaml
Labels: merge request

#2509 refactor: Deprecated props are being used in the example pages.
  docs/pages/examples/authentication/company.tsx
  docs/pages/examples/cards/bookmark-card.tsx
  docs/pages/examples/cards/notification-card.tsx
  docs/pages/examples/dashboard/cards.tsx
  docs/pages/examples/mail/detail.tsx
Labels: merge request

#2477 Add missing tests for file-button
  packages/components/file-button/tests/file-button.test.tsx
Labels: merge request

#2411 Thematize `CircleProgress` component
  .changeset/late-bottles-wait.md
  packages/components/progress/src/circle-progress.tsx
  packages/theme/src/components/circle-progress.ts
  packages/theme/src/components/index.ts
  stories/components/feedback/circle-progress.stories.tsx
Labels: review wanted

#2514 refactor: Deprecated props are being used in the Storybook Theme/Loadingpage.
  stories/system/theme/loading.stories.tsx
Labels: merge request

#2503 Updated dependencies
  .changeset/nasty-pandas-wait.md
  .changeset/shy-geckos-train.md
  .changeset/tough-trains-drive.md
  docs/package.json
  docs/pages/api/github/observe/index.api.ts
  docs/pages/api/github/webhook/index.api.ts
  docs/scripts/component/props.ts
  docs/scripts/content/translate.ts
  docs/utils/mdx.ts
  examples/create-react-app/package.json
  examples/hono/package.json
  examples/nextjs-app/package.json
  examples/nextjs-pages/package.json
  examples/remix/package.json
  examples/vite/package.json
  package.json
  packages/cli/package.json
  packages/cli/src/utils/fs.ts
  packages/components/carousel/package.json
  packages/components/lucide/package.json
  packages/components/lucide/src/icons/amphora.tsx
  packages/components/lucide/src/icons/bandage.tsx
  packages/components/lucide/src/icons/binoculars.tsx
  packages/components/lucide/src/icons/chevrons-left-right-ellipsis.tsx
  packages/components/lucide/src/icons/circle-fading-arrow-up.tsx
  packages/components/lucide/src/icons/ethernet-port.tsx
  packages/components/lucide/src/icons/id-card.tsx
  packages/components/lucide/src/icons/index.ts
  packages/components/lucide/src/icons/index.types.ts.tsx
  packages/components/lucide/src/icons/map-pin-check-inside.tsx
  packages/components/lucide/src/icons/map-pin-check.tsx
  packages/components/lucide/src/icons/map-pin-house.tsx
  packages/components/lucide/src/icons/map-pin-minus-inside.tsx
  packages/components/lucide/src/icons/map-pin-minus.tsx
  packages/components/lucide/src/icons/map-pin-plus-inside.tsx
  packages/components/lucide/src/icons/map-pin-plus.tsx
  packages/components/lucide/src/icons/map-pin-x-inside.tsx
  packages/components/lucide/src/icons/map-pin-x.tsx
  packages/components/lucide/src/icons/microchip.tsx
  packages/components/lucide/src/icons/omega.tsx
  packages/components/lucide/src/icons/square-square.tsx
  packages/components/lucide/src/icons/table-of-contents.tsx
  packages/components/lucide/src/icons/tickets.tsx
  packages/components/markdown/package.json
  packages/components/motion/package.json
  packages/components/resizable/package.json
  packages/components/table/package.json
  packages/components/transitions/tests/slide-fade.test.tsx
  packages/components/transitions/tests/slide.test.tsx
  packages/core/package.json
  packages/core/src/providers/color-mode-manager.ts
  packages/core/src/providers/theme-manager.ts
  packages/hooks/use-local-storage/src/index.ts
  packages/nextjs/package.json
  packages/utils/src/react.tsx
  pnpm-lock.yaml
Labels: merge request

#2481 Updated data handling with constants
  docs/pages/api/insights/index.api.ts
Labels: merge request

#2527 Added `drag` function for test
  .changeset/blue-rabbits-sparkle.md
  packages/components/reorder/tests/reorder.test.tsx
  packages/hooks/use-pan-event/tests/index.test.tsx
  packages/test/src/drag.ts
  packages/test/src/index.ts
Labels: merge request

#2462 Add trend insights
  docs/components/transitions/count-up.tsx
  docs/pages/api/insights/index.api.ts
  docs/pages/insights/index.page.tsx
  docs/pages/insights/insights-provider.tsx
  docs/pages/insights/insights-utils.ts
  docs/pages/insights/score-legend.tsx
  docs/pages/insights/total-chart.tsx
  docs/pages/insights/user-chart.tsx
  docs/pages/insights/user-charts.tsx
Labels: review wanted, merge request

#2519 Added `header` and `footer` props
  .changeset/chilled-shirts-march.md
  .changeset/cyan-ligers-yawn.md
  .changeset/dirty-rats-sin.md
  .changeset/eighty-cobras-drive.md
  .changeset/flat-impalas-dress.md
  .changeset/seven-pans-relate.md
  .changeset/shy-plants-poke.md
  .changeset/violet-ways-roll.md
  packages/components/autocomplete/src/autocomplete-list.tsx
  packages/components/autocomplete/src/autocomplete.tsx
  packages/components/autocomplete/src/multi-autocomplete.tsx
  packages/components/autocomplete/src/use-autocomplete.tsx
  packages/components/calendar/package.json
  packages/components/calendar/src/date-picker.tsx
  packages/components/calendar/src/month-picker.tsx
  packages/components/calendar/src/multi-date-picker.tsx
  packages/components/calendar/src/range-date-picker.tsx
  packages/components/calendar/src/year-picker.tsx
  packages/components/color-picker/src/color-picker.tsx
  packages/components/menu/src/menu-list.tsx
  packages/components/select/src/multi-select.tsx
  packages/components/select/src/select-list.tsx
  packages/components/select/src/select.tsx
  packages/components/select/src/use-select.ts
  packages/theme/src/components/color-picker.ts
  packages/theme/src/components/date-picker.ts
  packages/theme/src/components/menu.ts
  packages/theme/src/components/select.ts
  pnpm-lock.yaml
  stories/components/forms/autocomplete.stories.tsx
  stories/components/forms/multi-autocomplete.stories.tsx
  stories/components/forms/multi-select.stories.tsx
  stories/components/forms/select.stories.tsx
Labels: merge request

#2516 Simplify documentation request template text
  .github/ISSUE_TEMPLATE/documentation_request.ja.yml
  .github/ISSUE_TEMPLATE/documentation_request.yml
Labels: merge request

#2529 refactor: Deprecated props are being used in the Storybook Theme/FontAwesomePage.
  stories/components/media-and-icons/font-awesome.stories.tsx
Labels: merge request

#2511 Fix deprecated size prop usage in Loading component
  docs/contents/components/feedback/loading/index.ja.mdx
  docs/contents/components/feedback/loading/index.mdx
  docs/contents/styled-system/loading.ja.mdx
  docs/contents/styled-system/loading.mdx
Labels: merge request

#2518 refactor: replace deprecated `size` prop with `fontSize` in context menu
  docs/contents/components/overlay/context-menu/index.ja.mdx
  docs/contents/components/overlay/context-menu/index.mdx
Labels: review wanted, merge request

#2473 Added gradient functionality to styles
  .changeset/rich-pants-turn.md
  packages/core/src/styles.ts
  scripts/generate-css/transform-props.ts
Labels: merge request

#2476 `content: ''` is set by default for CSS pseudo-elements `:before` and `:after`
  .changeset/afraid-buckets-matter.md
  .changeset/mean-forks-smile.md
  docs/scripts/content/styled-system.ts
  packages/core/src/config.ts
  packages/core/src/css/css.ts
  packages/core/src/css/css.types.ts
  packages/core/src/index.ts
  packages/core/src/pseudos.ts
  packages/core/src/styles.ts
  scripts/generate-css/styles.ts
  scripts/generate-css/transform-props.ts
Labels: merge request

#2549 Add support for CSS variable parsing with `$` symbol
  .changeset/two-fishes-juggle.md
  packages/core/src/config.ts
  packages/core/src/constant.ts
  packages/core/src/css/css.ts
  packages/core/src/css/var.ts
Labels: merge request

#2530 Adjust date handling in insights module
  docs/pages/insights/index.page.tsx
  docs/pages/insights/insights-header.tsx
  docs/pages/insights/insights-utils.ts
Labels: merge request

#2542 Added `toTitleCase` function and updated regex
  .changeset/shiny-zoos-doubt.md
  packages/utils/src/string.ts
Labels: merge request

#2554 Corrected semantic color scheme handling
  .changeset/giant-taxis-sing.md
  .changeset/gorgeous-fireants-grin.md
  packages/cli/src/command/tokens/create-theme-typings.ts
  packages/core/src/generated-theme.types.ts
  packages/core/src/theme.ts
  packages/core/src/theme.types.ts
Labels: merge request

#2555 Refactor/storybook use infinite scroll
  docs/contents/hooks/use-infinite-scroll.ja.mdx
  docs/contents/hooks/use-infinite-scroll.mdx
  stories/hooks/use-infinite-scroll.stories.tsx
Labels: merge request

#2441 Updated motion types
  .changeset/brave-schools-reflect.md
  .changeset/little-shirts-report.md
  .changeset/new-gifts-train.md
  .changeset/pink-moons-cry.md
  packages/components/autocomplete/src/autocomplete-list.tsx
  packages/components/menu/src/menu-list.tsx
  packages/components/modal/src/dialog.tsx
  packages/components/modal/src/drawer.tsx
  packages/components/modal/src/modal-overlay.tsx
  packages/components/modal/src/modal.tsx
  packages/components/motion/src/index.ts
  packages/components/motion/src/motion-forward-ref.tsx
  packages/components/motion/src/motion.tsx
  packages/components/motion/src/motion.types.ts
  packages/components/motion/src/utils.ts
  packages/components/popover/src/popover-content.tsx
  packages/components/popover/src/popover.tsx
  packages/components/rating/src/rating-group.tsx
  packages/components/reorder/src/reorder-item.tsx
  packages/components/reorder/src/reorder.tsx
  packages/components/resizable/src/resizable-trigger.tsx
  packages/components/select/src/select-list.tsx
  packages/components/snacks/src/snacks.tsx
  packages/components/tooltip/src/tooltip.tsx
  packages/components/transitions/src/collapse.tsx
  packages/components/transitions/src/fade.tsx
  packages/components/transitions/src/scale-fade.tsx
  packages/components/transitions/src/slide-fade.tsx
  packages/components/transitions/src/slide.tsx
  packages/core/src/components/component.types.ts
  packages/core/src/components/forward-ref.ts
  packages/utils/src/index.types.ts
  packages/utils/src/react.tsx
Labels: review wanted, merge request

#2559 Added `containerProps` to `PopoverContent`
  .changeset/silver-poets-happen.md
  packages/components/popover/src/popover-content.tsx
Labels: merge request

#2536 fix: add Text component to the default theme
  .changeset/three-mirrors-dream.md
  .changeset/young-mayflies-punch.md
  packages/theme/src/components/index.ts
  packages/theme/src/components/text.ts
Labels: merge request

#2568 Add test for loading-provider force
  packages/components/loading/tests/loading-provider.test.tsx
Labels: merge request

#2545 Centralized color schemes and tones usage
  .changeset/silly-pianos-dream.md
  docs/pages/insights/total-chart.tsx
  docs/theme/index.ts
  examples/create-react-app/src/theme/index.ts
  examples/hono/src/theme/index.ts
  examples/nextjs-app/theme/index.ts
  examples/nextjs-pages/theme/index.ts
  examples/remix/app/theme/index.ts
  examples/vite/src/theme/index.ts
  packages/cli/src/command/tokens/create-theme-typings.ts
  packages/core/src/theme.ts
  packages/theme-tools/src/generate.ts
  packages/utils/src/color.ts
  scripts/generate-docs.ts
  stories/components.tsx
Labels: review wanted, merge request

#2560 Added create PR GitHub actions
  .github/composite-actions/sync-docs/action.yml
  .github/workflows/docs.yml
  .github/workflows/quality.yml
  .github/workflows/release.yml
  docs/pages/api/github/observe/update-pull-requests.ts
  docs/pages/api/github/webhook/pull-request/opened.ts
Labels: merge request

#2569 Updated type definitions and logic
  .changeset/wicked-tigers-rest.md
  packages/core/src/components/use-component-style.tsx
  packages/core/src/css/css.types.ts
  packages/core/src/theme.types.ts
Labels: merge request

#2558 Update Japanese style properties documentation
  docs/contents/styled-system/style-props.ja.mdx
  docs/contents/styled-system/style-props.mdx
  docs/scripts/content/styled-system.ts
  packages/core/src/config.ts
  packages/core/src/styles.ts
  scripts/generate-css/check.ts
  scripts/generate-css/config.ts
  scripts/generate-css/index.ts
  scripts/generate-css/styles.ts
  scripts/generate-css/ui-props.ts
Labels: merge request

#2551 Provided a convenience function for CSS `color-mix`.
  .changeset/large-ways-admire.md
  packages/core/src/config.ts
  packages/core/src/config/animation.ts
  packages/core/src/config/at-rule.ts
  packages/core/src/config/color-mix.ts
  packages/core/src/config/filter.ts
  packages/core/src/config/gradient.ts
  packages/core/src/config/index.ts
  packages/core/src/config/transform.ts
  packages/core/src/config/utils.ts
  packages/core/src/css/css.ts
  packages/core/src/styles.ts
  scripts/generate-css/styles.ts
  scripts/generate-css/tokens.ts
  scripts/generate-css/transform-props.ts
Labels: review wanted, merge request

#2532 Add user selection functionality in UI
  docs/i18n/ui.en.json
  docs/i18n/ui.ja.json
  docs/pages/insights/insights-header.tsx
  docs/pages/insights/insights-utils.ts
Labels: review wanted, merge request

#2546 Corrected theme color reference in getColor
  .changeset/tame-numbers-thank.md
  packages/utils/src/color.ts
Labels: review wanted, merge request

#2515 Added deprecated label
  docs/components/mdx/props-card.tsx
  docs/contents/components/data-display/list/props.ja.mdx
  docs/contents/components/data-display/list/props.mdx
  docs/contents/components/data-display/resizable/props.ja.mdx
  docs/contents/components/data-display/resizable/props.mdx
  docs/contents/components/data-display/stat/props.ja.mdx
  docs/contents/components/data-display/stat/props.mdx
  docs/contents/components/media-and-icons/fontawesome/props.ja.mdx
  docs/contents/components/media-and-icons/fontawesome/props.mdx
  docs/contents/components/media-and-icons/icon/props.ja.mdx
  docs/contents/components/media-and-icons/icon/props.mdx
  docs/contents/components/media-and-icons/image/props.ja.mdx
  docs/contents/components/media-and-icons/image/props.mdx
  docs/contents/components/media-and-icons/lucide/props.ja.mdx
  docs/contents/components/media-and-icons/lucide/props.mdx
  docs/contents/components/navigation/breadcrumb/props.ja.mdx
  docs/contents/components/navigation/breadcrumb/props.mdx
  docs/contents/components/navigation/stepper/props.ja.mdx
  docs/contents/components/navigation/stepper/props.mdx
  docs/i18n/ui.en.json
  docs/i18n/ui.ja.json
  docs/scripts/component/props.ts
  packages/components/breadcrumb/DOCS.json
  packages/components/fontawesome/DOCS.json
  packages/components/icon/DOCS.json
  packages/components/image/DOCS.json
  packages/components/list/DOCS.json
  packages/components/lucide/DOCS.json
  packages/components/resizable/DOCS.json
  packages/components/stat/DOCS.json
  packages/components/stepper/DOCS.json
  scripts/generate-docs.ts
Labels: review wanted, merge request

#2583 Add interpolation stories file
  stories/system/styles/interpolation.stories.tsx
Labels: merge request

#2539 Handle optional `theme.__config` in theme types
  .changeset/sweet-mangos-sleep.md
  packages/components/notice/src/notice.tsx
  packages/components/snacks/src/snacks.tsx
  packages/components/snacks/src/use-snacks.tsx
  packages/core/src/theme.types.ts
  packages/core/tests/breakpoint.test.ts
Labels: merge request

#2591 test: add header and footer tests for the Select component
  packages/components/select/tests/select.test.tsx
Labels: merge request

#2570 refactor: Deprecated props are being used in the Storybook Theme/LucidePage.
  stories/components/media-and-icons/lucide.stories.tsx
Labels: merge request

#2574 Fixed `whileHover` to `whileFocus`.
  docs/contents/getting-started/basics.ja.mdx
Labels: review wanted, merge request

#2584 Fixed YearPicker and MonthPicker display issues when no initial value is set
  .changeset/ten-spoons-judge.md
  packages/components/calendar/src/use-year-list.tsx
  packages/components/calendar/tests/month-picker.test.tsx
  packages/components/calendar/tests/year-picker.test.tsx
Labels: merge request

#2592 test: add header and footer tests for the Autocomplete component
  packages/components/autocomplete/tests/autocomplete.test.tsx
Labels: merge request

#2576 fixed `PieProps` type
  .changeset/twenty-cows-appear.md
  packages/components/charts/src/chart.types.ts
Labels: review wanted, merge request

#2577 Add calc utility for dynamic styles across system
  .changeset/calm-timers-clean.md
  .changeset/mighty-turtles-wink.md
  .changeset/new-readers-sit.md
  .changeset/thin-impalas-taste.md
  packages/components/carousel/src/carousel.tsx
  packages/components/layouts/src/grid.tsx
  packages/core/src/config/calc.ts
  packages/core/src/config/color-mix.ts
  packages/core/src/config/gradient.ts
  packages/core/src/config/index.ts
  packages/core/src/config/utils.ts
  packages/core/src/styles.ts
  packages/core/tests/config.test.ts
  scripts/generate-css/config.ts
  scripts/generate-css/index.ts
  scripts/generate-css/override-types.ts
  scripts/generate-css/resolve-types.ts
  scripts/generate-css/styles.ts
  scripts/generate-css/tokens.ts
  scripts/generate-css/transform-props.ts
  scripts/generate-css/ui-props.ts
  stories/system/styles/calc.stories.tsx
  stories/system/styles/min-max-clamp.stories.tsx
Labels: merge request

#2582 Fixed color parsing in color-mix function
  .changeset/tender-dogs-travel.md
  packages/core/src/config/color-mix.ts
  stories/system/styles/color-mix.stories.tsx
Labels: merge request

#2567 Add test for array values handling
  packages/theme-tools/tests/generate.test.ts
Labels: review wanted, merge request

#2573 Changed LucideIcon used as `ImageIcon` in docs.
  docs/components/mdx/editable-code-block.tsx
  docs/contents/components/forms/dropzone/index.ja.mdx
  docs/contents/components/forms/dropzone/index.mdx
Labels: review wanted, merge request

#2597 docs: Update MonthPicker default type description
  docs/contents/components/forms/month-picker/index.ja.mdx
  docs/contents/components/forms/month-picker/index.mdx
Labels: merge request

#2531 Added custom chart tooltip
  .changeset/perfect-hornets-march.md
  docs/i18n/ui.en.json
  docs/i18n/ui.ja.json
  docs/pages/insights/chart-tooltip.tsx
  docs/pages/insights/insights-header.tsx
  docs/pages/insights/insights-utils.ts
  docs/pages/insights/total-chart.tsx
  docs/pages/insights/user-chart.tsx
  packages/components/charts/src/chart.types.ts
  packages/components/charts/src/index.ts
Labels: review wanted, merge request

#2588 Added `tint`, `shade`, `transparentize` and `tone` CSS value functions
  .changeset/rude-baboons-taste.md
  packages/core/src/config/color-mix.ts
  stories/system/styles/color-mix.stories.tsx
Labels: review wanted, merge request

#2611 Update terminology in contribution guides
  CONTRIBUTING.ja.md
  CONTRIBUTING.md
  docs/contents/community/contributing.ja.mdx
  docs/contents/community/contributing.mdx
Labels: merge request

#2610 Updated GitHub token in release workflow
  .github/workflows/release.yml
Labels: merge request

#2612 Simplified `shouldForwardProp` logic
  .changeset/itchy-chefs-sniff.md
  packages/core/src/components/should-forward-prop.ts
Labels: merge request

#2616 Updated icon size properties to fontSize
  docs/pages/examples/mail/sidebar.tsx
  docs/pages/icons/icon-drawer.tsx
  docs/pages/icons/list.tsx
  docs/pages/icons/not-found.tsx
  packages/components/dropzone/src/dropzone.tsx
  packages/components/loading/tests/loading.test.tsx
  stories/components/data-display/infinite-scroll-area.stories.tsx
  stories/components/media-and-icons/avatar.stories.tsx
Labels: merge request

#2615 Updated package manager component logic
  docs/components/mdx/select-package-managers.tsx
  docs/contents/components/media-and-icons/fontawesome/index.ja.mdx
  docs/contents/components/media-and-icons/fontawesome/index.mdx
Labels: merge request

#2614 Optimize format handling logic
  .changeset/red-bugs-approve.md
  packages/components/color-picker/src/use-color-selector.ts
Labels: merge request

#2609 Updated filter handling in styles
  .changeset/stale-weeks-fry.md
  packages/core/src/styles.ts
  scripts/generate-css/transform-props.ts
Labels: merge request

#2596 fix: improve inefficient MenuButton's render
  .changeset/thirty-doors-wait.md
  packages/components/menu/src/menu-button.tsx
Labels: review wanted

#2622 Update value check to use `isNumeric` function
  .changeset/cool-years-begin.md
  .changeset/giant-wombats-shake.md
  packages/components/carousel/src/carousel.tsx
  packages/core/src/config/calc.ts
  packages/utils/src/assertion.ts
  packages/utils/tests/assertion.test.ts
  stories/system/styles/calc.stories.tsx
Labels: merge request

#2605 Updated trend calculation logic
  docs/pages/insights/insights-utils.ts
Labels: merge request

#2604 Corrected typo in ui.en.json file
  docs/i18n/ui.en.json
Labels: merge request

#2623 Simplified date manipulation logic
  docs/pages/insights/insights-header.tsx
Labels: merge request

#2613 Added exports and nativeImage component
  .changeset/light-experts-confess.md
  packages/components/image/src/index.ts
  packages/components/image/src/native-image.tsx
  stories/components/media-and-icons/native-image.stories.tsx
Labels: merge request

#2620 Updated component imports and props handling
  .changeset/healthy-pumas-film.md
  packages/nextjs/src/image.tsx
  packages/nextjs/src/index.ts
  packages/nextjs/src/link.tsx
Labels: merge request

#2598 test: add onKeyDown and onKeyUp tests
  packages/components/radio/tests/radio.test.tsx
Labels: review wanted, merge request

#2602 Fix required indicator
  .changeset/pink-yaks-visit.md
  packages/components/form-control/src/fieldset.tsx
  packages/components/form-control/src/form-control.tsx
  packages/components/form-control/tests/form-control.test.tsx
Labels: review wanted

#2628 Updated framer-motion version pinning
  packages/components/motion/package.json
  packages/core/package.json
  pnpm-lock.yaml
Labels: merge request

#2633 Remove 'size' from CarouselItem props
  docs/pages/examples/music/content.tsx
Labels: merge request

#2639 Rename hue to tone in code and docs
  docs/components/mdx/color-palettes.tsx
  docs/contents/styled-system/semantic-tokens.ja.mdx
  docs/contents/styled-system/semantic-tokens.mdx
  docs/contents/styled-system/theming/customize-theme.ja.mdx
  docs/contents/styled-system/theming/customize-theme.mdx
  docs/contents/styled-system/theming/default-theme.ja.mdx
  docs/contents/styled-system/theming/default-theme.mdx
  packages/utils/src/color.ts
  stories/components.tsx
Labels: merge request

#2640 Update CLI documentation content and structure
  docs/contents/styled-system/cli.ja.mdx
  docs/contents/styled-system/cli.mdx
Labels: merge request

#2636 Add row double click event handling guide
  docs/contents/components/data-display/table/index.ja.mdx
  docs/contents/components/data-display/table/index.mdx
Labels: merge request

#2645 Updated label
  docs/contents/styled-system/cli.ja.mdx
  docs/contents/styled-system/cli.mdx
Labels: merge request

#2637 Added `listProps` and `itemProps` definitions
  docs/contents/styled-system/configure/default-config.ja.mdx
  docs/contents/styled-system/configure/default-config.mdx
Labels: merge request

#2644 Update props types for Icon, Loading
  .changeset/six-cups-search.md
  packages/components/icon/src/icon.tsx
  packages/components/loading/src/loading.tsx
Labels: merge request

#2648 Update theme usage with `getVar` function
  .changeset/rude-walls-divide.md
  .changeset/strong-crabs-ring.md
  docs/pages/examples/music/header.tsx
  docs/pages/examples/playground/editor/prompt.tsx
  docs/pages/index.page.tsx
  packages/components/charts/src/area-chart-split.tsx
  packages/components/charts/src/use-area-chart.ts
  packages/components/charts/src/use-bar-chart.tsx
  packages/components/charts/src/use-chart-reference-line.ts
  packages/components/charts/src/use-line-chart.ts
  packages/components/charts/src/use-pie-chart.ts
  packages/components/charts/src/use-radar-chart.ts
  packages/components/color-picker/src/alpha-slider.tsx
  packages/components/color-picker/src/color-swatch.tsx
  packages/components/indicator/src/indicator.tsx
  packages/components/layouts/src/stack.tsx
  packages/components/slider/src/range-slider.tsx
  packages/components/slider/src/slider.tsx
  packages/components/snacks/src/snacks.tsx
  packages/components/stat/src/stat-icon.tsx
  packages/core/src/css/var.ts
  packages/theme/src/components/indicator.ts
  packages/theme/src/components/stat.ts
  stories/system/styles/variable.stories.tsx
Labels: merge request

#2635 Added `NativeImage` documentation
  docs/contents/components/media-and-icons/image/props.ja.mdx
  docs/contents/components/media-and-icons/image/props.mdx
  docs/contents/components/media-and-icons/native-image/index.ja.mdx
  docs/contents/components/media-and-icons/native-image/index.mdx
  docs/i18n/content.en.json
  docs/i18n/content.ja.json
  docs/scripts/component/props.ts
Labels: merge request

#2627 Adjusted the styling
  .changeset/thirty-mangos-applaud.md
  packages/cli/@types/cli-welcome.d.ts
  packages/cli/package.json
  packages/cli/src/command/theme/index.ts
  packages/cli/src/command/tokens/index.ts
  packages/cli/src/index.ts
  packages/cli/src/utils/cli.ts
  pnpm-lock.yaml
Labels: review wanted, merge request

#2638 Added close event customization details
  docs/contents/hooks/use-notice.ja.mdx
  docs/contents/hooks/use-notice.mdx
  docs/contents/hooks/use-snacks.ja.mdx
  docs/contents/hooks/use-snacks.mdx
  docs/contents/styled-system/notification.ja.mdx
  docs/contents/styled-system/notification.mdx
Labels: review wanted, merge request

#2649 Add label generation script and task
  docs/package.json
  docs/scripts/content/label.ts
  package.json
Labels: review wanted, merge request

#2652 Add documentation of header and footer for MultiSelect component
  docs/contents/components/forms/multi-select/index.ja.mdx
  docs/contents/components/forms/multi-select/index.mdx
Labels: merge request

#2654 Update Japanese translation and ordering
  docs/contents/components/other/motion/index.ja.mdx
  docs/contents/getting-started/basics.ja.mdx
  docs/contents/styled-system/animation.ja.mdx
  docs/contents/styled-system/animation.mdx
  docs/contents/styled-system/at-rules.ja.mdx
  docs/contents/styled-system/at-rules.mdx
  docs/contents/styled-system/cli.ja.mdx
  docs/contents/styled-system/cli.mdx
  docs/contents/styled-system/color-mode.ja.mdx
  docs/contents/styled-system/color-mode.mdx
  docs/contents/styled-system/css-custom-properties.ja.mdx
  docs/contents/styled-system/css-custom-properties.mdx
  docs/contents/styled-system/css-value-functions.ja.mdx
  docs/contents/styled-system/css-value-functions.mdx
  docs/contents/styled-system/global-styles.ja.mdx
  docs/contents/styled-system/global-styles.mdx
  docs/contents/styled-system/gradient.ja.mdx
  docs/contents/styled-system/gradient.mdx
  docs/contents/styled-system/interpolation.ja.mdx
  docs/contents/styled-system/interpolation.mdx
  docs/contents/styled-system/reset-styles.ja.mdx
  docs/contents/styled-system/reset-styles.mdx
  docs/contents/styled-system/responsive-styles.ja.mdx
  docs/contents/styled-system/responsive-styles.mdx
  docs/contents/styled-system/semantic-tokens.ja.mdx
  docs/contents/styled-system/semantic-tokens.mdx
  docs/contents/styled-system/text-and-layer-styles.ja.mdx
  docs/contents/styled-system/text-and-layer-styles.mdx
Labels: merge request

#2647 Simplified prop handling in loading component
  .changeset/quiet-plums-deny.md
  packages/components/loading/src/loading.tsx
  packages/theme/src/components/loading.ts
Labels: review wanted, merge request

#2656 Add radialChart documentation and props
  docs/contents/components/data-display/radial-chart/index.ja.mdx
  docs/contents/components/data-display/radial-chart/index.mdx
  docs/contents/components/data-display/radial-chart/props.ja.mdx
  docs/contents/components/data-display/radial-chart/props.mdx
  docs/contents/components/data-display/radial-chart/theming.ja.mdx
  docs/contents/components/data-display/radial-chart/theming.mdx
  docs/scripts/component/props.ts
  packages/components/charts/DOCS.json
Labels: merge request

#2655 Added header and footer in multi-autocomplete
  docs/contents/components/forms/multi-autocomplete/index.ja.mdx
  docs/contents/components/forms/multi-autocomplete/index.mdx
Labels: merge request

#2664 Added validation for invalid date strings
  docs/pages/insights/insights-utils.ts
Labels: merge request

#2650 docs: typo in description of `Toggle`
  docs/contents/components/forms/toggle/index.ja.mdx
  docs/contents/components/forms/toggle/index.mdx
  docs/contents/components/forms/toggle/props.ja.mdx
  docs/contents/components/forms/toggle/props.mdx
  docs/contents/components/forms/toggle/theming.ja.mdx
  docs/contents/components/forms/toggle/theming.mdx
Labels: merge request

#2663 Removed `changeset-release/docs` branch trigger
  .github/workflows/quality.yml
Labels: merge request

#2661 Updated radial chart endAngle in docs
  docs/contents/components/data-display/radial-chart/index.ja.mdx
  docs/contents/components/data-display/radial-chart/index.mdx
Labels: merge request

#2659 Update contributor list and props details
  docs/constant/contributors.ts
  docs/contents/components/data-display/radial-chart/props.ja.mdx
  docs/contents/components/data-display/radial-chart/props.mdx
  docs/contents/components/media-and-icons/image/props.ja.mdx
  docs/contents/components/media-and-icons/image/props.mdx
  docs/i18n/content.en.json
  docs/i18n/content.ja.json
Labels: merge request

#2651 test: add tests for modal placement
  packages/components/modal/tests/modal.test.tsx
Labels: merge request

#2681 Add emeriti category and update lists
  docs/components/mdx/users.tsx
  docs/constant/contributors.ts
  docs/constant/emeriti.ts
  docs/constant/index.ts
  docs/constant/maintainers.ts
  docs/constant/members.ts
  docs/contents/community/team.ja.mdx
  docs/contents/community/team.mdx
  docs/scripts/content/contributors.ts
Labels: merge request

#2676 Update element references and props across components
  .changeset/shiny-pianos-promise.md
  docs/components/forms/search.tsx
  docs/components/navigation/table-of-contents.tsx
  packages/components/checkbox/src/checkbox.tsx
  packages/components/loading/src/loading-provider.tsx
  packages/components/menu/src/menu-button.tsx
  packages/components/modal/src/drawer.tsx
  packages/components/modal/src/modal-overlay.tsx
  packages/components/modal/src/modal.tsx
  packages/components/motion/src/factory.ts
  packages/components/motion/src/index.ts
  packages/components/motion/src/motion.tsx
  packages/components/motion/src/motion.types.ts
  packages/components/motion/tests/motion.test.tsx
  packages/components/popover/src/popover-content.tsx
  packages/components/rating/src/rating-group.tsx
  packages/components/reorder/src/reorder-item.tsx
  packages/components/reorder/src/reorder.tsx
  packages/components/ripple/src/ripple.tsx
  packages/components/segmented-control/src/segmented-control.tsx
  packages/components/snacks/src/snacks.tsx
  packages/components/switch/src/switch.tsx
  packages/components/tabs/src/tab.tsx
  packages/components/tooltip/src/tooltip.tsx
  packages/components/transitions/src/collapse.tsx
  packages/components/transitions/src/fade.tsx
  packages/components/transitions/src/scale-fade.tsx
  packages/components/transitions/src/slide-fade.tsx
  packages/components/transitions/src/slide.tsx
  packages/core/src/components/component.types.ts
  packages/core/src/factory.ts
  packages/core/src/styled.ts
  packages/core/src/styles.ts
  packages/hooks/use-clickable/src/index.ts
  packages/next/src/image.tsx
  scripts/generate-css/exclude-props.ts
  stories/components/motion/variants.stories.tsx
Labels: review wanted, merge request

#2685 docs: add custom labels for DonutChart
  docs/contents/components/data-display/donut-chart/index.ja.mdx
  docs/contents/components/data-display/donut-chart/index.mdx
Labels: merge request

#2680 test: add tests for popover animation
  packages/components/popover/tests/popover.test.tsx
Labels: review wanted, merge request

#2679 docs: replace `Menu` with `Popover` in `Popover`
  docs/contents/components/overlay/popover/index.ja.mdx
  docs/contents/components/overlay/popover/index.mdx
Labels: review wanted, merge request

#2682 docs: Update text in non-hover element
  docs/contents/components/other/motion/index.ja.mdx
  docs/contents/components/other/motion/index.mdx
  docs/contents/styled-system/animation.ja.mdx
  docs/contents/styled-system/animation.mdx
Labels: review wanted, merge request
