Repository yamada-ui/yamada-ui, pull requests merged in 2024-10, with the labels that each got.

#3018 Fix component name in `@yamada-ui/autocomplete`
  .changeset/fluffy-jokes-behave.md
  packages/components/autocomplete/src/autocomplete-create.tsx
  packages/components/autocomplete/src/autocomplete-empty.tsx
  packages/components/autocomplete/src/autocomplete-option.tsx
Labels: merge request

#3027 fix: add `displayName` and `__ui__` in plop template
  plop/component/package-multi/src/{{dashCase packageName}}.tsx.hbs
  plop/component/package/src/{{dashCase packageName}}.tsx.hbs
Labels: merge request

#3029 Add `testing-library/no-wait-for-multiple-assertions` to ESLint rules
  .eslint/testing-library.ts
  packages/components/file-button/tests/file-button.test.tsx
  packages/components/pin-input/tests/pin-input.test.tsx
  packages/components/snacks/tests/snacks.test.tsx
  packages/components/table/tests/table.test.tsx
Labels: merge request

#3022 fix(number-input): add displayName and __ui__ properties to improve d…
  .changeset/neat-apricots-hammer.md
  packages/components/number-input/src/number-input.tsx
Labels: merge request

#3039 Optimized package build process in script
  scripts/dependency-build.ts
Labels: merge request

#3033 Set `displayName` and `__ui__` for `@yamada-ui/file-input`
  .changeset/many-horses-nail.md
  packages/components/file-input/src/file-input.tsx
Labels: merge request

#3031 fix: set the `displayName` and `__ui__` for `@yamada-ui/highlight`
  .changeset/mighty-elephants-own.md
  packages/components/highlight/src/highlight.tsx
Labels: merge request

#3030 fix: displayName is not set for the component of "@yamada-ui/pin-input"
  .changeset/tricky-rice-move.md
  packages/components/pin-input/src/pin-input.tsx
Labels: review wanted, merge request

#3025 fix: displayName is not set for the component of "@yamada-ui/progress"
  .changeset/three-taxis-sniff.md
  packages/components/progress/src/circle-progress.tsx
  packages/components/progress/src/progress.tsx
Labels: review wanted, merge request

#3020 Feat/set display name and UI for segmented control
  .changeset/honest-bulldogs-end.md
  packages/components/segmented-control/src/segmented-control.tsx
Labels: review wanted, merge request

#3004 Updated color scheme handling logic
  .changeset/honest-dogs-dream.md
  packages/components/carousel/src/carousel-control.tsx
  packages/core/src/components/use-component-style.tsx
  packages/core/src/css/css.types.ts
  scripts/generate-docs.ts
Labels: merge request

#2978 fix: set `displayname` and `__ui__`
  .changeset/chilled-pillows-argue.md
  packages/components/rating/src/rating-group.tsx
  packages/components/rating/src/rating-item.tsx
  packages/components/rating/src/rating.tsx
Labels: review wanted, merge request

#2963 fix: added displayName and __ui__ to tag components
  .changeset/polite-cobras-type.md
  packages/components/tag/src/tag.tsx
Labels: merge request

#3041 (create-yamada-app)gatsby template delete 404 page
  packages/create-yamada-app/src/templates/gatsby/src/pages/404.tsx
Labels: merge request

#3040 Updated contributor and member lists
  docs/constant/contributors.ts
  docs/constant/members.ts
Labels: merge request

#2981 Add displayName and __ui__ to Stepper component.
  .changeset/tiny-days-hammer.md
  packages/components/stepper/src/step-description.tsx
  packages/components/stepper/src/step-separator.tsx
  packages/components/stepper/src/step-status.tsx
  packages/components/stepper/src/step-title.tsx
  packages/components/stepper/src/step.tsx
  packages/components/stepper/src/stepper.tsx
Labels: review wanted, merge request

#3013 feat: className portal
  .changeset/poor-tips-act.md
  packages/components/portal/src/portal.tsx
Labels: merge request

#2835 Change throw Error to console.warn
  .changeset/hungry-parents-know.md
  packages/hooks/use-breakpoint/src/index.ts
  packages/hooks/use-breakpoint/tests/index.test.tsx
Labels: review wanted, merge request

#3032 Set `displayName` and `__ui__` for `@yamada-ui/charts`
  .changeset/hungry-cars-lay.md
  packages/components/charts/src/area-chart-gradient.tsx
  packages/components/charts/src/area-chart-split.tsx
  packages/components/charts/src/area-chart.tsx
  packages/components/charts/src/bar-chart.tsx
  packages/components/charts/src/chart-legend.tsx
  packages/components/charts/src/chart-tooltip.tsx
  packages/components/charts/src/donut-chart.tsx
  packages/components/charts/src/line-chart.tsx
  packages/components/charts/src/pie-chart.tsx
  packages/components/charts/src/radar-chart.tsx
  packages/components/charts/src/radial-chart.tsx
Labels: merge request

#2983 Remove deprecated `size` prop and cleanup
  .changeset/shaggy-houses-begin.md
  packages/components/progress/src/circle-progress.tsx
Labels: merge request

#3046 Rename close components to tag prefix
  .changeset/strong-llamas-remember.md
  packages/components/tag/src/tag.tsx
Labels: merge request

#3048 Updated component structure and naming
  .changeset/swift-gorillas-watch.md
  packages/components/progress/src/circle-progress.tsx
Labels: merge request

#3049 Updated dropzone component names
  .changeset/great-adults-push.md
  packages/components/dropzone/src/dropzone.tsx
Labels: merge request

#3055 refactor(color-picker): move JSDoc comments to component definitions
  .changeset/early-gorillas-lay.md
  packages/components/color-picker/src/hue-slider.tsx
  packages/components/color-picker/src/saturation-slider.tsx
Labels: merge request

#3056 feat(file-button): add displayName and __ui__ properties
  .changeset/mean-poems-turn.md
  packages/components/file-button/src/file-button.tsx
Labels: merge request

#3060 Reorganize imports and metadata
  plop/component/package-multi/src/{{dashCase packageName}}.tsx.hbs
  plop/component/package/src/{{dashCase packageName}}.tsx.hbs
  plop/component/storybook/{{dashCase packageName}}.stories.tsx.hbs
Labels: merge request

#3059 Add `Picture` component and related tests
  .changeset/heavy-trainers-tell.md
  packages/components/image/DOCS.json
  packages/components/image/src/index.ts
  packages/components/image/src/picture.tsx
  packages/components/image/tests/picture.test.tsx
  stories/components/media-and-icons/picture.stories.tsx
Labels: merge request

#3044 Added `memo` utility for components
  .changeset/happy-keys-sort.md
  packages/core/src/components/index.ts
  packages/core/src/components/memo.ts
Labels: review wanted, merge request

#3024 Fixed `index` of `Carousel`
  .changeset/silver-fireants-judge.md
  packages/components/carousel/src/use-carousel.ts
Labels: merge request

#3068 Simplified dependency and variable usage
  packages/components/snacks/package.json
  packages/components/snacks/src/snacks.tsx
  pnpm-lock.yaml
Labels: merge request

#3047 Updated icon component names
  .changeset/tricky-carpets-shout.md
  packages/components/rating/src/rating-item.tsx
Labels: merge request

#3066 Remove unused `useToken`, adjust padding logic
  docs/components/navigation/table-of-contents.tsx
Labels: merge request

#3069 Simplified condition in `createVar` function
  packages/core/src/css/var.ts
Labels: merge request

#3072 Fixed `Slider` and `RangeSlider` components
  .changeset/plenty-shoes-run.md
  .changeset/smart-rabbits-hide.md
  examples/next/pages/pages/index.tsx
  packages/components/slider/src/range-slider.tsx
  packages/components/slider/src/slider.tsx
Labels: merge request

#3021 fix: displayName is not set for the component of "@yamada-ui/pagination" #2889
  .changeset/dusty-roads-curve.md
  packages/components/pagination/src/pagination-icon.tsx
  packages/components/pagination/src/pagination-item.tsx
  packages/components/pagination/src/pagination.tsx
Labels: help wanted, merge request

#3057 fix(kbd): set the `displayName` and `__ui__` of the `Kbd` component
  .changeset/tough-dolphins-shave.md
  packages/components/kbd/src/kbd.tsx
Labels: review wanted, merge request

#3067 Updated package dependencies and code cleanup
  .changeset/kind-keys-tell.md
  packages/components/carousel/package.json
  packages/components/carousel/src/carousel-control.tsx
  packages/components/carousel/src/carousel-indicators.tsx
  packages/components/carousel/src/carousel-slide.tsx
  packages/components/carousel/src/carousel.tsx
  packages/components/carousel/src/use-carousel.ts
  pnpm-lock.yaml
Labels: merge request

#3077 Standardize prop definitions to interfaces
  docs/pages/examples/dashboard/header.tsx
  docs/pages/examples/dashboard/index.tsx
  docs/pages/examples/mail/detail.tsx
  docs/pages/examples/mail/header.tsx
  docs/pages/examples/mail/inbox.tsx
  docs/pages/examples/music/sidebar.tsx
Labels: merge request

#3079 Optimized imports and updated interfaces
  examples/create-react-app/src/components/layouts/header.tsx
  examples/hono/src/components/layouts/header.tsx
  examples/next/app/components/layouts/header.tsx
  examples/next/pages/components/layouts/header.tsx
  examples/remix/app/components/layouts/header.tsx
  examples/vite/src/components/layouts/header.tsx
Labels: merge request

#3078 Convert type aliases to interfaces
  packages/components/avatar/src/avatar.tsx
  packages/components/carousel/src/carousel.tsx
  packages/components/color-picker/src/color-picker.tsx
  packages/components/native-table/tests/native-table.test.tsx
  packages/components/rating/src/rating-item.tsx
  packages/components/select/src/option.tsx
  packages/components/stepper/src/use-stepper.ts
  packages/components/tabs/src/tabs-context.tsx
  packages/components/toggle/src/toggle-group.tsx
Labels: merge request

#3076 Updated hover and disabled styles
  packages/theme/src/components/checkbox.ts
  packages/theme/src/components/radio.ts
Labels: merge request

#3074 Set `displayName` and `__ui__` for `@yamada-ui/snacks`
  .changeset/unlucky-llamas-add.md
  packages/components/snacks/src/snacks.tsx
  packages/components/snacks/src/use-snacks.tsx
Labels: review wanted

#3063 feat(icon): add displayName and __ui__ properties
  .changeset/silly-starfishes-share.md
  packages/components/icon/src/icon.tsx
Labels: merge request

#3092 Fixed `allowInput` style
  .changeset/chilly-pens-end.md
  .changeset/fuzzy-apes-shake.md
  packages/components/calendar/src/date-picker.tsx
  packages/components/calendar/src/use-calendar-picker.ts
  packages/components/calendar/src/use-date-picker.ts
  packages/components/calendar/src/use-month-picker.ts
  packages/components/calendar/src/use-multi-date-picker.ts
  packages/components/calendar/src/use-range-date-picker.ts
  packages/components/calendar/src/use-year-picker.ts
  packages/components/color-picker/src/color-picker.tsx
  packages/components/color-picker/src/use-color-picker.ts
  packages/core/src/pseudos.ts
  packages/theme/src/components/color-picker.ts
  packages/theme/src/components/date-picker.ts
Labels: merge request

#3086 When the option `value` is not set, the value of `children` is automatically set
  .changeset/fluffy-avocados-mix.md
  packages/components/autocomplete/src/use-autocomplete-option.ts
  packages/components/select/src/use-select.ts
  stories/components/forms/select.stories.tsx
Labels: merge request

#3093 Update transition properties
  .changeset/sweet-deers-repair.md
  packages/theme/src/components/input.ts
Labels: merge request

#3112 Added keyboard and `rowHeader` support
  .changeset/chatty-rivers-hope.md
  .changeset/cyan-geckos-drive.md
  .changeset/friendly-lobsters-swim.md
  .changeset/giant-swans-wash.md
  .changeset/modern-clocks-flow.md
  cspell.json
  packages/components/table/package.json
  packages/components/table/src/paging-table-control.tsx
  packages/components/table/src/paging-table.tsx
  packages/components/table/src/table-checkbox.tsx
  packages/components/table/src/table-context.tsx
  packages/components/table/src/table-sort-button.tsx
  packages/components/table/src/table-utils.tsx
  packages/components/table/src/table.tsx
  packages/components/table/src/tbody.tsx
  packages/components/table/src/tfoot.tsx
  packages/components/table/src/thead.tsx
  packages/components/table/src/use-table.tsx
  packages/components/table/tests/table.test.tsx
  packages/theme/src/components/table.ts
  pnpm-lock.yaml
  stories/components/data-display/table.stories.tsx
Labels: merge request

#3104 fix(component): add displayname input
  .changeset/pink-coins-travel.md
  packages/components/input/src/input-addon.tsx
  packages/components/input/src/input-element.tsx
  packages/components/input/src/input-group.tsx
  packages/components/input/src/input.tsx
Labels: merge request

#3062 Add landscape and portrait media queries
  packages/core/src/pseudos.ts
  stories/system/styles/pseudo.stories.tsx
Labels: review wanted, merge request

#3117 Update type imports and interfaces
  .changeset/thick-horses-watch.md
  docs/components/mdx/package-managers.tsx
  packages/components/table/src/use-table.tsx
Labels: merge request

#3085 feat(docs): add accessibility section for FileInput component
  docs/contents/components/forms/file-input/accessibility.ja.mdx
  docs/contents/components/forms/file-input/accessibility.mdx
Labels: review wanted, merge request

#3114 Added `Picture` component documentation
  .changeset/new-horses-play.md
  docs/contents/components/media-and-icons/fontawesome/index.ja.mdx
  docs/contents/components/media-and-icons/fontawesome/index.mdx
  docs/contents/components/media-and-icons/icon/index.ja.mdx
  docs/contents/components/media-and-icons/icon/index.mdx
  docs/contents/components/media-and-icons/lucide/index.ja.mdx
  docs/contents/components/media-and-icons/lucide/index.mdx
  docs/contents/components/media-and-icons/picture/index.ja.mdx
  docs/contents/components/media-and-icons/picture/index.mdx
  docs/contents/components/media-and-icons/picture/props.ja.mdx
  docs/contents/components/media-and-icons/picture/props.mdx
  docs/contents/hooks/use-breakpoint-effect.ja.mdx
  docs/contents/hooks/use-breakpoint-state.ja.mdx
  docs/contents/hooks/use-breakpoint-value.ja.mdx
  docs/contents/hooks/use-breakpoint.ja.mdx
  docs/contents/hooks/use-update-breakpoint-effect.ja.mdx
  docs/contents/styled-system/theming/default-theme.ja.mdx
  docs/contents/styled-system/theming/default-theme.mdx
  docs/scripts/component/props.ts
  packages/components/image/src/picture.tsx
  stories/components/media-and-icons/picture.stories.tsx
Labels: merge request

#3125 Added `aria-roledescription` to components
  .changeset/neat-penguins-lick.md
  cspell.json
  packages/components/color-picker/src/use-saturation-slider.ts
Labels: merge request

#3124 Added `aria-hidden` to `AccordionIcon`
  .changeset/wise-planes-fix.md
  packages/components/accordion/src/accordion-item.tsx
  packages/components/accordion/src/accordion-label.tsx
Labels: merge request

#3139 Removed `"mono"` from SEMANTIC_COLOR_SCHEMES
  packages/utils/src/color.ts
Labels: merge request

#3141 Fixed undefined variant or size bug in styles
  .changeset/mean-monkeys-sell.md
  packages/core/src/components/use-component-style.tsx
Labels: merge request

#3134 Added accessibility attributes to modal
  .changeset/moody-shirts-eat.md
  cspell.json
  packages/components/modal/src/dialog-close-button.tsx
  packages/components/modal/src/drawer-content.tsx
  packages/components/modal/src/modal-body.tsx
  packages/components/modal/src/modal-close-button.tsx
  packages/components/modal/src/modal-content.tsx
  packages/components/modal/src/modal-context.ts
  packages/components/modal/src/modal-header.tsx
  packages/components/modal/src/modal-overlay.tsx
  packages/components/modal/src/modal.tsx
  packages/components/modal/tests/modal.test.tsx
Labels: merge request

#3146 displayName is not set for the component of "@yamada-ui/motion"
  .changeset/proud-lemons-beg.md
  packages/components/motion/src/motion.tsx
Labels: merge request

#3127 Added `useClickable` and updated props handling
  packages/components/file-input/package.json
  packages/components/file-input/src/file-input.tsx
  pnpm-lock.yaml
Labels: merge request

#3116 Added `closeButtonProps` to tag component
  .changeset/small-pears-complain.md
  packages/components/tag/src/tag.tsx
Labels: merge request

#3138 Centralize string manipulation functions
  .changeset/poor-gorillas-hug.md
  docs/scripts/component/props.ts
  docs/scripts/component/theme.ts
  docs/scripts/content/styled-system.ts
  docs/scripts/generate-icon-tags.ts
  docs/scripts/utils.ts
  docs/utils/github.ts
  docs/utils/object.ts
  docs/utils/string.ts
  packages/cli/src/command/theme/index.ts
  packages/cli/src/utils/index.ts
  packages/cli/src/utils/string.ts
  packages/theme/src/components/drawer.ts
  packages/utils/src/string.ts
  packages/utils/tests/string.test.ts
  scripts/a11y-issues.ts
  scripts/generate-css/index.ts
  scripts/generate-css/styles.ts
  scripts/utils.ts
Labels: review wanted, merge request

#3145 Fixed `aria-rowindex` for `Table`
  .changeset/khaki-swans-sniff.md
  .changeset/quiet-suits-rule.md
  packages/components/table/src/table-utils.tsx
  packages/components/table/src/tbody.tsx
  packages/components/table/src/tfoot.tsx
  packages/components/table/src/thead.tsx
  packages/theme/src/components/native-table.ts
Labels: merge request

#3153 Updated CloseButton accessibility docs
  docs/contents/components/other/close-button/accessibility.ja.mdx
  docs/contents/components/other/close-button/accessibility.mdx
Labels: merge request

#3159 Remove focus and cookieStorage modules
  packages/test/src/focus.ts
  packages/test/src/index.ts
  packages/test/src/mocks/cookie.ts
  packages/test/src/mocks/index.ts
  packages/test/src/utils.ts
  packages/utils/src/index.types.ts
Labels: merge request

#3143 Adjusted the styles of some components
  .changeset/brown-forks-turn.md
  .changeset/four-badgers-live.md
  .changeset/ninety-pans-unite.md
  packages/components/table/package.json
  packages/components/table/src/paging-table-control.tsx
  packages/theme/src/components/button.ts
  packages/theme/src/components/color-swatch.ts
  packages/theme/src/components/date-picker.ts
  packages/theme/src/components/input.ts
  packages/theme/src/components/native-select.ts
  packages/theme/src/components/pagination.ts
  packages/theme/src/components/segmented-control.ts
  packages/utils/src/string.ts
  packages/utils/tests/string.test.ts
  pnpm-lock.yaml
Labels: review wanted, merge request

#3164 fix(components): add display name for lucide
  .changeset/twenty-chefs-help.md
  packages/components/lucide/src/icon.tsx
Labels: merge request

#3163 chore: set displayName for infinite-scroll-area
  .changeset/strong-ducks-pay.md
  packages/components/infinite-scroll-area/src/infinite-scroll-area.tsx
Labels: merge request

#3160 refactor: add displayName for the component of `"@yamada-ui/list"`
  .changeset/pretty-rocks-fix.md
  packages/components/list/src/list.tsx
Labels: merge request

#3158 Excluded files that were tested unnecessarily.
  packages/components/tooltip/tests/tooltip.test.tsx
  vitest.config.mts
Labels: review wanted, merge request

#3154 Update index.ja.mdx
  docs/contents/components/data-display/infinite-scroll-area/index.ja.mdx
  docs/contents/components/data-display/infinite-scroll-area/index.mdx
Labels: merge request

#3173 Added accessibility info for Tag component
  docs/contents/components/data-display/tag/accessibility.ja.mdx
  docs/contents/components/data-display/tag/accessibility.mdx
Labels: merge request

#3171 Added 2xl size to button styles
  .changeset/tidy-starfishes-sort.md
  packages/theme/src/components/button.ts
Labels: merge request

#3172 Update button sizes and remove old styles
  docs/pages/index.page.tsx
  docs/theme/components/button.ts
  docs/theme/components/index.ts
Labels: merge request

#3128 Updated accessibility docs for `FileInput`
  docs/contents/components/forms/file-input/accessibility.ja.mdx
  docs/contents/components/forms/file-input/accessibility.mdx
Labels: merge request

#3191 Updated useRef type in component docs
  docs/contents/components/overlay/context-menu/index.ja.mdx
  docs/contents/components/overlay/context-menu/index.mdx
  docs/contents/components/overlay/menu/index.ja.mdx
  docs/contents/components/overlay/menu/index.mdx
Labels: merge request

#3179 Add OS detection to `useWindowEvent` hook
  stories/hooks/use-window-event.stories.tsx
Labels: review wanted, merge request

#3170 Added `useProcessing` custom hook
  .changeset/calm-cherries-greet.md
  packages/hooks/use-processing/README.md
  packages/hooks/use-processing/package.json
  packages/hooks/use-processing/src/index.ts
  packages/hooks/use-processing/tests/index.test.ts
  packages/hooks/use-processing/tsconfig.json
  packages/react/package.json
  packages/react/src/index.ts
  pnpm-lock.yaml
  stories/hooks/use-processing.stories.tsx
Labels: merge request

#3169 Added `usePromiseDisclosure` hook
  .changeset/fifty-seas-explain.md
  packages/hooks/use-disclosure/src/index.ts
  packages/hooks/use-disclosure/tests/index.test.ts
  stories/hooks/use-disclosure.stories.tsx
Labels: review wanted, merge request

#3202 Implemented forwardRef in loading components
  .changeset/large-lions-film.md
  .changeset/mean-pumas-smile.md
  packages/components/loading/src/loading-provider.tsx
  packages/core/src/theme.types.ts
Labels: merge request

#3204 Update various configurations and scripts
  .eslint/cspell.ts
  cspell.json
  docs/constant/contributors.ts
  docs/constant/emeriti.ts
  docs/constant/maintainers.ts
  docs/constant/members.ts
  docs/package.json
  docs/pages/api/github/observe/update-pull-requests.ts
  eslint.config.ts
  examples/create-react-app/package.json
  examples/hono/package.json
  examples/next/app/package.json
  examples/next/pages/package.json
  examples/remix/package.json
  examples/vite/package.json
  package.json
  packages/components/lucide/package.json
  packages/components/markdown/package.json
  packages/test/src/drag.ts
  packages/utils/src/react.tsx
  pnpm-lock.yaml
  scripts/a11y-issues.ts
  scripts/coverage-issues.ts
  scripts/create-issues.ts
  scripts/report-insights.ts
Labels: merge request

#3189 Enhanced accessibility, refactored code
  .changeset/sharp-geckos-sneeze.md
  packages/components/menu/src/menu-button.tsx
  packages/components/menu/src/menu-context.ts
  packages/components/menu/src/menu-group.tsx
  packages/components/menu/src/menu-item.tsx
  packages/components/menu/src/menu-list.tsx
  packages/components/menu/src/menu.tsx
  stories/components/overlay/menu.stories.tsx
Labels: review wanted, merge request

#3196 Updated aria attributes and props handling
  .changeset/spotty-clouds-kick.md
  packages/components/rating/src/use-rating-item.ts
  packages/components/rating/src/use-rating.tsx
  packages/components/rating/tests/rating.test.tsx
Labels: merge request

#3193 Update ref forwarding and prop types
  .changeset/few-carrots-compete.md
  .changeset/silver-spoons-compare.md
  packages/components/pagination/src/pagination-item.tsx
  packages/components/pagination/src/pagination.tsx
  packages/components/pagination/tests/pagination.test.tsx
  packages/theme/src/components/pagination.ts
Labels: merge request

#3236 fix: add displayName and __ui__ to layout components
  .changeset/soft-games-unite.md
  packages/components/layouts/src/aspect-ratio.tsx
  packages/components/layouts/src/box.tsx
  packages/components/layouts/src/center.tsx
  packages/components/layouts/src/container.tsx
  packages/components/layouts/src/divider.tsx
  packages/components/layouts/src/flex.tsx
  packages/components/layouts/src/grid.tsx
  packages/components/layouts/src/spacer.tsx
  packages/components/layouts/src/stack.tsx
Labels: merge request

#3147 fix(tabs): added necessary aria attributes to Tab and TabPanel component
  .changeset/forty-pets-serve.md
  .changeset/sharp-ties-tease.md
  packages/components/tabs/src/tab-list.tsx
  packages/components/tabs/src/tab-panel.tsx
  packages/components/tabs/src/tab-panels.tsx
  packages/components/tabs/src/tab.tsx
  packages/components/tabs/src/tabs-context.tsx
  packages/components/tabs/src/tabs.tsx
  packages/hooks/use-descendant/src/index.ts
Labels: review wanted

#3190 Enhance accessibility of autocomplete elements
  .changeset/funny-rivers-dream.md
  packages/components/autocomplete/src/autocomplete-create.tsx
  packages/components/autocomplete/src/autocomplete-empty.tsx
  packages/components/autocomplete/src/autocomplete-list.tsx
  packages/components/autocomplete/src/autocomplete-option-group.tsx
  packages/components/autocomplete/src/autocomplete-option.tsx
  packages/components/autocomplete/src/multi-autocomplete.tsx
  packages/components/autocomplete/src/use-autocomplete-list.ts
  packages/components/autocomplete/src/use-autocomplete-option-group.ts
  packages/components/autocomplete/src/use-autocomplete-option.ts
  packages/components/autocomplete/src/use-autocomplete.tsx
  packages/components/autocomplete/tests/multi-autocomplete.test.tsx
  packages/components/select/src/option-group.tsx
  packages/components/select/src/option.tsx
  packages/components/select/src/select-list.tsx
  packages/components/select/src/use-select-list.ts
  packages/components/select/src/use-select-option-group.ts
  packages/components/select/src/use-select-option.ts
  packages/components/select/src/use-select.tsx
Labels: review wanted, merge request

#3241 feat(reorder): add `displayName` to components related with `Reorder`
  .changeset/tame-ducks-clap.md
  packages/components/reorder/src/reorder-item.tsx
  packages/components/reorder/src/reorder-trigger.tsx
  packages/components/reorder/src/reorder.tsx
Labels: merge request

#3243 Added `Blockquote`, `Code` and `Em` components.
  .changeset/red-actors-melt.md
  .changeset/rude-gorillas-smash.md
  packages/components/typography/src/blockquote.tsx
  packages/components/typography/src/code.tsx
  packages/components/typography/src/em.tsx
  packages/components/typography/src/index.ts
  packages/components/typography/tests/typography.test.tsx
  packages/core/src/components/element.types.ts
  packages/core/src/generated-theme.types.ts
  packages/theme/src/components/blockquote.ts
  packages/theme/src/components/code.ts
  packages/theme/src/components/em.ts
  packages/theme/src/components/index.ts
  packages/theme/src/styles/reset-style.ts
  stories/components/typography/blockquote.stories.tsx
  stories/components/typography/code.stories.tsx
  stories/components/typography/em.stories.tsx
Labels: merge request

#3237 test(table): update coverages
  packages/components/table/tests/table.test.tsx
Labels: test, review wanted, merge request

#3247 Updated contributor and member lists
  docs/constant/contributors.ts
  docs/constant/members.ts
Labels: merge request

#3235 Remove unnecessary layout animation of `Switch` component
  .changeset/early-goats-hope.md
  packages/components/switch/src/switch.tsx
Labels: merge request

#3239 (create-yamada-app)next pages project specify the version in package.json as `workspace:*`
  packages/create-yamada-app/src/templates/next/pages/next.config.mjs
  packages/create-yamada-app/src/templates/next/pages/package.json
Labels: merge request

#3224 Added new variants `subtle` and `surface`
  .changeset/brave-camels-sniff.md
  .changeset/clean-dryers-beg.md
  .changeset/green-moose-roll.md
  .changeset/rich-kids-drop.md
  packages/components/alert/package.json
  packages/components/alert/src/alert.tsx
  packages/components/alert/tests/alert.test.tsx
  packages/components/progress/tests/progress.test.tsx
  packages/components/tabs/src/tab.tsx
  packages/theme/src/components/alert.ts
  packages/theme/src/components/badge.ts
  packages/theme/src/components/button.ts
  packages/theme/src/components/calendar.ts
  packages/theme/src/components/loading.ts
  packages/theme/src/components/pagination.ts
  packages/theme/src/components/progress.ts
  packages/theme/src/components/segmented-control.ts
  packages/theme/src/components/tabs.ts
  packages/theme/src/components/tag.ts
  packages/theme/src/components/toggle.ts
  packages/theme/src/tokens/colors.ts
  pnpm-lock.yaml
  stories/components/data-display/badge.stories.tsx
  stories/components/data-display/tag.stories.tsx
  stories/components/feedback/alert.stories.tsx
  stories/components/forms/button.stories.tsx
  stories/components/navigation/pagination.stories.tsx
Labels: review wanted, merge request

#3242 feat(menu): add `displayName` to components related with `Menu`
  .changeset/cuddly-buckets-guess.md
  packages/components/menu/src/context-menu-trigger.tsx
  packages/components/menu/src/context-menu.tsx
  packages/components/menu/src/menu-button.tsx
  packages/components/menu/src/menu-divider.tsx
  packages/components/menu/src/menu-group.tsx
  packages/components/menu/src/menu-item.tsx
  packages/components/menu/src/menu-list.tsx
  packages/components/menu/src/menu-option-group.tsx
  packages/components/menu/src/menu.tsx
Labels: merge request

#3245 Added `Bleed` and `Float` component
  .changeset/plenty-jeans-live.md
  packages/components/layouts/src/bleed.tsx
  packages/components/layouts/src/float.tsx
  packages/components/layouts/src/index.ts
  stories/components/layouts/bleed.stories.tsx
  stories/components/layouts/float.stories.tsx
Labels: merge request

#3178 Add `useAsyncCallback` hook
  .changeset/eighty-hornets-divide.md
  .changeset/good-actors-live.md
  .changeset/small-melons-yell.md
  .changeset/swift-horses-smile.md
  packages/components/loading/src/loading-provider.tsx
  packages/core/src/theme.types.ts
  packages/hooks/use-async-callback/README.md
  packages/hooks/use-async-callback/package.json
  packages/hooks/use-async-callback/src/index.ts
  packages/hooks/use-async-callback/tests/index.test.tsx
  packages/hooks/use-async-callback/tsconfig.json
  packages/react/package.json
  packages/react/src/index.ts
  packages/test/src/render.tsx
  pnpm-lock.yaml
  stories/hooks/use-async-callback.stories.tsx
Labels: review wanted, merge request

#3259 Added `useProcessing` hook documentation
  docs/contents/hooks/use-processing.ja.mdx
  docs/contents/hooks/use-processing.mdx
Labels: merge request

#3263 Added `Em` documentation
  docs/contents/components/typography/em/index.ja.mdx
  docs/contents/components/typography/em/index.mdx
  docs/contents/components/typography/em/theming.ja.mdx
  docs/contents/components/typography/em/theming.mdx
  docs/scripts/component/props.ts
Labels: merge request

#3264 Added `Code` documentation
  docs/contents/components/typography/code/index.ja.mdx
  docs/contents/components/typography/code/index.mdx
  docs/contents/components/typography/code/props.ja.mdx
  docs/contents/components/typography/code/props.mdx
  docs/contents/components/typography/code/theming.ja.mdx
  docs/contents/components/typography/code/theming.mdx
Labels: merge request

#3260 Added `useAsyncCallback` documentation
  docs/contents/hooks/use-async-callback.ja.mdx
  docs/contents/hooks/use-async-callback.mdx
Labels: merge request

#3265 Added `Blockquote` documentation
  docs/components/mdx/editable-code-block.tsx
  docs/contents/components/typography/blockquote/index.ja.mdx
  docs/contents/components/typography/blockquote/index.mdx
  docs/contents/components/typography/blockquote/props.ja.mdx
  docs/contents/components/typography/blockquote/props.mdx
  docs/contents/components/typography/blockquote/theming.ja.mdx
  docs/contents/components/typography/blockquote/theming.mdx
  docs/contents/components/typography/highlight/index.ja.mdx
  docs/contents/components/typography/highlight/index.mdx
Labels: merge request

#3258 Added `usePromiseDisclosure` documentation
  docs/contents/hooks/use-promise-disclosure.ja.mdx
  docs/contents/hooks/use-promise-disclosure.mdx
Labels: merge request

#3266 Added `Bleed` documentation
  docs/contents/components/layouts/bleed/index.ja.mdx
  docs/contents/components/layouts/bleed/index.mdx
  docs/contents/components/layouts/bleed/props.ja.mdx
  docs/contents/components/layouts/bleed/props.mdx
  docs/contents/components/layouts/divider/index.ja.mdx
  docs/contents/components/layouts/divider/index.mdx
Labels: merge request

#3254 test(flip): test cover for console warning in <Flip />
  packages/components/transitions/tests/flip.test.tsx
Labels: merge request

#3280 Added 'label: New' to useAsyncCallback docs
  docs/contents/hooks/use-async-callback.ja.mdx
  docs/contents/hooks/use-async-callback.mdx
Labels: merge request

#3278 Updated `Blockquote` component docs and usage
  docs/contents/components/typography/blockquote/index.mdx
Labels: merge request

#3285 docs(fileButton): use japanese translation on accessibility section
  docs/contents/components/forms/file-button/accessibility.ja.mdx
Labels: merge request

#3282 Removed conditional ripple disable logic
  .changeset/big-planes-admire.md
  packages/components/button/src/button.tsx
  packages/components/close-button/src/close-button.tsx
  packages/components/pagination/src/pagination-item.tsx
  packages/components/tabs/src/tab.tsx
  packages/components/toggle/src/toggle.tsx
Labels: merge request
