Repository yamada-ui/yamada-ui, pull requests merged in 2025-01, with the labels that each got.

#4259 `rating`: remove deprecated props
  packages/react/src/components/rating/rating.stories.tsx
  packages/react/src/components/rating/rating.test.tsx
  packages/react/src/components/rating/use-rating.tsx
Labels: merge request

#4272 Fixed render animation and updated dependencies
  .changeset/hungry-lies-visit.md
  .changeset/red-crabs-pull.md
  packages/components/motion/package.json
  packages/components/motion/src/motion.tsx
  packages/core/package.json
  pnpm-lock.yaml
Labels: merge request

#4260 `radio`: remove deprecated props
  packages/react/src/components/radio/radio-card.stories.tsx
  packages/react/src/components/radio/radio-card.tsx
  packages/react/src/components/radio/radio-group.test.tsx
  packages/react/src/components/radio/radio.stories.tsx
  packages/react/src/components/radio/radio.test.tsx
  packages/react/src/components/radio/radio.tsx
  packages/react/src/components/radio/use-radio-group.ts
  packages/react/src/components/radio/use-radio.ts
Labels: merge request

#4233 refactor: move styles to theme for form pagination
  packages/react/src/components/pagination/pagination-item.tsx
  packages/react/src/theme/components/pagination.ts
Labels: review wanted, merge request

#4249 refactor: move styles to theme for form pin-input
  packages/react/src/components/pin-input/pin-input.tsx
  packages/react/src/theme/components/pin-input.ts
Labels: merge request

#4261 `select`: remove deprecated props
  packages/react/src/components/select/multi-select.stories.tsx
  packages/react/src/components/select/multi-select.tsx
  packages/react/src/components/select/select.stories.tsx
  packages/react/src/components/select/select.test.tsx
  packages/react/src/components/select/use-select-option.ts
  packages/react/src/components/select/use-select.tsx
Labels: merge request

#4262 `slider`: remove deprecated props
  packages/react/src/components/slider/range-slider.stories.tsx
  packages/react/src/components/slider/range-slider.test.tsx
  packages/react/src/components/slider/range-slider.tsx
  packages/react/src/components/slider/slider.stories.tsx
  packages/react/src/components/slider/slider.test.tsx
  packages/react/src/components/slider/slider.tsx
Labels: merge request

#4263 `textarea`: remove deprecated props
  packages/react/src/components/textarea/textarea.stories.tsx
  packages/react/src/components/textarea/textarea.test.tsx
Labels: merge request

#4264 `highlight`: remove deprecated props
  packages/react/src/components/highlight/highlight.stories.tsx
  packages/react/src/components/highlight/highlight.test.tsx
  packages/react/src/components/highlight/highlight.tsx
Labels: merge request

#4266 `indicator`: remove deprecated props
  packages/react/src/components/indicator/indicator.stories.tsx
  packages/react/src/components/indicator/indicator.test.tsx
  packages/react/src/components/indicator/indicator.tsx
Labels: merge request

#4270 `link`: remove deprecated props
  packages/react/src/components/link/link-box.tsx
  packages/react/src/components/link/link.tsx
Labels: merge request

#4271 `menu`: remove deprecated props
  packages/react/src/components/menu/context-menu.stories.tsx
  packages/react/src/components/menu/menu-item.tsx
  packages/react/src/components/menu/menu.stories.tsx
  packages/react/src/components/menu/menu.test.tsx
Labels: merge request

#4280 `transitions`: remove deprecated props
  packages/react/src/components/transitions/airy.stories.tsx
  packages/react/src/components/transitions/airy.tsx
  packages/react/src/components/transitions/collapse.stories.tsx
  packages/react/src/components/transitions/collapse.test.tsx
  packages/react/src/components/transitions/collapse.tsx
  packages/react/src/components/transitions/fade.stories.tsx
  packages/react/src/components/transitions/fade.test.tsx
  packages/react/src/components/transitions/fade.tsx
  packages/react/src/components/transitions/flip.stories.tsx
  packages/react/src/components/transitions/flip.tsx
  packages/react/src/components/transitions/rotate.stories.tsx
  packages/react/src/components/transitions/rotate.tsx
  packages/react/src/components/transitions/scale-fade.stories.tsx
  packages/react/src/components/transitions/scale-fade.test.tsx
  packages/react/src/components/transitions/scale-fade.tsx
  packages/react/src/components/transitions/slide-fade.test.tsx
  packages/react/src/components/transitions/slide-fade.tsx
  packages/react/src/components/transitions/slide-fide.stories.tsx
  packages/react/src/components/transitions/slide.stories.tsx
  packages/react/src/components/transitions/slide.test.tsx
  packages/react/src/components/transitions/slide.tsx
Labels: merge request

#4282 `native-table`: removed deprecated props
  packages/react/src/components/native-table/native-table.stories.tsx
  packages/react/src/components/native-table/native-table.test.tsx
  packages/react/src/components/native-table/td.tsx
  packages/react/src/components/native-table/th.tsx
Labels: review wanted

#4283 `pagination`: removed deprecated props
  packages/react/src/components/pagination/pagination-item.tsx
  packages/react/src/components/pagination/pagination.stories.tsx
  packages/react/src/components/pagination/pagination.test.tsx
  packages/react/src/components/pagination/pagination.tsx
  packages/react/src/components/pagination/use-pagination.ts
Labels: merge request

#4284 `portal`: removed deprecated props
  packages/react/src/components/portal/portal.tsx
Labels: merge request

#4281 fix(native-select): removed deprecated props
  packages/react/src/components/native-select/native-select.stories.tsx
  packages/react/src/components/native-select/native-select.test.tsx
Labels: merge request

#4279 `<Drawer />`: `fullHeight` did not work
  .changeset/fifty-mugs-appear.md
  packages/components/modal/src/drawer.tsx
  packages/theme/src/components/drawer.ts
Labels: merge request

#4222 `color-picker`: removed deprecated props
  packages/react/src/components/color-picker/alpha-slider.stories.tsx
  packages/react/src/components/color-picker/color-picker.stories.tsx
  packages/react/src/components/color-picker/color-picker.test.tsx
  packages/react/src/components/color-picker/color-picker.tsx
  packages/react/src/components/color-picker/color-selector.stories.tsx
  packages/react/src/components/color-picker/color-swatch.tsx
  packages/react/src/components/color-picker/hue-slider.stories.tsx
  packages/react/src/components/color-picker/saturation-slider.stories.tsx
  packages/react/src/components/color-picker/use-color-picker.ts
  packages/react/src/components/color-picker/use-color-selector.ts
  packages/react/src/components/color-picker/use-color-slider.ts
  packages/react/src/components/color-picker/use-saturation-slider.ts
Labels: review wanted, merge request

#4256 `number-input`: remove deprecated props
  packages/react/src/components/number-input/number-input.stories.tsx
  packages/react/src/components/number-input/number-input.test.tsx
  packages/react/src/components/number-input/number-input.tsx
Labels: review wanted, merge request

#4221 refactor: move styles to theme for form menu
  packages/react/src/components/menu/menu-button.tsx
  packages/react/src/components/menu/menu-item.tsx
  packages/react/src/theme/components/menu.ts
Labels: review wanted

#4277 `modal`: remove deprecated props
  packages/react/src/components/modal/dialog.stories.tsx
  packages/react/src/components/modal/dialog.test.tsx
  packages/react/src/components/modal/drawer-content.tsx
  packages/react/src/components/modal/drawer.stories.tsx
  packages/react/src/components/modal/drawer.test.tsx
  packages/react/src/components/modal/drawer.tsx
  packages/react/src/components/modal/modal.stories.tsx
  packages/react/src/components/modal/modal.test.tsx
  packages/react/src/components/modal/modal.tsx
  packages/react/src/theme/components/drawer.ts
Labels: review wanted

#4267 `infinite-scroll-area`, `use-infinite-scroll`: remove props
  packages/react/src/components/infinite-scroll-area/infinite-scroll-area.tsx
  packages/react/src/hooks/use-infinite-scroll/index.stories.tsx
  packages/react/src/hooks/use-infinite-scroll/index.ts
Labels: review wanted

#4202 Test/enhance test coverage for radio
  packages/components/radio/tests/radio-card.test.tsx
Labels: review wanted

#4276 Replaced Icon in `Pagination`
  packages/react/src/components/pagination/pagination-icon.tsx
  packages/react/src/components/pagination/pagination-item.tsx
Labels: merge request

#4274 fix: replace `CheckIcon` in `Stepper`
  packages/react/src/components/stepper/step-status.tsx
Labels: review wanted, merge request

#4231 remove `ResizableTriggerIcon`
  packages/react/src/components/resizable/index.ts
  packages/react/src/components/resizable/resizable-trigger.tsx
  packages/react/src/components/resizable/resizable.test.tsx
Labels: review wanted

#4243 replaced `lucide-icon` in `password-input`
  packages/react/src/components/password-input/password-input-icon.tsx
  packages/react/src/components/password-input/password-input.test.tsx
  packages/react/src/components/password-input/password-input.tsx
Labels: review wanted, merge request

#4291 Updated callback return type
  .changeset/pink-onions-move.md
  packages/hooks/use-async-callback/src/index.ts
Labels: merge request

#4273 Replace `CheckIcon` in `Select`
  packages/react/src/components/select/option.tsx
Labels: review wanted

#4275 Replace to `ChevronsUpDownIcon` in `Table`
  packages/react/src/components/table/table-sort-button.tsx
Labels: merge request

#4292 Updated form control prop handling in UI components
  .changeset/rich-stingrays-fetch.md
  packages/components/checkbox/src/checkbox-card-group.tsx
  packages/components/checkbox/src/checkbox-group.tsx
  packages/components/radio/src/radio-card-group.tsx
  packages/components/radio/src/radio-group.tsx
Labels: merge request

#4295 `motion`: remove deprecated props
  packages/react/src/components/motion/animation.stories.tsx
  packages/react/src/components/motion/motion.types.ts
  packages/react/src/components/motion/utils.stories.tsx
Labels: merge request

#4294 `reorder`: rename internal variables
  packages/react/src/components/reorder/reorder-context.ts
  packages/react/src/components/reorder/reorder-item.tsx
  packages/react/src/components/reorder/reorder-trigger.tsx
  packages/react/src/components/reorder/reorder.tsx
Labels: merge request

#4296 `popover`: remove deprecated props
  packages/react/src/components/autocomplete/use-autocomplete.tsx
  packages/react/src/components/popover/popover.stories.tsx
  packages/react/src/components/popover/popover.tsx
Labels: review wanted

#4316 fix(accordion): correct rotation transformation for expanded state
  packages/react/src/components/accordion/accordion.style.ts
Labels: merge request

#4321 fix(table): added HeaderContext and TableMeta types to export
  .changeset/famous-dolls-smoke.md
  packages/components/table/src/index.ts
  packages/components/table/src/use-table.tsx
Labels: review wanted

#4323 Updated fallback image URLs in documentation
  docs/contents/components/media-and-icons/image/index.ja.mdx
  docs/contents/components/media-and-icons/image/index.mdx
  stories/components/media-and-icons/image.stories.tsx
Labels: merge request

#4298 fix: replaced `DatePickerIcon`
  packages/react/src/components/calendar/date-picker.tsx
Labels: merge request

#4255 refactor: move styles to theme for calendar
  packages/react/src/components/calendar/calendar-header.tsx
  packages/react/src/theme/components/calendar.ts
Labels: review wanted

#4326 Removed unused `ComponentArgs` properties
  .changeset/chilly-bears-leave.md
  packages/core/src/components/component.types.ts
Labels: merge request

#4411 docs(highlight): replace with new props
  docs/contents/components/typography/highlight/index.ja.mdx
  docs/contents/components/typography/highlight/index.mdx
Labels: merge request

#4418 docs(input): replace with new props
  docs/contents/components/forms/input/index.ja.mdx
  docs/contents/components/forms/input/index.mdx
Labels: merge request

#4419 docs(number-input): replace with new props
  docs/contents/components/forms/number-input/index.ja.mdx
  docs/contents/components/forms/number-input/index.mdx
Labels: merge request

#4412 docs(form-control): replace with new props
  docs/contents/components/forms/form-control/index.ja.mdx
  docs/contents/components/forms/form-control/index.mdx
Labels: merge request

#4413 docs(fieldset): replace with new props
  docs/contents/components/forms/fieldset/index.ja.mdx
  docs/contents/components/forms/fieldset/index.mdx
Labels: merge request

#4427 docs(radio-card): replace with new props
  docs/contents/components/forms/radio-card/index.ja.mdx
  docs/contents/components/forms/radio-card/index.mdx
Labels: merge request
