Repository yamada-ui/yamada-ui, pull requests merged in 2025-05, with the labels that each got.

#4642 Corrected component case in documentation
  docs/contents/components/data-display/list/index.ja.mdx
  docs/contents/components/data-display/list/index.mdx
Labels: merge request

#4643 Simplified Float component props usage
  docs/contents/components/layouts/float/index.ja.mdx
  docs/contents/components/layouts/float/index.mdx
Labels: merge request

#4644 Updated dependency versions
  .changeset/shaggy-walls-yell.md
  docs/package.json
  package.json
  packages/components/icon/tests/icon.test.tsx
  packages/components/motion/src/index.ts
  packages/components/motion/src/motion.types.ts
  packages/components/scroll-area/tests/scroll-area.test.tsx
  packages/components/slider/src/range-slider.tsx
  pnpm-lock.yaml
Labels: merge request

#4314 Update reset css
  packages/react/src/theme/styles/reset-style.ts
Labels: review wanted

#4556 Refactored `PasswordInput` component
  packages/react/src/components/group/group.style.ts
  packages/react/src/components/group/group.tsx
  packages/react/src/components/group/index.ts
  packages/react/src/components/group/use-group.ts
  packages/react/src/components/input/input-group.tsx
  packages/react/src/components/input/input.style.ts
  packages/react/src/components/password-input/index.ts
  packages/react/src/components/password-input/password-input.stories.tsx
  packages/react/src/components/password-input/password-input.style.ts
  packages/react/src/components/password-input/password-input.test.tsx
  packages/react/src/components/password-input/password-input.tsx
  packages/react/src/components/password-input/strength-meter.style.ts
  packages/react/src/components/password-input/strength-meter.tsx
  packages/react/src/components/password-input/use-password-input.tsx
  packages/react/src/components/password-input/use-strength-meter.ts
  packages/react/src/core/pseudos.ts
  packages/react/src/index.ts
  packages/react/src/legacy-components/password-input/index.ts
  packages/react/src/legacy-components/password-input/password-input-context.ts
  packages/react/src/legacy-components/password-input/password-input-icon.tsx
  packages/react/src/legacy-components/password-input/password-input-strength-meter.tsx
  packages/react/src/legacy-components/password-input/password-input.stories.tsx
  packages/react/src/legacy-components/password-input/password-input.test.tsx
  packages/react/src/legacy-components/password-input/password-input.tsx
  packages/react/src/legacy-components/password-input/use-password-input.tsx
  packages/react/src/theme/components/password-input.ts
  packages/utils/src/object.ts
Labels: review wanted

#4655 test(Resizable): enable rendering test and add aria attributes to Trigger
  packages/react/src/components/resizable/resizable.test.tsx
Labels: test, merge request

#4649 Refactored `Indicator` component
  packages/react/src/components/bleed/bleed.tsx
  packages/react/src/components/color-swatch/color-swatch.tsx
  packages/react/src/components/file-input/file-input.tsx
  packages/react/src/components/float/float.stories.tsx
  packages/react/src/components/float/float.tsx
  packages/react/src/components/indicator/index.ts
  packages/react/src/components/indicator/indicator.stories.tsx
  packages/react/src/components/indicator/indicator.style.ts
  packages/react/src/components/indicator/indicator.test.tsx
  packages/react/src/components/indicator/indicator.tsx
  packages/react/src/components/loading/oval.tsx
  packages/react/src/components/number-input/number-input.tsx
  packages/react/src/components/password-input/password-input.tsx
  packages/react/src/components/skeleton/skeleton.tsx
  packages/react/src/components/tag/tag.style.ts
  packages/react/src/components/textarea/textarea.tsx
  packages/react/src/core/components/create-component.tsx
  packages/react/src/core/config/focus-ring.ts
  packages/react/src/core/css/index.types.ts
  packages/react/src/core/css/var.ts
  packages/react/src/core/styles.ts
  packages/react/src/index.ts
  packages/react/src/legacy-components/indicator/index.ts
  packages/react/src/legacy-components/indicator/indicator.stories.tsx
  packages/react/src/legacy-components/indicator/indicator.test.tsx
  packages/react/src/legacy-components/indicator/indicator.tsx
  packages/react/src/theme/components/indicator.ts
  packages/react/src/theme/tokens/keyframes.ts
  scripts/generate-styles/styled-props.ts
Labels: review wanted

#4659 Refactored `NativeSelect` component
  packages/react/src/components/breadcrumb/breadcrumb.stories.tsx
  packages/react/src/components/editable/editable.stories.tsx
  packages/react/src/components/field/use-field-props.ts
  packages/react/src/components/file-input/file-input.stories.tsx
  packages/react/src/components/file-input/file-input.style.ts
  packages/react/src/components/input/input.stories.tsx
  packages/react/src/components/input/input.style.ts
  packages/react/src/components/native-select/index.ts
  packages/react/src/components/native-select/namespace.ts
  packages/react/src/components/native-select/native-select.stories.tsx
  packages/react/src/components/native-select/native-select.style.ts
  packages/react/src/components/native-select/native-select.test.tsx
  packages/react/src/components/native-select/native-select.tsx
  packages/react/src/components/number-input/number-input.stories.tsx
  packages/react/src/components/number-input/number-input.style.ts
  packages/react/src/components/password-input/password-input.stories.tsx
  packages/react/src/components/password-input/password-input.style.ts
  packages/react/src/components/textarea/textarea.stories.tsx
  packages/react/src/components/textarea/textarea.style.ts
  packages/react/src/core/components/use-component-style.ts
  packages/react/src/core/css/index.types.ts
  packages/react/src/core/theme/index.types.ts
  packages/react/src/index.ts
  packages/react/src/legacy-components/native-select/index.ts
  packages/react/src/legacy-components/native-select/native-select.stories.tsx
  packages/react/src/legacy-components/native-select/native-select.test.tsx
  packages/react/src/legacy-components/native-select/native-select.tsx
  packages/react/src/theme/components/native-select.ts
Labels: review wanted

#4652 Refactored `PinInput` component
  packages/react/src/components/button/button-group.tsx
  packages/react/src/components/field/field.tsx
  packages/react/src/components/field/use-field-props.ts
  packages/react/src/components/input/input-group.tsx
  packages/react/src/components/native-select/namespace.ts
  packages/react/src/components/pin-input/index.ts
  packages/react/src/components/pin-input/namespace.ts
  packages/react/src/components/pin-input/pin-input.stories.tsx
  packages/react/src/components/pin-input/pin-input.style.ts
  packages/react/src/components/pin-input/pin-input.test.tsx
  packages/react/src/components/pin-input/pin-input.tsx
  packages/react/src/components/pin-input/use-pin-input.ts
  packages/react/src/components/toggle/toggle-group.tsx
  packages/react/src/index.ts
  packages/react/src/legacy-components/pin-input/index.ts
  packages/react/src/legacy-components/pin-input/pin-input-field.test.tsx
  packages/react/src/legacy-components/pin-input/pin-input.stories.tsx
  packages/react/src/legacy-components/pin-input/pin-input.tsx
  packages/react/src/theme/components/pin-input.ts
  packages/react/src/utils/dom.ts
Labels: review wanted
