Repository yamada-ui/yamada-ui, pull requests merged in 2025-02, with the labels that each got.

#4431 Refactored `Code` component
  packages/react/src/components/code/code.stories.tsx
  packages/react/src/components/code/code.style.ts
  packages/react/src/components/code/code.test.tsx
  packages/react/src/components/code/code.tsx
  packages/react/src/components/code/index.ts
  packages/react/src/index.ts
  packages/react/src/legacy-components/code/code.tsx
  packages/react/src/legacy-components/code/index.ts
  packages/react/src/theme/components/code.ts
Labels: merge request

#4430 Refactored `Em` component
  packages/react/src/components/em/em.stories.tsx
  packages/react/src/components/em/em.style.ts
  packages/react/src/components/em/em.test.tsx
  packages/react/src/components/em/em.tsx
  packages/react/src/components/em/index.ts
  packages/react/src/index.ts
  packages/react/src/legacy-components/em/em.tsx
  packages/react/src/legacy-components/em/index.ts
  packages/react/src/theme/components/em.ts
Labels: review wanted

#4425 docs(textarea): replace with new props
  docs/contents/components/forms/textarea/index.ja.mdx
  docs/contents/components/forms/textarea/index.mdx
Labels: merge request

#4404 refactor: move styles to theme for year picker
  packages/react/src/legacy-components/calendar/year-picker.tsx
  packages/react/src/theme/components/year-picker.ts
Labels: review wanted, merge request

#4405 refactor: move styles to theme for multi date picker
  packages/react/src/legacy-components/calendar/multi-date-picker.tsx
  packages/react/src/theme/components/multi-date-picker.ts
Labels: review wanted, merge request

#4407 refactor: move styles to theme for color selector
  packages/react/src/legacy-components/color-picker/color-selector.tsx
  packages/react/src/theme/components/color-selector.ts
Labels: review wanted, merge request

#4426 docs(radio): replace with new props
  docs/contents/components/forms/radio/index.ja.mdx
  docs/contents/components/forms/radio/index.mdx
Labels: review wanted, merge request

#4424 docs(pin-input): replace with new props
  docs/contents/components/forms/pin-input/index.ja.mdx
  docs/contents/components/forms/pin-input/index.mdx
Labels: merge request

#4423 docs(password-input): replace with new props
  docs/contents/components/forms/password-input/index.ja.mdx
  docs/contents/components/forms/password-input/index.mdx
Labels: merge request

#4417 docs(icon-button): replace with new props
  docs/contents/components/forms/icon-button/index.ja.mdx
  docs/contents/components/forms/icon-button/index.mdx
Labels: review wanted, merge request

#4433 docs(checkbox): replace with new props
  docs/contents/components/forms/checkbox/index.ja.mdx
  docs/contents/components/forms/checkbox/index.mdx
Labels: merge request

#4442 docs(toggle): replace with new props
  docs/contents/components/forms/toggle/index.ja.mdx
  docs/contents/components/forms/toggle/index.mdx
Labels: merge request

#4440 docs(checkbox-card): replace with new props
  docs/contents/components/forms/checkbox-card/index.ja.mdx
  docs/contents/components/forms/checkbox-card/index.mdx
Labels: merge request

#4441 docs(switch): replace with new props
  docs/contents/components/forms/switch/index.ja.mdx
  docs/contents/components/forms/switch/index.mdx
Labels: merge request

#4436 Refactored `Status` component
  packages/react/src/components/status/index.ts
  packages/react/src/components/status/status.stories.tsx
  packages/react/src/components/status/status.style.ts
  packages/react/src/components/status/status.test.tsx
  packages/react/src/components/status/status.tsx
  packages/react/src/index.ts
  packages/react/src/legacy-components/status/index.ts
  packages/react/src/legacy-components/status/status.tsx
Labels: merge request

#4429 Refactored `DataList` component
  packages/react/src/components/data-list/data-list.stories.tsx
  packages/react/src/components/data-list/data-list.style.ts
  packages/react/src/components/data-list/data-list.test.tsx
  packages/react/src/components/data-list/data-list.tsx
  packages/react/src/components/data-list/index.ts
  packages/react/src/components/data-list/namespace.ts
  packages/react/src/components/data-list/use-data-list.ts
  packages/react/src/index.ts
  packages/react/src/legacy-components/data-list/data-list.stories.tsx
  packages/react/src/legacy-components/data-list/data-list.tsx
  packages/react/src/legacy-components/data-list/index.ts
Labels: review wanted, merge request

#4456 docs(month-picker): replace with new props
  docs/contents/components/forms/month-picker/index.ja.mdx
  docs/contents/components/forms/month-picker/index.mdx
Labels: merge request

#4455 docs(range-date-picker): replace with new props
  docs/contents/components/forms/range-date-picker/index.ja.mdx
  docs/contents/components/forms/range-date-picker/index.mdx
Labels: merge request

#4457 docs(year-picker): replace with new props
  docs/contents/components/forms/year-picker/index.ja.mdx
  docs/contents/components/forms/year-picker/index.mdx
Labels: review wanted

#4458 docs(color-picker): replace with new props
  docs/contents/components/forms/color-picker/index.ja.mdx
  docs/contents/components/forms/color-picker/index.mdx
Labels: merge request

#4452 docs(multi-autocomplete): replace with new props
  docs/contents/components/forms/multi-autocomplete/index.ja.mdx
  docs/contents/components/forms/multi-autocomplete/index.mdx
Labels: review wanted

#4473 test(accordion): add tests for displayName, className, and HTML tag r…
  packages/react/src/components/accordion/accordion.test.tsx
  packages/react/src/components/accordion/use-accordion.ts
Labels: review wanted

#4474 test: fix failing tests for collapse component
  packages/react/src/components/collapse/collapse.test.tsx
Labels: merge request

#4493 docs(button): replace with new props
  docs/contents/components/forms/button/index.ja.mdx
  docs/contents/components/forms/button/index.mdx
Labels: merge request

#4477 Refactored `Textarea` component
  packages/react/src/components/textarea/index.ts
  packages/react/src/components/textarea/textarea.stories.tsx
  packages/react/src/components/textarea/textarea.style.ts
  packages/react/src/components/textarea/textarea.test.tsx
  packages/react/src/components/textarea/textarea.tsx
  packages/react/src/components/textarea/use-autosize.test.tsx
  packages/react/src/components/textarea/use-autosize.ts
  packages/react/src/components/textarea/use-textarea.ts
  packages/react/src/index.ts
  packages/react/src/legacy-components/textarea/index.ts
  packages/react/src/legacy-components/textarea/textarea.tsx
  packages/react/src/theme/components/textarea.ts
Labels: review wanted

#4325 Rebuild generate-styles
  cspell.json
  package.json
  packages/react/src/components/textarea/use-autosize.test.tsx
  packages/react/src/components/textarea/use-autosize.ts
  packages/react/src/components/textarea/use-textarea.ts
  packages/react/src/core/config/animation.ts
  packages/react/src/core/config/at-rule.stories.tsx
  packages/react/src/core/config/index.ts
  packages/react/src/core/css/css.stories.tsx
  packages/react/src/core/css/css.ts
  packages/react/src/core/css/use-css.stories.tsx
  packages/react/src/core/pseudos.ts
  packages/react/src/core/styled.tsx
  packages/react/src/core/styles.ts
  packages/react/src/hooks/use-animation/index.stories.tsx
  packages/react/src/hooks/use-hover/index.stories.tsx
  packages/react/src/providers/ui-provider/ui-provider.tsx
  pnpm-lock.yaml
  scripts/generate-styles/check.ts
  scripts/generate-styles/config.ts
  scripts/generate-styles/index.ts
  scripts/generate-styles/layout-props.ts
  scripts/generate-styles/override-types.ts
  scripts/generate-styles/styles.ts
  scripts/generate-styles/ui-props.ts
Labels: review wanted

#4494 Update packages and dependencies
  .changeset/deep-peas-hang.md
  docs/package.json
  examples/create-react-app/package.json
  examples/hono/package.json
  examples/next/app/package.json
  examples/next/pages/package.json
  examples/remix/package.json
  examples/vite/package.json
  package.json
  packages/cli/package.json
  packages/components/autocomplete/tests/autocomplete.test.tsx
  packages/components/carousel/package.json
  packages/components/charts/package.json
  packages/components/color-picker/tests/alpha-slider.test.tsx
  packages/components/color-picker/tests/saturation-slider.test.tsx
  packages/components/focus-lock/package.json
  packages/components/fontawesome/package.json
  packages/components/loading/package.json
  packages/components/lucide/package.json
  packages/components/lucide/src/icons/battery-plus.tsx
  packages/components/lucide/src/icons/circle-small.tsx
  packages/components/lucide/src/icons/droplet-off.tsx
  packages/components/lucide/src/icons/house-wifi.tsx
  packages/components/lucide/src/icons/index.ts
  packages/components/lucide/src/icons/index.types.ts
  packages/components/lucide/src/icons/list-filter-plus.tsx
  packages/components/lucide/src/icons/map-plus.tsx
  packages/components/lucide/src/icons/mars-stroke.tsx
  packages/components/lucide/src/icons/mars.tsx
  packages/components/lucide/src/icons/non-binary.tsx
  packages/components/lucide/src/icons/scan-heart.tsx
  packages/components/lucide/src/icons/transgender.tsx
  packages/components/lucide/src/icons/triangle-dashed.tsx
  packages/components/lucide/src/icons/venus-and-mars.tsx
  packages/components/lucide/src/icons/venus.tsx
  packages/components/lucide/src/icons/waves-ladder.tsx
  packages/components/markdown/package.json
  packages/components/modal/package.json
  packages/components/motion/package.json
  packages/components/motion/src/motion.types.ts
  packages/components/reorder/tests/reorder.test.tsx
  packages/components/table/package.json
  packages/core/package.json
  packages/hooks/use-focus-visible/src/index.ts
  packages/hooks/use-pan-event/tests/index.test.tsx
  packages/next/package.json
  packages/test/package.json
  packages/theme/src/components/native-table.ts
  packages/utils/src/event.ts
  pnpm-lock.yaml
Labels: merge request

#4500 test(button): add tests for displayName, className, and HTML tag rend…
  packages/react/src/components/button/button-group.test.tsx
  packages/react/src/components/button/button-group.tsx
  packages/react/src/components/button/button.test.tsx
  packages/react/src/components/button/close-button.test.tsx
  packages/react/src/components/button/icon-button.test.tsx
Labels: review wanted

#4501 test(card): add tests for displayName, className, and HTML tag rendering
  packages/react/src/components/card/card.test.tsx
Labels: review wanted

#4518 docs(tag): replace with new props
  docs/contents/components/data-display/tag/index.ja.mdx
  docs/contents/components/data-display/tag/index.mdx
Labels: merge request

#4528 docs(breadcrumb): replace with new props
  docs/contents/components/navigation/breadcrumb/index.ja.mdx
  docs/contents/components/navigation/breadcrumb/index.mdx
Labels: merge request

#4527 docs(link-box): replace with new props
  docs/contents/components/navigation/link-box/index.ja.mdx
  docs/contents/components/navigation/link-box/index.mdx
Labels: merge request

#4525 docs(infinite-scroll-area): replace with new props
  docs/contents/components/data-display/infinite-scroll-area/index.ja.mdx
  docs/contents/components/data-display/infinite-scroll-area/index.mdx
Labels: merge request

#4287 Enhance test coverage for carousel
  packages/components/carousel/tests/carousel.test.tsx
Labels: help wanted, review wanted

#4548 transitions(airy, collapse, fade): replace with new props
  docs/contents/components/transitions/airy/index.ja.mdx
  docs/contents/components/transitions/airy/index.mdx
  docs/contents/components/transitions/collapse/index.ja.mdx
  docs/contents/components/transitions/collapse/index.mdx
  docs/contents/components/transitions/fade/index.ja.mdx
  docs/contents/components/transitions/fade/index.mdx
Labels: merge request

#4555 test: add a temporary `todo` for failing tests
  .github/workflows/quality.yml
  packages/react/src/components/avatar/avatar.test.tsx
  packages/react/src/components/button/button-group.test.tsx
  packages/react/src/components/card/card.test.tsx
  packages/react/src/components/container/container.test.tsx
  packages/react/src/components/scroll-area/scroll-area.test.tsx
  packages/react/src/components/textarea/textarea.test.tsx
  packages/react/src/components/textarea/use-autosize.test.tsx
  packages/react/src/components/visually-hidden/visually-hidden.test.tsx
  packages/react/src/core/css/css.test.tsx
Labels: merge request
