Repository yamada-ui/yamada-ui, pull requests merged in 2025-03, with the labels that each got.

#4554 Fixed `List` component documentation
  docs/contents/components/data-display/list/index.ja.mdx
  docs/contents/components/data-display/list/index.mdx
Labels: review wanted, merge request

#4561 test: add accessibility and rendering tests for <Flex />
  packages/react/src/components/flex/flex.test.tsx
Labels: review wanted, merge request

#4573 test: enhance icon component tests for accessibility and rendering
  packages/react/src/components/icon/icon.test.tsx
  packages/react/src/components/icon/lucide-icon.test.tsx
Labels: merge request

#4559 test: enhance <Field /> component tests for displayName, className, a…
  packages/react/src/components/field/field.test.tsx
Labels: review wanted, merge request

#4560 test: add tests for Fieldset component displayName, className, and HT…
  packages/react/src/components/fieldset/fieldset.test.tsx
Labels: merge request

#4568 test: enhance accessibility and validation tests for FormatByte and F…
  packages/react/src/components/format/format-byte.test.tsx
  packages/react/src/components/format/format-number.test.tsx
Labels: merge request

#4574 test: enhance accessibility and rendering tests for Image and Picture…
  packages/react/src/components/image/image.test.tsx
  packages/react/src/components/image/picture.test.tsx
  packages/react/src/components/image/picture.tsx
Labels: merge request

#4582 test: enhance NativeTable tests with accessibility checks and classNa…
  packages/react/src/components/native-table/native-table.test.tsx
Labels: merge request

#4562 test: add displayName and __ui__ properties to For component
  packages/react/src/components/for/for.test.tsx
  packages/react/src/components/for/for.tsx
Labels: merge request

#4565 feat(modal): support multiple `aria-labelledby` and `aria-describedby`
  packages/react/src/components/modal/use-modal.ts
Labels: review wanted

#4592 Updated contributors and members lists
  docs/constant/contributors.ts
  docs/constant/members.ts
  pnpm-lock.yaml
Labels: merge request

#4607 Updated `clip` to `clipPath` for hiding elements
  .changeset/sixty-apples-tie.md
  packages/components/visually-hidden/src/visually-hidden.tsx
  packages/components/visually-hidden/tests/visually-hidden.test.tsx
  packages/test/src/accessibility.tsx
Labels: merge request

#4608 Renamed `isLoading` to `loading` in `useProcessing`
  .changeset/clear-horses-slide.md
  packages/hooks/use-processing/src/index.ts
Labels: merge request

#4613 Test/wrap
  packages/react/src/components/wrap/wrap.test.tsx
Labels: merge request

#4420 feat(avatar): Internationalize `aria-label` in `avatar`
  cspell.json
  package.json
  packages/react/src/components/avatar/use-avatar.ts
  packages/react/src/core/pseudos.ts
  packages/react/src/core/theme/index.types.ts
  packages/react/src/hooks/use-controllable-state/index.ts
  packages/react/src/providers/i18n-provider/i18n-provider.tsx
  packages/react/src/providers/i18n-provider/intl/en-US.ts
  packages/react/src/providers/i18n-provider/intl/index.ts
  packages/react/src/providers/i18n-provider/intl/ja-JP.ts
  packages/react/src/providers/ui-provider/ui-provider.tsx
  packages/react/storybook/main.ts
  packages/react/storybook/preview.tsx
  packages/utils/src/i18n.test.ts
  packages/utils/src/i18n.ts
  packages/utils/src/index.ts
  packages/utils/src/index.types.ts
  pnpm-lock.yaml
Labels: review wanted, merge request

#4606 Unified `lazy` initialization logic
  .changeset/spicy-forks-pull.md
  packages/components/autocomplete/src/use-autocomplete.tsx
  packages/components/calendar/src/use-calendar-picker.ts
  packages/components/color-picker/src/use-color-picker.ts
  packages/components/select/src/use-select.tsx
Labels: merge request

#4619 test: update container component tests
  packages/react/src/components/container/container.test.tsx
Labels: merge request

#4623 Updated motion dependency and exports
  .changeset/witty-donuts-trade.md
  packages/components/motion/package.json
  packages/components/motion/src/index.ts
  packages/core/package.json
  pnpm-lock.yaml
Labels: merge request

#4624 Updated element comparison logic and tests
  .changeset/itchy-carpets-type.md
  packages/utils/src/react.tsx
  packages/utils/tests/react.test.tsx
Labels: merge request
